$axure.loadCurrentPage({
  "url":"faq.html",
  "generationDate":new Date(1412900044518.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"56f07779af344b3c87435dd0944c5f21",
    "type":"Axure:Page",
    "name":"FAQ",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"668d3368dd04418cba6844e6324a07aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":1100,
              "height":894},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce5b2ecb2cbc4299a4d49516e35240ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":1100,
                  "height":894},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"54b7d7ba524849c595c2601c6cfdd8d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":60,
              "y":834},
            "size":{
              "width":1100,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ee2f88c86f14cf1a8bc6dcbc9b6c98d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":60,
                  "y":834},
                "size":{
                  "width":1100,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"e79c6dfbfe7341a4b7f5f05889404a2a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":133},
            "size":{
              "width":1100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u4_line.png"}},
{
          "id":"a3fc8973311c4f828cd63744861ad850",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":854},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21d63b33ac964ba2b8926f6bb0435d67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":854},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a0a4c261d4c4f338d787671f5475ca8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":475,
              "y":854},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53971fbb1d4a4b41973762c76caaacca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":854},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a437165d909481f814a483fcea52402",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":888},
            "size":{
              "width":230,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6c5518be8c64459afd19672607de201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":888},
                "size":{
                  "width":230,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c4ff05078f746ebaa9676d2bd5441fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":475,
              "y":888},
            "size":{
              "width":230,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068654747081493cbbb55b69256de38c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":888},
                "size":{
                  "width":230,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37f282829e5f4fd890d4b8f36041278f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":931,
              "y":854},
            "size":{
              "width":84,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0144e4ea75a8486a923583cc84b2c726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":854},
                "size":{
                  "width":84,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d21095faacb427ea4994f194130aa2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":931,
              "y":888},
            "size":{
              "width":203,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d940196ec8f24f1d9977357c5881eac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":888},
                "size":{
                  "width":203,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6114f580bfac4dee982abf36be270bb1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":840,
              "y":854},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b2b93da43d44ea852ec1f726b4e7da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":840,
                  "y":854},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u31.png"}},
{
          "id":"ecec45325d4648c59be5e5362d603cda",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":843},
            "size":{
              "width":10,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u33_line.png"}},
{
          "id":"6967246cc29a4dbeb53d457b3de39213",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":843},
            "size":{
              "width":10,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u33_line.png"}},
{
          "id":"3e7338cf87c3463d9ea9847ba945010e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":414},
            "size":{
              "width":120,
              "height":286}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"right",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c1f00420b27443cbaa44241686cc5892",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bdc2fbace04844ad93baf0aca7f87b32",
                  "label":"",
                  "parentDynamicPanel":"3e7338cf87c3463d9ea9847ba945010e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":100,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84f402301ff84d25a2632d4ac450c7da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e7338cf87c3463d9ea9847ba945010e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":100,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u43.png"}},
{
                  "id":"31a360428cd24ab6b240f1c6ab659441",
                  "label":"",
                  "parentDynamicPanel":"3e7338cf87c3463d9ea9847ba945010e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":10,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"16511978e8814025a08545a7f3c8d251",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e7338cf87c3463d9ea9847ba945010e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":10,
                          "y":140},
                        "size":{
                          "width":100,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u43.png"}},
{
                  "id":"f6cec61611e2457b948997d52d667cf1",
                  "label":"",
                  "parentDynamicPanel":"3e7338cf87c3463d9ea9847ba945010e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":205},
                    "size":{
                      "width":37,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"494b3f5ca8644f29ab010532f855b335",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e7338cf87c3463d9ea9847ba945010e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":205},
                        "size":{
                          "width":37,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u47.png"}},
{
                  "id":"d6c20b6b24184b59b3e547c667a71bd1",
                  "label":"",
                  "parentDynamicPanel":"3e7338cf87c3463d9ea9847ba945010e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":38,
                      "y":69},
                    "size":{
                      "width":45,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8554d8bdc34f4afabfdbd2e9177fd478",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e7338cf87c3463d9ea9847ba945010e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":38,
                          "y":69},
                        "size":{
                          "width":45,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u49.png"}}]}]},
{
          "id":"9531fc5eaaed471ca522b49e8d414de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":137},
            "size":{
              "width":1100,
              "height":153}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"471205c310584882bd0e81f472005d9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":137},
                "size":{
                  "width":1100,
                  "height":153}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品/u42.png"}},
{
          "id":"ff5a36191e1c4b3598fd492bdc2f357e",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":329},
            "size":{
              "width":240,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fa40578194449a6b4e8bbafe36fb022",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":240,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9836966f27e64143b4f93f6467f428de",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":240,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9130ac1161ac4fd19f63b8d7849d4ce0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":240,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/产品/u48.png"}},
{
                  "id":"971b057e4ad7483896f2bbbb27c9d96a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":240,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfad12fc68e842dea39576754b5e70e1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":240,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/产品/u48.png"}},
{
                  "id":"c0e6738ed7e64f7d8da25e283ff66ea1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":240,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1267d17d2d645959a8aa1e220e55415",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":240,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/产品/u50.png"}}]}]},
{
          "id":"9c20ecccce904a6f923549fbf6b3c018",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "location":{
              "x":400,
              "y":329},
            "size":{
              "width":734,
              "height":366}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d749d944e98494596bc0de4a1255632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "location":{
                  "x":400,
                  "y":329},
                "size":{
                  "width":734,
                  "height":366}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edc57a9fd08f416bb84c18b3ae7bf1fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":588,
              "y":964},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01489fa939804c1c93b9bd930e4f091e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":588,
                  "y":964},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b41e88645494c1ab6a79bbca93878f3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":435},
            "size":{
              "width":240,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"424b6932a23b4e99bcfaf49a2e58ce06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":440},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fc6c8efd446446cbee186c9e1f35199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":440},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品/u55.png"}},
{
          "id":"f7187e43563b45258e15eee0bdddfe86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":100,
              "y":298},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63b6761582dd4db792d6c76a67e3c984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":298},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8ea3381f9b646c7b4921f9fcb61320d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":552,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8466b7b862684a479a149a1baa3d0167",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":552,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea45107b9025443fbc12ed048d8fbb14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":648,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1af02c3b7f341559fa78e8943361b85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":648,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品",
                      "target":{
                        "targetType":"page",
                        "url":"产品.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"453288f9dee246d580b3292449ac2118",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":744,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a0983b7d5d4246a3fc15c1ad403e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":744,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 案例",
                      "target":{
                        "targetType":"page",
                        "url":"案例.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ad8d41ccde940b389e476fb39b16111",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":840,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be0166fe3268424c825a0575ebb10bb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":840,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 报价",
                      "target":{
                        "targetType":"page",
                        "url":"报价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88324412db2247eeaf1cb8a6fa2d1f66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":936,
              "y":99},
            "size":{
              "width":39,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdb6963dec534257a487667c8a881be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":936,
                  "y":99},
                "size":{
                  "width":39,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 FAQ",
                      "target":{
                        "targetType":"page",
                        "url":"faq.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbdb2c877d9644f9a5fdd863e7974d26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":1034,
              "y":96},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c768b98d248c4a3f95a22f21ae97973c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":1034,
                  "y":96},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u15.png"}},
{
          "id":"0345476d21c04807af45321818c46144",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":86},
            "size":{
              "width":296,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f6d5e7b0184f0d9dfe44ee603ea77e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":86},
                "size":{
                  "width":296,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u76.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "668d3368dd04418cba6844e6324a07aa":{
      "scriptId":"u0"},
    "ce5b2ecb2cbc4299a4d49516e35240ce":{
      "scriptId":"u1"},
    "54b7d7ba524849c595c2601c6cfdd8d1":{
      "scriptId":"u2"},
    "5ee2f88c86f14cf1a8bc6dcbc9b6c98d":{
      "scriptId":"u3"},
    "e79c6dfbfe7341a4b7f5f05889404a2a":{
      "scriptId":"u4"},
    "a3fc8973311c4f828cd63744861ad850":{
      "scriptId":"u5"},
    "21d63b33ac964ba2b8926f6bb0435d67":{
      "scriptId":"u6"},
    "6a0a4c261d4c4f338d787671f5475ca8":{
      "scriptId":"u7"},
    "53971fbb1d4a4b41973762c76caaacca":{
      "scriptId":"u8"},
    "2a437165d909481f814a483fcea52402":{
      "scriptId":"u9"},
    "e6c5518be8c64459afd19672607de201":{
      "scriptId":"u10"},
    "6c4ff05078f746ebaa9676d2bd5441fa":{
      "scriptId":"u11"},
    "068654747081493cbbb55b69256de38c":{
      "scriptId":"u12"},
    "37f282829e5f4fd890d4b8f36041278f":{
      "scriptId":"u13"},
    "0144e4ea75a8486a923583cc84b2c726":{
      "scriptId":"u14"},
    "9d21095faacb427ea4994f194130aa2b":{
      "scriptId":"u15"},
    "d940196ec8f24f1d9977357c5881eac0":{
      "scriptId":"u16"},
    "6114f580bfac4dee982abf36be270bb1":{
      "scriptId":"u17"},
    "62b2b93da43d44ea852ec1f726b4e7da":{
      "scriptId":"u18"},
    "ecec45325d4648c59be5e5362d603cda":{
      "scriptId":"u19"},
    "6967246cc29a4dbeb53d457b3de39213":{
      "scriptId":"u20"},
    "3e7338cf87c3463d9ea9847ba945010e":{
      "scriptId":"u21"},
    "bdc2fbace04844ad93baf0aca7f87b32":{
      "scriptId":"u22"},
    "84f402301ff84d25a2632d4ac450c7da":{
      "scriptId":"u23"},
    "31a360428cd24ab6b240f1c6ab659441":{
      "scriptId":"u24"},
    "16511978e8814025a08545a7f3c8d251":{
      "scriptId":"u25"},
    "f6cec61611e2457b948997d52d667cf1":{
      "scriptId":"u26"},
    "494b3f5ca8644f29ab010532f855b335":{
      "scriptId":"u27"},
    "d6c20b6b24184b59b3e547c667a71bd1":{
      "scriptId":"u28"},
    "8554d8bdc34f4afabfdbd2e9177fd478":{
      "scriptId":"u29"},
    "9531fc5eaaed471ca522b49e8d414de5":{
      "scriptId":"u30"},
    "471205c310584882bd0e81f472005d9b":{
      "scriptId":"u31"},
    "ff5a36191e1c4b3598fd492bdc2f357e":{
      "scriptId":"u32"},
    "6fa40578194449a6b4e8bbafe36fb022":{
      "scriptId":"u33"},
    "9836966f27e64143b4f93f6467f428de":{
      "scriptId":"u34"},
    "9130ac1161ac4fd19f63b8d7849d4ce0":{
      "scriptId":"u35"},
    "971b057e4ad7483896f2bbbb27c9d96a":{
      "scriptId":"u36"},
    "bfad12fc68e842dea39576754b5e70e1":{
      "scriptId":"u37"},
    "c0e6738ed7e64f7d8da25e283ff66ea1":{
      "scriptId":"u38"},
    "e1267d17d2d645959a8aa1e220e55415":{
      "scriptId":"u39"},
    "9c20ecccce904a6f923549fbf6b3c018":{
      "scriptId":"u40"},
    "5d749d944e98494596bc0de4a1255632":{
      "scriptId":"u41"},
    "edc57a9fd08f416bb84c18b3ae7bf1fd":{
      "scriptId":"u42"},
    "01489fa939804c1c93b9bd930e4f091e":{
      "scriptId":"u43"},
    "2b41e88645494c1ab6a79bbca93878f3":{
      "scriptId":"u44"},
    "424b6932a23b4e99bcfaf49a2e58ce06":{
      "scriptId":"u45"},
    "5fc6c8efd446446cbee186c9e1f35199":{
      "scriptId":"u46"},
    "f7187e43563b45258e15eee0bdddfe86":{
      "scriptId":"u47"},
    "63b6761582dd4db792d6c76a67e3c984":{
      "scriptId":"u48"},
    "c8ea3381f9b646c7b4921f9fcb61320d":{
      "scriptId":"u49"},
    "8466b7b862684a479a149a1baa3d0167":{
      "scriptId":"u50"},
    "ea45107b9025443fbc12ed048d8fbb14":{
      "scriptId":"u51"},
    "c1af02c3b7f341559fa78e8943361b85":{
      "scriptId":"u52"},
    "453288f9dee246d580b3292449ac2118":{
      "scriptId":"u53"},
    "58a0983b7d5d4246a3fc15c1ad403e11":{
      "scriptId":"u54"},
    "1ad8d41ccde940b389e476fb39b16111":{
      "scriptId":"u55"},
    "be0166fe3268424c825a0575ebb10bb2":{
      "scriptId":"u56"},
    "88324412db2247eeaf1cb8a6fa2d1f66":{
      "scriptId":"u57"},
    "fdb6963dec534257a487667c8a881be4":{
      "scriptId":"u58"},
    "fbdb2c877d9644f9a5fdd863e7974d26":{
      "scriptId":"u59"},
    "c768b98d248c4a3f95a22f21ae97973c":{
      "scriptId":"u60"},
    "0345476d21c04807af45321818c46144":{
      "scriptId":"u61"},
    "14f6d5e7b0184f0d9dfe44ee603ea77e":{
      "scriptId":"u62"}}});