$axure.loadCurrentPage({
  "url":"notification.html",
  "generationDate":new Date(1427322485896.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b687cdff44244d77bd46acd3f72cef5c",
    "type":"Axure:Page",
    "name":"Notification",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d97e775b3c9e49ff8a928d7297ce54ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0x4CF2F2F2},
            "location":{
              "x":50,
              "y":33},
            "size":{
              "width":320,
              "height":568},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60e06e014c01474cb7c310398a05414c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0x4CF2F2F2},
                "location":{
                  "x":50,
                  "y":33},
                "size":{
                  "width":320,
                  "height":568},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u7.png"}},
{
          "id":"bfe9d0bba5e240c79475f12b396cc87f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":50,
              "y":33},
            "size":{
              "width":320,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67580a90e3a44e54a7589e05f1ac9882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":50,
                  "y":33},
                "size":{
                  "width":320,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u9.png"}},
{
          "id":"ed311e5200e246ffb1d8ea8a57cbddb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":56,
              "y":33},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05bdfbfd884f43dd928580aab83d1c79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":56,
                  "y":33},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"3654613d9f2244528849930912862c08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":50,
              "y":560},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4aa6bc968894fa590a6b71467750b86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":50,
                  "y":560},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u15.png"}},
{
          "id":"4c3332002ab448f2b5e52b602509a838",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":566},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98be63fa4c754ddeb57b5e8a9b416b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":566},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Add poll",
                      "target":{
                        "targetType":"page",
                        "url":"add_poll.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u17.png"}},
{
          "id":"54d3177c997147e2917fedd4e6cca219",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":570},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8327a2327e4a4f9c94141dfbac9a1cdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":570},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Search",
                      "target":{
                        "targetType":"page",
                        "url":"search.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"ed25536fb40a48dda1d94456504b0cf9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":569},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8519edf72b4518be796128b9aac86f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":569},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search/u12.png"}},
{
          "id":"f84c8471e32445b6abdc6525633f2f31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":569},
            "size":{
              "width":22,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f634c97e2bc340629ffb136abfd09fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":569},
                "size":{
                  "width":22,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Notification",
                      "target":{
                        "targetType":"page",
                        "url":"notification.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/notification/u14.png"}},
{
          "id":"2bae0102e0f44f389a45cb1134812daf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":569},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b33559512ede47a09616da77b12fb917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":326,
                  "y":569},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Me",
                      "target":{
                        "targetType":"page",
                        "url":"me.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u25.png"}},
{
          "id":"938f5c7c110d40b7bb9f2fd817f36706",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":194,
              "y":63},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a0d7fa7803a4adfabd4cadb1721088d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":194,
                  "y":63},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c81234f08e0498a9d61d95aec4d0b95",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":93},
            "size":{
              "width":320,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6860de36ed444f4c8c8c973f86a363e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77c2a864926745e283a6b1d1c2824190",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "lineSpacing":"20px",
                    "size":{
                      "width":320,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/notification/u21.png"}},
{
              "id":"b6a0a8e28a2349e7984419ec89753814",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2844f60c6894c7592058e6930ce2e80",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "lineSpacing":"20px",
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":320,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/notification/u21.png"}},
{
              "id":"a25c5cecd4d149059dffa8086b9fc1b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "lineSpacing":"20px",
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74e23449880c47898003cefd69472346",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "lineSpacing":"20px",
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":320,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/add_poll/u26.png"}}]},
{
          "id":"914a16ea8c1f466a90d23d1f1eaebf10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":285,
              "y":99},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d8a839e84a5495f8dcc99d380d60d85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":285,
                  "y":99},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e4c05f850bc41159027d2dcdeb10fc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":106},
            "size":{
              "width":26,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1af74bf675e64a2bbd686f78fbf2f071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":106},
                "size":{
                  "width":26,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notification/u29.png"}},
{
          "id":"32127fdee53840fc8d90a5370acd1102",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":285,
              "y":147},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d3a6d6e5adf4ab086584e56f06f1690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":285,
                  "y":147},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4514631c27b436badeee2cf11eb111f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":155},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a0d2ca9c3d1462fb659081fe5cc9d9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":155},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notification/u33.png"}},
{
          "id":"a191d9d1f7e0447daf0f10350a0648d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":205},
            "size":{
              "width":26,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f178fe46b544d3997a4a8b51529bc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":205},
                "size":{
                  "width":26,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notification/u29.png"}},
{
          "id":"d79fe014e7de4971a086c6c1fbabda72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":291,
              "y":197},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca504c7e28e74df68e552ba50ab4303c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":291,
                  "y":197},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f46e0eda4194459c9a5af264b2bcc4b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "paddingTop":"8",
            "location":{
              "x":63,
              "y":623},
            "size":{
              "width":300,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae635a7e8794478900b4e1952b8ebc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "paddingTop":"8",
                "location":{
                  "x":63,
                  "y":623},
                "size":{
                  "width":300,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notification/u39.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d97e775b3c9e49ff8a928d7297ce54ea":{
      "scriptId":"u0"},
    "60e06e014c01474cb7c310398a05414c":{
      "scriptId":"u1"},
    "bfe9d0bba5e240c79475f12b396cc87f":{
      "scriptId":"u2"},
    "67580a90e3a44e54a7589e05f1ac9882":{
      "scriptId":"u3"},
    "ed311e5200e246ffb1d8ea8a57cbddb7":{
      "scriptId":"u4"},
    "05bdfbfd884f43dd928580aab83d1c79":{
      "scriptId":"u5"},
    "3654613d9f2244528849930912862c08":{
      "scriptId":"u6"},
    "f4aa6bc968894fa590a6b71467750b86":{
      "scriptId":"u7"},
    "4c3332002ab448f2b5e52b602509a838":{
      "scriptId":"u8"},
    "98be63fa4c754ddeb57b5e8a9b416b5f":{
      "scriptId":"u9"},
    "54d3177c997147e2917fedd4e6cca219":{
      "scriptId":"u10"},
    "8327a2327e4a4f9c94141dfbac9a1cdc":{
      "scriptId":"u11"},
    "ed25536fb40a48dda1d94456504b0cf9":{
      "scriptId":"u12"},
    "dd8519edf72b4518be796128b9aac86f":{
      "scriptId":"u13"},
    "f84c8471e32445b6abdc6525633f2f31":{
      "scriptId":"u14"},
    "f634c97e2bc340629ffb136abfd09fa1":{
      "scriptId":"u15"},
    "2bae0102e0f44f389a45cb1134812daf":{
      "scriptId":"u16"},
    "b33559512ede47a09616da77b12fb917":{
      "scriptId":"u17"},
    "938f5c7c110d40b7bb9f2fd817f36706":{
      "scriptId":"u18"},
    "8a0d7fa7803a4adfabd4cadb1721088d":{
      "scriptId":"u19"},
    "3c81234f08e0498a9d61d95aec4d0b95":{
      "scriptId":"u20"},
    "6860de36ed444f4c8c8c973f86a363e8":{
      "scriptId":"u21"},
    "77c2a864926745e283a6b1d1c2824190":{
      "scriptId":"u22"},
    "b6a0a8e28a2349e7984419ec89753814":{
      "scriptId":"u23"},
    "f2844f60c6894c7592058e6930ce2e80":{
      "scriptId":"u24"},
    "a25c5cecd4d149059dffa8086b9fc1b8":{
      "scriptId":"u25"},
    "74e23449880c47898003cefd69472346":{
      "scriptId":"u26"},
    "914a16ea8c1f466a90d23d1f1eaebf10":{
      "scriptId":"u27"},
    "3d8a839e84a5495f8dcc99d380d60d85":{
      "scriptId":"u28"},
    "7e4c05f850bc41159027d2dcdeb10fc0":{
      "scriptId":"u29"},
    "1af74bf675e64a2bbd686f78fbf2f071":{
      "scriptId":"u30"},
    "32127fdee53840fc8d90a5370acd1102":{
      "scriptId":"u31"},
    "1d3a6d6e5adf4ab086584e56f06f1690":{
      "scriptId":"u32"},
    "b4514631c27b436badeee2cf11eb111f":{
      "scriptId":"u33"},
    "9a0d2ca9c3d1462fb659081fe5cc9d9c":{
      "scriptId":"u34"},
    "a191d9d1f7e0447daf0f10350a0648d7":{
      "scriptId":"u35"},
    "d6f178fe46b544d3997a4a8b51529bc0":{
      "scriptId":"u36"},
    "d79fe014e7de4971a086c6c1fbabda72":{
      "scriptId":"u37"},
    "ca504c7e28e74df68e552ba50ab4303c":{
      "scriptId":"u38"},
    "f46e0eda4194459c9a5af264b2bcc4b7":{
      "scriptId":"u39"},
    "cae635a7e8794478900b4e1952b8ebc9":{
      "scriptId":"u40"}}});