$axure.loadCurrentPage({
  "url":"个人首页-新用户.html",
  "generationDate":new Date(1413832591149.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"22f8f5c760ce42eda0878d9fd54d793c",
    "type":"Axure:Page",
    "name":"个人首页-新用户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1a600d03fbeb42ce9c7d4f3ac3a54870",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":62},
            "size":{
              "width":1200,
              "height":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eaa1748579e4990896309bdbd91fff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":62},
                "size":{
                  "width":1200,
                  "height":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"9403995c3ae94aaabf54e53a1084af92",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":286},
            "size":{
              "width":1115,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-新用户/u2_line.png"}},
{
          "id":"ff29b31d7bd04a42b27fbe29acfccade",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":612,
              "y":278},
            "size":{
              "width":160,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"666f3513dc584723a0b5013fec0c92b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":62},
            "size":{
              "width":1200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6222c400f1949c3b5e6711f1ee36ee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":62},
                "size":{
                  "width":1200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-新用户/u4.png"}},
{
          "id":"d5a92f6de03a4c7c9b99f86e16e42f35",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Futura Condensed Bold', 'Futura'",
            "fontSize":"28px",
            "fontWeight":"700",
            "fontStyle":"normal",
            "horizontalAlignment":"center",
            "location":{
              "x":135,
              "y":68},
            "size":{
              "width":76,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74293f9a673243e385f2601345f4dc9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Futura Condensed Bold', 'Futura'",
                "fontSize":"28px",
                "fontWeight":"700",
                "fontStyle":"normal",
                "horizontalAlignment":"center",
                "location":{
                  "x":135,
                  "y":68},
                "size":{
                  "width":76,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ecf31dacb5441a19c87480049074a2d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":62},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-新用户/u8_line.png"}},
{
          "id":"690d6848078541429f0daf846e33cda3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":282,
              "y":76},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e53c563bb7174f969edb681dc3383ebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":282,
                  "y":76},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"febf5bddc5ee4a43bd084e6a30e98d65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":1217,
              "y":76},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edaf652bc52645c19ee601d77d4f9cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":1217,
                  "y":76},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bca4d3b352a4c5cb884fee24cfb7187",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":74.5},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b812fe90f1748b48eb4f91c6eb85211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":74.5},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-新用户/u13.png"}},
{
          "id":"fde6aec5404244ba96461bbb0f8bd02b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":170},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9adfc6c367c94bb0a929b981f56c844c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":170},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人首页-老用户",
                      "target":{
                        "targetType":"page",
                        "url":"个人首页-老用户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人首页-新用户/u15.png"}},
{
          "id":"0afae3bf4ff242c593825bc0e027603b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":249,
              "y":170},
            "size":{
              "width":381,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4928c57b20541a7a58a2cea18f6fdca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":249,
                  "y":170},
                "size":{
                  "width":381,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-新用户/u17.png"}},
{
          "id":"ea96bef4e4a547efa41416ecd99de074",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":140,
              "y":330},
            "size":{
              "width":145,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e2f2124ab4846f8acbc7c1085800b91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":330},
                "size":{
                  "width":145,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce6a1475bf0246829f192c8d6fd978a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":764},
            "size":{
              "width":1200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1966c87b888044639cc5c22b86c5f582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":764},
                "size":{
                  "width":1200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-新用户/u4.png"}},
{
          "id":"cb193b55aecc4ff59cdaf84be6f86de6",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":780},
            "size":{
              "width":145,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0daf3affffbf443594ecfde94ec23b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":780},
                "size":{
                  "width":145,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "1a600d03fbeb42ce9c7d4f3ac3a54870":{
      "scriptId":"u0"},
    "2eaa1748579e4990896309bdbd91fff2":{
      "scriptId":"u1"},
    "9403995c3ae94aaabf54e53a1084af92":{
      "scriptId":"u2"},
    "ff29b31d7bd04a42b27fbe29acfccade":{
      "scriptId":"u3"},
    "666f3513dc584723a0b5013fec0c92b4":{
      "scriptId":"u4"},
    "c6222c400f1949c3b5e6711f1ee36ee3":{
      "scriptId":"u5"},
    "d5a92f6de03a4c7c9b99f86e16e42f35":{
      "scriptId":"u6"},
    "74293f9a673243e385f2601345f4dc9c":{
      "scriptId":"u7"},
    "7ecf31dacb5441a19c87480049074a2d":{
      "scriptId":"u8"},
    "690d6848078541429f0daf846e33cda3":{
      "scriptId":"u9"},
    "e53c563bb7174f969edb681dc3383ebb":{
      "scriptId":"u10"},
    "febf5bddc5ee4a43bd084e6a30e98d65":{
      "scriptId":"u11"},
    "edaf652bc52645c19ee601d77d4f9cc2":{
      "scriptId":"u12"},
    "2bca4d3b352a4c5cb884fee24cfb7187":{
      "scriptId":"u13"},
    "7b812fe90f1748b48eb4f91c6eb85211":{
      "scriptId":"u14"},
    "fde6aec5404244ba96461bbb0f8bd02b":{
      "scriptId":"u15"},
    "9adfc6c367c94bb0a929b981f56c844c":{
      "scriptId":"u16"},
    "0afae3bf4ff242c593825bc0e027603b":{
      "scriptId":"u17"},
    "b4928c57b20541a7a58a2cea18f6fdca":{
      "scriptId":"u18"},
    "ea96bef4e4a547efa41416ecd99de074":{
      "scriptId":"u19"},
    "5e2f2124ab4846f8acbc7c1085800b91":{
      "scriptId":"u20"},
    "ce6a1475bf0246829f192c8d6fd978a1":{
      "scriptId":"u21"},
    "1966c87b888044639cc5c22b86c5f582":{
      "scriptId":"u22"},
    "cb193b55aecc4ff59cdaf84be6f86de6":{
      "scriptId":"u23"},
    "0daf3affffbf443594ecfde94ec23b62":{
      "scriptId":"u24"}}});