$axure.loadCurrentPage({
  "url":"structure.html",
  "generationDate":new Date(1444085354143.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"780c77aff491484f9d411962a22d67a0",
    "type":"Axure:Page",
    "name":"Structure",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aa0f4b355a7946fb895de5dd6d034542",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":250,
              "y":180},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53982ed4920d42699d65e71446d36d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":250,
                  "y":180},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"5a5a454347e64630ba8fe331eb2b4d05",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":250,
              "y":520},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c4c67a181e54b1f908fc0d363d5e7eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":250,
                  "y":520},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"bdc6615f84f3440fa81aa56bce9da648",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":250,
              "y":910},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd328662874c4fbfa972a3b112b98f94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":250,
                  "y":910},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"d6c0ae77aed44fe48a46ce3f341cdf67",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":40},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2307357a7af4dec90b5d902b858c4d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":40},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"29ce63e85f644223ad5d6e66df84b02c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":130},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ce7ebd0990441e1885583e21d07fc92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":130},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"2b01552a916a4dffbcbbee811d9feca4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":230},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fe98141361d4261a26d8f48cbc47ea7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":230},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"ecf550b45d1a4772897c2c5b47f985fa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":320},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"098f11d44c054c11b52ecb0e2c12f17f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":320},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"82ce36ca533c4699b9d7215148462880",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":450},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ac0b9827b7c4ad6ac913a23e57999c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":450},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"3725d72d6da44ff784b73f0dba63ccd3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":580},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78bb10bdd31a45f2a8889f080b6f266b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":580},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"1c556b0736c9455f8bfcb5fabca462c1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":740,
              "y":490},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9491e2b8c8db4ef09064c52f378cc6d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":740,
                  "y":490},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"5a93f179a8a5470ca9b714b34f35ae09",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":740,
              "y":580},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d3c39199e1d416e901a906e550a7f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":740,
                  "y":580},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"ffc6be27a58e479c8181ba7e4031d801",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08c5fd02cd494ca5902f45d3806f02bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"1756021bd8824e088f95db4e649828e7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52272e655e034d79b9c07e94b5b12057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"385c6d5761dc40e38ac21a5d97b00772",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"721d0fcd5afe449f9b3d79e06bdca3a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"fed8c4269415426db79ccc3b83f0653f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83c2dba756034a7b82e3beea14536b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"0bdade45db5f4dd6941750e0d640ae51",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":740,
              "y":230},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fd4f8faeca94d3c9bd841bdc630cb78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":740,
                  "y":230},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"f38924ae6eaf49b6addc486aade771da",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a5af46515824d0fbdf0c437f89aa087",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"ad576c90c5da406aa6fb75cd6c6d4424",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":740,
              "y":670},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76de545d382f40389d07a33cc0be7c71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":740,
                  "y":670},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"05aa5fe9f33a4c3ca735b52db8a2f9b9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":970,
              "y":670},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63076ba2543446e286cdf6e0f90c3782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":970,
                  "y":670},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"f2abe1ac90894ccc82dc642ee8b2aa43",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":610},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23295f9f18114f32ad6ba5ce319e591a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":610},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"a1b8250292be474fabba320bb7337fec",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":970,
              "y":490},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"122cbe4c4d83495e9817963e98f2a1eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":970,
                  "y":490},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"ef56e1c1e9de4134a24d7269c76ecef8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"430c3861577543d2912af4d27be67b50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"0fafc51ae9bc4889a6d60b1a3717dd0e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":610},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"703c82a6c5984ec5960cf298e81d2ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":610},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"41528ab32f3b409985d62f680a16306b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":610},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c513ae938ce4411a8ff018b0a6a3dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":610},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"d0bddf35ad9945d5afee8043b2d32c7e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":700},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62fa2ea0f4e4e8e91fa6cbd4d067cef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":700},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"e9fb23f11fa94fb58a2a8fbc94449d5f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":550},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a6b633632cb493a80dbf012077d8678",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":550},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"10a1fa7b24ec4deca8e1d301a03d7d5e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":550},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ffea8daf3544a06940366ff16289a51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":550},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"c93d2de0614341049ff91da64494555e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":750},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7e7fb9f8c2c45d5a24b92408a682c18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":750},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"4378133cafab4735a514f2b4d5c6dc33",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":830},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4fa57796fe481da170d9917038fdf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":830},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"9a7b17ab2f5f4d97b191a4d7dd0172b4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":910},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b2002bbeeea49e2afc9bf408c15b997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":910},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"e457ec57865d4f00a84c3abcc9b189d4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":990},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42a1d468d3a747b1838a3ed6ad835196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":990},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"1ab22edb76d1435babfa50c9116b95a5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":520,
              "y":1070},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"404735bd310b44ce94c520ac16c17ef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":520,
                  "y":1070},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"11ec6ea44ea14e17ba9d2d6a45dd0dbf",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":940},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8888ca61b4d2469eaa6d77b552009c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":940},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"bc649d4349e64602aeace69c13019a8c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":940},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bee6a4870e6b4ac8bacf0b24d20713e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":940},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"bb20561f384b486cbd89d984b738a1d9",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":940},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79243e111bc8496c99ab54e22835a221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":940},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"2baef18769cc4df2a2b42920ae46e1ce",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":940},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e394f655ae4cb2b0ef145845f06d07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":940},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"ffb677fe7ce8413dbc5ff0a3e128200f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":940},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"719580869bfa48dcb67504f85c16db70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":940},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "aa0f4b355a7946fb895de5dd6d034542":{
      "scriptId":"u0"},
    "53982ed4920d42699d65e71446d36d91":{
      "scriptId":"u1"},
    "5a5a454347e64630ba8fe331eb2b4d05":{
      "scriptId":"u2"},
    "7c4c67a181e54b1f908fc0d363d5e7eb":{
      "scriptId":"u3"},
    "bdc6615f84f3440fa81aa56bce9da648":{
      "scriptId":"u4"},
    "bd328662874c4fbfa972a3b112b98f94":{
      "scriptId":"u5"},
    "d6c0ae77aed44fe48a46ce3f341cdf67":{
      "scriptId":"u6"},
    "a2307357a7af4dec90b5d902b858c4d0":{
      "scriptId":"u7"},
    "29ce63e85f644223ad5d6e66df84b02c":{
      "scriptId":"u8"},
    "9ce7ebd0990441e1885583e21d07fc92":{
      "scriptId":"u9"},
    "2b01552a916a4dffbcbbee811d9feca4":{
      "scriptId":"u10"},
    "7fe98141361d4261a26d8f48cbc47ea7":{
      "scriptId":"u11"},
    "ecf550b45d1a4772897c2c5b47f985fa":{
      "scriptId":"u12"},
    "098f11d44c054c11b52ecb0e2c12f17f":{
      "scriptId":"u13"},
    "82ce36ca533c4699b9d7215148462880":{
      "scriptId":"u14"},
    "9ac0b9827b7c4ad6ac913a23e57999c5":{
      "scriptId":"u15"},
    "3725d72d6da44ff784b73f0dba63ccd3":{
      "scriptId":"u16"},
    "78bb10bdd31a45f2a8889f080b6f266b":{
      "scriptId":"u17"},
    "1c556b0736c9455f8bfcb5fabca462c1":{
      "scriptId":"u18"},
    "9491e2b8c8db4ef09064c52f378cc6d3":{
      "scriptId":"u19"},
    "5a93f179a8a5470ca9b714b34f35ae09":{
      "scriptId":"u20"},
    "6d3c39199e1d416e901a906e550a7f48":{
      "scriptId":"u21"},
    "ffc6be27a58e479c8181ba7e4031d801":{
      "scriptId":"u22"},
    "08c5fd02cd494ca5902f45d3806f02bb":{
      "scriptId":"u23"},
    "1756021bd8824e088f95db4e649828e7":{
      "scriptId":"u24"},
    "52272e655e034d79b9c07e94b5b12057":{
      "scriptId":"u25"},
    "385c6d5761dc40e38ac21a5d97b00772":{
      "scriptId":"u26"},
    "721d0fcd5afe449f9b3d79e06bdca3a3":{
      "scriptId":"u27"},
    "fed8c4269415426db79ccc3b83f0653f":{
      "scriptId":"u28"},
    "83c2dba756034a7b82e3beea14536b8e":{
      "scriptId":"u29"},
    "0bdade45db5f4dd6941750e0d640ae51":{
      "scriptId":"u30"},
    "9fd4f8faeca94d3c9bd841bdc630cb78":{
      "scriptId":"u31"},
    "f38924ae6eaf49b6addc486aade771da":{
      "scriptId":"u32"},
    "0a5af46515824d0fbdf0c437f89aa087":{
      "scriptId":"u33"},
    "ad576c90c5da406aa6fb75cd6c6d4424":{
      "scriptId":"u34"},
    "76de545d382f40389d07a33cc0be7c71":{
      "scriptId":"u35"},
    "05aa5fe9f33a4c3ca735b52db8a2f9b9":{
      "scriptId":"u36"},
    "63076ba2543446e286cdf6e0f90c3782":{
      "scriptId":"u37"},
    "f2abe1ac90894ccc82dc642ee8b2aa43":{
      "scriptId":"u38"},
    "23295f9f18114f32ad6ba5ce319e591a":{
      "scriptId":"u39"},
    "a1b8250292be474fabba320bb7337fec":{
      "scriptId":"u40"},
    "122cbe4c4d83495e9817963e98f2a1eb":{
      "scriptId":"u41"},
    "ef56e1c1e9de4134a24d7269c76ecef8":{
      "scriptId":"u42"},
    "430c3861577543d2912af4d27be67b50":{
      "scriptId":"u43"},
    "0fafc51ae9bc4889a6d60b1a3717dd0e":{
      "scriptId":"u44"},
    "703c82a6c5984ec5960cf298e81d2ad6":{
      "scriptId":"u45"},
    "41528ab32f3b409985d62f680a16306b":{
      "scriptId":"u46"},
    "0c513ae938ce4411a8ff018b0a6a3dd8":{
      "scriptId":"u47"},
    "d0bddf35ad9945d5afee8043b2d32c7e":{
      "scriptId":"u48"},
    "d62fa2ea0f4e4e8e91fa6cbd4d067cef":{
      "scriptId":"u49"},
    "e9fb23f11fa94fb58a2a8fbc94449d5f":{
      "scriptId":"u50"},
    "7a6b633632cb493a80dbf012077d8678":{
      "scriptId":"u51"},
    "10a1fa7b24ec4deca8e1d301a03d7d5e":{
      "scriptId":"u52"},
    "6ffea8daf3544a06940366ff16289a51":{
      "scriptId":"u53"},
    "c93d2de0614341049ff91da64494555e":{
      "scriptId":"u54"},
    "e7e7fb9f8c2c45d5a24b92408a682c18":{
      "scriptId":"u55"},
    "4378133cafab4735a514f2b4d5c6dc33":{
      "scriptId":"u56"},
    "4e4fa57796fe481da170d9917038fdf6":{
      "scriptId":"u57"},
    "9a7b17ab2f5f4d97b191a4d7dd0172b4":{
      "scriptId":"u58"},
    "9b2002bbeeea49e2afc9bf408c15b997":{
      "scriptId":"u59"},
    "e457ec57865d4f00a84c3abcc9b189d4":{
      "scriptId":"u60"},
    "42a1d468d3a747b1838a3ed6ad835196":{
      "scriptId":"u61"},
    "1ab22edb76d1435babfa50c9116b95a5":{
      "scriptId":"u62"},
    "404735bd310b44ce94c520ac16c17ef1":{
      "scriptId":"u63"},
    "11ec6ea44ea14e17ba9d2d6a45dd0dbf":{
      "scriptId":"u64"},
    "8888ca61b4d2469eaa6d77b552009c52":{
      "scriptId":"u65"},
    "bc649d4349e64602aeace69c13019a8c":{
      "scriptId":"u66"},
    "bee6a4870e6b4ac8bacf0b24d20713e1":{
      "scriptId":"u67"},
    "bb20561f384b486cbd89d984b738a1d9":{
      "scriptId":"u68"},
    "79243e111bc8496c99ab54e22835a221":{
      "scriptId":"u69"},
    "2baef18769cc4df2a2b42920ae46e1ce":{
      "scriptId":"u70"},
    "45e394f655ae4cb2b0ef145845f06d07":{
      "scriptId":"u71"},
    "ffb677fe7ce8413dbc5ff0a3e128200f":{
      "scriptId":"u72"},
    "719580869bfa48dcb67504f85c16db70":{
      "scriptId":"u73"}}});