$axure.loadCurrentPage({
  "url":"自定义尺寸.html",
  "generationDate":new Date(1413832591993.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4f8c95917ff84df881be62f074443a9c",
    "type":"Axure:Page",
    "name":"自定义尺寸",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"14a73edd1c1a4caeb050b43c0b0e4c06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":62},
            "size":{
              "width":1200,
              "height":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8208bb814afd4ce08933b331c7e3abaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":62},
                "size":{
                  "width":1200,
                  "height":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"1f0eb3d975024206bd2877b71d7d9997",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":145},
            "size":{
              "width":1115,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-新用户/u2_line.png"}},
{
          "id":"89186078b3de4012aff5eff607bf0993",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":612,
              "y":137},
            "size":{
              "width":160,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6a7a10a2d86347cd8dbdcff4c76b3882",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":185},
            "size":{
              "width":200,
              "height":200},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7DB500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce5d2b2bd2504f2181eaa6717727884b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":185},
                "size":{
                  "width":200,
                  "height":200},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7DB500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片列表/u4.png"}},
{
          "id":"48e7245887854527acd432ddab633106",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":185},
            "size":{
              "width":200,
              "height":200},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7DB500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3286428738f0428f956924b895c5f99d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":185},
                "size":{
                  "width":200,
                  "height":200},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7DB500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片列表/u4.png"}},
{
          "id":"87b9b167107240a58761de2844a87c6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":185},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7740983cd20b4d01bbcf33cba94b26ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":185},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u4.png"}},
{
          "id":"7fe5558634a347b8a940749035f602f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":821,
              "y":185},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b140fcfa79734da58dfbf5298e5fa451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":821,
                  "y":185},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u4.png"}},
{
          "id":"77dd276ced5045ef93573e8515f7cf8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":185},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dc5a7646ba944e0a7d4e926b24cce65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1050,
                  "y":185},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u4.png"}},
{
          "id":"cd91bf3542a640a385d7c2ec24e49739",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":425},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f41a8e344dd48738e2ab466f5572ff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":425},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u4.png"}},
{
          "id":"f1ff3a8888214a9792011fc7b532b437",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":425},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad2870a5f8bd4e3c9d5164055eb9003d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":425},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u4.png"}},
{
          "id":"f356f5e3e0874ba098ac0ec4cefe567a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":425},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e20042efc6e4e338af224903058d801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":425},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u4.png"}},
{
          "id":"e753b4ff41774352a7f169e67484d02e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":821,
              "y":425},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8027371ca1c14ebcb525d78801d6cd85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":821,
                  "y":425},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u4.png"}},
{
          "id":"d73385d6c7664537968c2077ace0c909",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":62},
            "size":{
              "width":1200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2926c2105f4dfc98449a65a33f0cae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":62},
                "size":{
                  "width":1200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-新用户/u4.png"}},
{
          "id":"369b22145adb486998f3251b37589867",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Futura Condensed Bold', 'Futura'",
            "fontSize":"28px",
            "fontWeight":"700",
            "fontStyle":"normal",
            "horizontalAlignment":"center",
            "location":{
              "x":135,
              "y":68},
            "size":{
              "width":76,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df118faca2544ed786ba4cd36a5b4f6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Futura Condensed Bold', 'Futura'",
                "fontSize":"28px",
                "fontWeight":"700",
                "fontStyle":"normal",
                "horizontalAlignment":"center",
                "location":{
                  "x":135,
                  "y":68},
                "size":{
                  "width":76,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f39fff3ec094cd6a301ccd8be972e1f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":62},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-新用户/u8_line.png"}},
{
          "id":"9028b185f747430bb8b1456561095154",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":282,
              "y":76},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c30466278254040ba9c5c34eced39d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":282,
                  "y":76},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b62db75d7ee44164ba95927bb2d91f26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":1217,
              "y":76},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1dba6ddb0e149b3a236e47fe56ead95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":1217,
                  "y":76},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f845a5d5ca814dc88036c1d56a7be6be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":74},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cef4ac9f9c4042b4be4e8a9cd77d5d7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":74},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-新用户/u13.png"}},
{
          "id":"f62a0f6d1f2744fcaef147c3596c247b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":764},
            "size":{
              "width":1200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41dd1e349b484a6493826c5e8f9ad2a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":764},
                "size":{
                  "width":1200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-新用户/u4.png"}},
{
          "id":"c4c314fdc76a4e6093ee56e6c50dd2d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":425},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"274bc118fba74654995b042d0ccbea1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1050,
                  "y":425},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u4.png"}},
{
          "id":"11baf1063ec74c8ab9983e9550a9fc84",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":780},
            "size":{
              "width":145,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86d892322ca04528aa308f603d37f60b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":780},
                "size":{
                  "width":145,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"37c54477be134c0e8cf96e119722baf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":780},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26ad8d66b6e4411b9c24b23bfc3d574b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":780},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88f9a5d724394413bb46ea5751352701",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":780},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dacd4ba0d7341148ee40fabb3f2a8f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":780},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0e62442e658479db60178861a6085f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":780},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cb369562d2a420bb3557c33ecf46c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":780},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"392a74003fbc40d5bac2d06601b08596",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":389,
              "y":780},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"519f1f9f2c9c4db2a1ae50f88fb32aaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":389,
                  "y":780},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbefeaf079f14cefafdc71a6f8f3c196",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":473,
              "y":780},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d71e71f2e7d54a5ab84606182259b999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":473,
                  "y":780},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a34a1e2d9a4416fbf54ae53863ba93b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":568,
              "y":780},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e21da446526144e5bdba85786f82835b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":568,
                  "y":780},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4f1a047a1fd4a1ea54949d91d1640ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":669},
            "size":{
              "width":200,
              "height":95},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a917dc0e785405d86756d80abcb4b3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":669},
                "size":{
                  "width":200,
                  "height":95},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片列表/u51.png"}},
{
          "id":"ed5cd5349a154918abe54b63332b3d68",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":669},
            "size":{
              "width":200,
              "height":95},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0535ef00d55745c9abffea8ddce86eb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":669},
                "size":{
                  "width":200,
                  "height":95},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片列表/u51.png"}},
{
          "id":"c5cee22fe5f14d1a8260c5aa61b12d02",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":669},
            "size":{
              "width":200,
              "height":95},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5aab10a61f1442b9fa82bf54b2cf9e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":669},
                "size":{
                  "width":200,
                  "height":95},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片列表/u51.png"}},
{
          "id":"3f5f35832f194b9b9b101660f8dcdce9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":821,
              "y":669},
            "size":{
              "width":200,
              "height":95},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29fb0d76384d4e8a9c7cb8288b83e3e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":821,
                  "y":669},
                "size":{
                  "width":200,
                  "height":95},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片列表/u51.png"}},
{
          "id":"491e05806d344a7ba640711e7fffe170",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":669},
            "size":{
              "width":200,
              "height":95},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f6156c5115d487d836d26887bbdb9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":669},
                "size":{
                  "width":200,
                  "height":95},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片列表/u51.png"}},
{
          "id":"c02507a0b36a459ab759d71951cdbfed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "location":{
              "x":91,
              "y":62},
            "size":{
              "width":1198,
              "height":750},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"621daec67d1b44be96897dad8517f1e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "location":{
                  "x":91,
                  "y":62},
                "size":{
                  "width":1198,
                  "height":750},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自定义尺寸/u61.png"}},
{
          "id":"3c8f4297fce14fc79dae5eea5831e443",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":270},
            "size":{
              "width":657,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ba31679477447fdbc78d509ffc8c315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":270},
                "size":{
                  "width":657,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自定义尺寸/u63.png"}},
{
          "id":"bf714dfc12af4a2098570b759e8eb25f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":380,
              "y":283},
            "size":{
              "width":113,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5756c3fdc2ae46889abe42fa580a2109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":380,
                  "y":283},
                "size":{
                  "width":113,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c381d51a78a494c915b5d22a9ae60d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":709,
              "y":332},
            "size":{
              "width":291,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bae50c0019943c2a71da1cc9fc07fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":709,
                  "y":332},
                "size":{
                  "width":291,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d140d0f092b48a0a41058af2d528230",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":746,
              "y":330},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"31fdb17c4491415688acdff3be082705",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":897,
              "y":330},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a82a8fc9fe924ff196f9fa232907aa3d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"bottom",
            "location":{
              "x":709,
              "y":365},
            "size":{
              "width":192,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a170da3906144ba82d210ee48768a76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"bottom",
                "location":{
                  "x":709,
                  "y":365},
                "size":{
                  "width":192,
                  "height":20}},
              "adaptiveStyles":{
}}]},
{
          "id":"7dca64cba17643dbb3b4b3f718ca866e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"bottom",
            "location":{
              "x":709,
              "y":395},
            "size":{
              "width":192,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9094f637673d44cb9100a103b9b41924",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"bottom",
                "location":{
                  "x":709,
                  "y":395},
                "size":{
                  "width":192,
                  "height":20}},
              "adaptiveStyles":{
}}]},
{
          "id":"85d7371b739c4a17bfa37f0f6c37537c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"bottom",
            "location":{
              "x":709,
              "y":425},
            "size":{
              "width":192,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf98680b9c0d456eb32c07141282266c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"bottom",
                "location":{
                  "x":709,
                  "y":425},
                "size":{
                  "width":192,
                  "height":20}},
              "adaptiveStyles":{
}}]},
{
          "id":"73b178b2c7ed4d66808cd2533c72d8e4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"bottom",
            "location":{
              "x":709,
              "y":455},
            "size":{
              "width":192,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb061b1378ea44c880d44e1267d671c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"bottom",
                "location":{
                  "x":709,
                  "y":455},
                "size":{
                  "width":192,
                  "height":20}},
              "adaptiveStyles":{
}}]},
{
          "id":"44914ae517154566880245ae70519068",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":709,
              "y":498},
            "size":{
              "width":83,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 复制成功_批量自定义 向下滑动 300 ms 置于顶层",
                      "objectsToFades":[{
                          "objectPath":["04211297dcc1464a901841794add8efc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":300,
                              "showType":"front"}}}]},
{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 复制成功_批量自定义 向上滑动 300 ms",
                      "objectsToFades":[{
                          "objectPath":["04211297dcc1464a901841794add8efc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideUp",
                              "duration":300,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"5ec92265242b40df84d90c5a8880d568",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":365,
              "y":315},
            "size":{
              "width":319,
              "height":225},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"874f583780ea42ff8ec489e256b8ab4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":365,
                  "y":315},
                "size":{
                  "width":319,
                  "height":225},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自定义尺寸/u80.png"}},
{
          "id":"c69d71881479482d8c11615bb174f18a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":322},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18a40e848b11497aae8830d033aed3b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":322},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自定义尺寸/u82.png"}},
{
          "id":"50aee0c7a2b04022b160fe398ac7418b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":322},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95e90c6353d94f05be4ec433839ccb3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":322},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自定义尺寸/u82.png"}},
{
          "id":"02ef2f8a94d14da7b71a9f7d87be1af6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":310},
            "size":{
              "width":655,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/自定义尺寸/u86_line.png"}},
{
          "id":"10d08db3c3234939b6779a2f0f6bdac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":990,
              "y":280},
            "size":{
              "width":16,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f9c72bb83140ffbce63d9b599c2d0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":990,
                  "y":280},
                "size":{
                  "width":16,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 图片列表",
                      "target":{
                        "targetType":"page",
                        "url":"图片列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e02d4e360639424dae8ecaa6b4e49bfe",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":811,
              "y":498},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 复制成功_批量自定义 向下滑动 300 ms 置于顶层",
                      "objectsToFades":[{
                          "objectPath":["04211297dcc1464a901841794add8efc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":300,
                              "showType":"front"}}}]},
{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 复制成功_批量自定义 向上滑动 300 ms",
                      "objectsToFades":[{
                          "objectPath":["04211297dcc1464a901841794add8efc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideUp",
                              "duration":300,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"a6903d0550c14ca49d83d1246aa5bc23",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":910,
              "y":498},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 复制成功_批量自定义 向下滑动 300 ms 置于顶层",
                      "objectsToFades":[{
                          "objectPath":["04211297dcc1464a901841794add8efc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":300,
                              "showType":"front"}}}]},
{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 复制成功_批量自定义 向上滑动 300 ms",
                      "objectsToFades":[{
                          "objectPath":["04211297dcc1464a901841794add8efc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideUp",
                              "duration":300,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"04211297dcc1464a901841794add8efc",
          "label":"复制成功_批量自定义",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF7DB500},
            "location":{
              "x":642.5,
              "y":278.5},
            "size":{
              "width":100,
              "height":30},
            "visible":false,
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86385a5cc68046d8bdde528c51eb36ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7DB500},
                "location":{
                  "x":642.5,
                  "y":278.5},
                "size":{
                  "width":100,
                  "height":30},
                "visible":false,
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/复制成功_u51.png"}},
{
          "id":"56ec21effc564a8cbf667c361d23b768",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":372},
            "size":{
              "width":10,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF00FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-老用户/u58_line.png"}},
{
          "id":"e702dedeb7484a30b1d9403d37cb7c76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF00FF},
            "location":{
              "x":388,
              "y":372},
            "size":{
              "width":9,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF00FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e500bab7a1fc4eb5878264c0891f5be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF00FF},
                "location":{
                  "x":388,
                  "y":372},
                "size":{
                  "width":9,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF00FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-老用户/u59.png"}},
{
          "id":"af48ebf24c8a4fdc86736851e3bebdbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":376,
              "y":418},
            "size":{
              "width":125,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e87c8ef6cafb401889c1f5b3e2b26db7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":376,
                  "y":418},
                "size":{
                  "width":125,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片列表/u71.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "14a73edd1c1a4caeb050b43c0b0e4c06":{
      "scriptId":"u0"},
    "8208bb814afd4ce08933b331c7e3abaf":{
      "scriptId":"u1"},
    "1f0eb3d975024206bd2877b71d7d9997":{
      "scriptId":"u2"},
    "89186078b3de4012aff5eff607bf0993":{
      "scriptId":"u3"},
    "6a7a10a2d86347cd8dbdcff4c76b3882":{
      "scriptId":"u4"},
    "ce5d2b2bd2504f2181eaa6717727884b":{
      "scriptId":"u5"},
    "48e7245887854527acd432ddab633106":{
      "scriptId":"u6"},
    "3286428738f0428f956924b895c5f99d":{
      "scriptId":"u7"},
    "87b9b167107240a58761de2844a87c6e":{
      "scriptId":"u8"},
    "7740983cd20b4d01bbcf33cba94b26ed":{
      "scriptId":"u9"},
    "7fe5558634a347b8a940749035f602f3":{
      "scriptId":"u10"},
    "b140fcfa79734da58dfbf5298e5fa451":{
      "scriptId":"u11"},
    "77dd276ced5045ef93573e8515f7cf8c":{
      "scriptId":"u12"},
    "1dc5a7646ba944e0a7d4e926b24cce65":{
      "scriptId":"u13"},
    "cd91bf3542a640a385d7c2ec24e49739":{
      "scriptId":"u14"},
    "7f41a8e344dd48738e2ab466f5572ff3":{
      "scriptId":"u15"},
    "f1ff3a8888214a9792011fc7b532b437":{
      "scriptId":"u16"},
    "ad2870a5f8bd4e3c9d5164055eb9003d":{
      "scriptId":"u17"},
    "f356f5e3e0874ba098ac0ec4cefe567a":{
      "scriptId":"u18"},
    "2e20042efc6e4e338af224903058d801":{
      "scriptId":"u19"},
    "e753b4ff41774352a7f169e67484d02e":{
      "scriptId":"u20"},
    "8027371ca1c14ebcb525d78801d6cd85":{
      "scriptId":"u21"},
    "d73385d6c7664537968c2077ace0c909":{
      "scriptId":"u22"},
    "5f2926c2105f4dfc98449a65a33f0cae":{
      "scriptId":"u23"},
    "369b22145adb486998f3251b37589867":{
      "scriptId":"u24"},
    "df118faca2544ed786ba4cd36a5b4f6f":{
      "scriptId":"u25"},
    "5f39fff3ec094cd6a301ccd8be972e1f":{
      "scriptId":"u26"},
    "9028b185f747430bb8b1456561095154":{
      "scriptId":"u27"},
    "8c30466278254040ba9c5c34eced39d4":{
      "scriptId":"u28"},
    "b62db75d7ee44164ba95927bb2d91f26":{
      "scriptId":"u29"},
    "b1dba6ddb0e149b3a236e47fe56ead95":{
      "scriptId":"u30"},
    "f845a5d5ca814dc88036c1d56a7be6be":{
      "scriptId":"u31"},
    "cef4ac9f9c4042b4be4e8a9cd77d5d7c":{
      "scriptId":"u32"},
    "f62a0f6d1f2744fcaef147c3596c247b":{
      "scriptId":"u33"},
    "41dd1e349b484a6493826c5e8f9ad2a0":{
      "scriptId":"u34"},
    "c4c314fdc76a4e6093ee56e6c50dd2d3":{
      "scriptId":"u35"},
    "274bc118fba74654995b042d0ccbea1e":{
      "scriptId":"u36"},
    "11baf1063ec74c8ab9983e9550a9fc84":{
      "scriptId":"u37"},
    "86d892322ca04528aa308f603d37f60b":{
      "scriptId":"u38"},
    "37c54477be134c0e8cf96e119722baf6":{
      "scriptId":"u39"},
    "26ad8d66b6e4411b9c24b23bfc3d574b":{
      "scriptId":"u40"},
    "88f9a5d724394413bb46ea5751352701":{
      "scriptId":"u41"},
    "3dacd4ba0d7341148ee40fabb3f2a8f6":{
      "scriptId":"u42"},
    "d0e62442e658479db60178861a6085f3":{
      "scriptId":"u43"},
    "4cb369562d2a420bb3557c33ecf46c63":{
      "scriptId":"u44"},
    "392a74003fbc40d5bac2d06601b08596":{
      "scriptId":"u45"},
    "519f1f9f2c9c4db2a1ae50f88fb32aaf":{
      "scriptId":"u46"},
    "cbefeaf079f14cefafdc71a6f8f3c196":{
      "scriptId":"u47"},
    "d71e71f2e7d54a5ab84606182259b999":{
      "scriptId":"u48"},
    "9a34a1e2d9a4416fbf54ae53863ba93b":{
      "scriptId":"u49"},
    "e21da446526144e5bdba85786f82835b":{
      "scriptId":"u50"},
    "d4f1a047a1fd4a1ea54949d91d1640ff":{
      "scriptId":"u51"},
    "5a917dc0e785405d86756d80abcb4b3b":{
      "scriptId":"u52"},
    "ed5cd5349a154918abe54b63332b3d68":{
      "scriptId":"u53"},
    "0535ef00d55745c9abffea8ddce86eb7":{
      "scriptId":"u54"},
    "c5cee22fe5f14d1a8260c5aa61b12d02":{
      "scriptId":"u55"},
    "d5aab10a61f1442b9fa82bf54b2cf9e9":{
      "scriptId":"u56"},
    "3f5f35832f194b9b9b101660f8dcdce9":{
      "scriptId":"u57"},
    "29fb0d76384d4e8a9c7cb8288b83e3e3":{
      "scriptId":"u58"},
    "491e05806d344a7ba640711e7fffe170":{
      "scriptId":"u59"},
    "9f6156c5115d487d836d26887bbdb9ef":{
      "scriptId":"u60"},
    "c02507a0b36a459ab759d71951cdbfed":{
      "scriptId":"u61"},
    "621daec67d1b44be96897dad8517f1e9":{
      "scriptId":"u62"},
    "3c8f4297fce14fc79dae5eea5831e443":{
      "scriptId":"u63"},
    "5ba31679477447fdbc78d509ffc8c315":{
      "scriptId":"u64"},
    "bf714dfc12af4a2098570b759e8eb25f":{
      "scriptId":"u65"},
    "5756c3fdc2ae46889abe42fa580a2109":{
      "scriptId":"u66"},
    "6c381d51a78a494c915b5d22a9ae60d7":{
      "scriptId":"u67"},
    "0bae50c0019943c2a71da1cc9fc07fba":{
      "scriptId":"u68"},
    "3d140d0f092b48a0a41058af2d528230":{
      "scriptId":"u69"},
    "31fdb17c4491415688acdff3be082705":{
      "scriptId":"u70"},
    "a82a8fc9fe924ff196f9fa232907aa3d":{
      "scriptId":"u71"},
    "8a170da3906144ba82d210ee48768a76":{
      "scriptId":"u72"},
    "7dca64cba17643dbb3b4b3f718ca866e":{
      "scriptId":"u73"},
    "9094f637673d44cb9100a103b9b41924":{
      "scriptId":"u74"},
    "85d7371b739c4a17bfa37f0f6c37537c":{
      "scriptId":"u75"},
    "cf98680b9c0d456eb32c07141282266c":{
      "scriptId":"u76"},
    "73b178b2c7ed4d66808cd2533c72d8e4":{
      "scriptId":"u77"},
    "eb061b1378ea44c880d44e1267d671c4":{
      "scriptId":"u78"},
    "44914ae517154566880245ae70519068":{
      "scriptId":"u79"},
    "5ec92265242b40df84d90c5a8880d568":{
      "scriptId":"u80"},
    "874f583780ea42ff8ec489e256b8ab4a":{
      "scriptId":"u81"},
    "c69d71881479482d8c11615bb174f18a":{
      "scriptId":"u82"},
    "18a40e848b11497aae8830d033aed3b2":{
      "scriptId":"u83"},
    "50aee0c7a2b04022b160fe398ac7418b":{
      "scriptId":"u84"},
    "95e90c6353d94f05be4ec433839ccb3e":{
      "scriptId":"u85"},
    "02ef2f8a94d14da7b71a9f7d87be1af6":{
      "scriptId":"u86"},
    "10d08db3c3234939b6779a2f0f6bdac8":{
      "scriptId":"u87"},
    "c8f9c72bb83140ffbce63d9b599c2d0d":{
      "scriptId":"u88"},
    "e02d4e360639424dae8ecaa6b4e49bfe":{
      "scriptId":"u89"},
    "a6903d0550c14ca49d83d1246aa5bc23":{
      "scriptId":"u90"},
    "04211297dcc1464a901841794add8efc":{
      "scriptId":"u91"},
    "86385a5cc68046d8bdde528c51eb36ac":{
      "scriptId":"u92"},
    "56ec21effc564a8cbf667c361d23b768":{
      "scriptId":"u93"},
    "e702dedeb7484a30b1d9403d37cb7c76":{
      "scriptId":"u94"},
    "e500bab7a1fc4eb5878264c0891f5be9":{
      "scriptId":"u95"},
    "af48ebf24c8a4fdc86736851e3bebdbb":{
      "scriptId":"u96"},
    "e87c8ef6cafb401889c1f5b3e2b26db7":{
      "scriptId":"u97"}}});