$axure.loadCurrentPage({
  "url":"报价详单.html",
  "generationDate":new Date(1412900044306.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bd1b3184d7604eeb98c5839537313d26",
    "type":"Axure:Page",
    "name":"报价详单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3eaf9a89da6d4f2591752ca17c21c8ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":1100,
              "height":894},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fed398546e78496282c44810cf90edaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":1100,
                  "height":894},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"ecf2863d1bc1476db95ef3b1df720521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":60,
              "y":834},
            "size":{
              "width":1100,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff8bcfde4fcc4f6babda8c68138b227d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":60,
                  "y":834},
                "size":{
                  "width":1100,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"78c313b3d2b4401687fb4909f324d132",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":854},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe878ca729a042cfae4b97eebc649365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":854},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb042b9845fc462295e2a1d25a1f9819",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":475,
              "y":854},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"865fe9947a88420badad71fb11f34a58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":854},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8489b8ad00ad468e80ce21e0dff8f242",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":888},
            "size":{
              "width":230,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92e30eb11b2424bbab2ca6e416dea80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":888},
                "size":{
                  "width":230,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"183443e1713d4334b23cf0de774aea71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":475,
              "y":888},
            "size":{
              "width":230,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db03a3d1fbab4b369f0873afedd433b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":888},
                "size":{
                  "width":230,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f48d4edb8787466ebd155b66d92dd400",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":931,
              "y":854},
            "size":{
              "width":84,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f68bfb12b0e4dd8bd571e7059ca197a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":854},
                "size":{
                  "width":84,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e1d5f26090542818af7a58c43be7298",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":931,
              "y":888},
            "size":{
              "width":203,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10b8869683a148e3ad118e289039547e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":888},
                "size":{
                  "width":203,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"298099d21ea146dd9ba1a28af314da28",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":840,
              "y":854},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad2979ce05f44daf9db59cc6e04d645b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":840,
                  "y":854},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u31.png"}},
{
          "id":"7aafc8da5d75495dab2d0075a87b5600",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":843},
            "size":{
              "width":10,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u33_line.png"}},
{
          "id":"a1f914729bc24fc2ae1bf76e85a21d9e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":843},
            "size":{
              "width":10,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u33_line.png"}},
{
          "id":"417c3501ee3a4b9b9d1f800f27e7334e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":414},
            "size":{
              "width":120,
              "height":286}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"right",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9e01c5daaf67404e8b29d75ccc6fa5ff",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0958cce67c6f4063bb461f9403fe81d8",
                  "label":"",
                  "parentDynamicPanel":"417c3501ee3a4b9b9d1f800f27e7334e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":100,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf3eac22ad2143efadaa477feeabba31",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"417c3501ee3a4b9b9d1f800f27e7334e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":100,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u43.png"}},
{
                  "id":"6f33eadade68431dbb318268842d2916",
                  "label":"",
                  "parentDynamicPanel":"417c3501ee3a4b9b9d1f800f27e7334e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":10,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66a04f0d1a774a29826e476bb4c73c73",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"417c3501ee3a4b9b9d1f800f27e7334e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":10,
                          "y":140},
                        "size":{
                          "width":100,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u43.png"}},
{
                  "id":"63dd742721fd4e8183ed8a112811ab98",
                  "label":"",
                  "parentDynamicPanel":"417c3501ee3a4b9b9d1f800f27e7334e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":205},
                    "size":{
                      "width":37,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b9491e15d6354ad4930c759f4436f83f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"417c3501ee3a4b9b9d1f800f27e7334e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":205},
                        "size":{
                          "width":37,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u47.png"}},
{
                  "id":"ed9776805e8447ea8c13e82b329e0a65",
                  "label":"",
                  "parentDynamicPanel":"417c3501ee3a4b9b9d1f800f27e7334e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":38,
                      "y":69},
                    "size":{
                      "width":45,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0927db5dd7d0428e8d86d910c2ba4711",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"417c3501ee3a4b9b9d1f800f27e7334e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":38,
                          "y":69},
                        "size":{
                          "width":45,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u49.png"}}]}]},
{
          "id":"5f8f3f2697be49ae81c71999214ae35a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":588,
              "y":964},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b62f56919e4d33840d6c1d20d5974b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":588,
                  "y":964},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43e9cd0de52047ec97fd3caec98ce1e3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":133},
            "size":{
              "width":1100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u4_line.png"}},
{
          "id":"7786d05aaa974d84ac78e7bac18a68af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":137},
            "size":{
              "width":1100,
              "height":153}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90019863c1fc46b98f7e7ccd3189c63d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":137},
                "size":{
                  "width":1100,
                  "height":153}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品/u42.png"}},
{
          "id":"3be658f575f84ae382d4cfb4b9f34054",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":243,
              "y":330},
            "size":{
              "width":734,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2770ac56fb4b447f99fb53a9cb996545",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":243,
                  "y":330},
                "size":{
                  "width":734,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc0d1eb0b6424ba3b30ba0d653e788c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":100,
              "y":298},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"492f853a1f364cb886092b22b8fac5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":298},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"492348dc56d5481d853f6dbec2fb7ebe",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":380},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c192c6efefa640d0ba9008a1a33430dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05b2d9a723d64e7e84019be3f8a96d06",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u39.png"}},
{
              "id":"93c3e05081394ba3ac77bd23f1e2cf66",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7cccca6cfe242e48043e61b7d9dd56c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u39.png"}},
{
              "id":"73727e6313ec4f369074249de427adeb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7fc359b5ab8947a0b57b57a742c60f62",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u51.png"}},
{
              "id":"bc8e6157887747698d39fbdaa2407474",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16bb86369cc440cdb4fe3c79e9707c2b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u39.png"}},
{
              "id":"a44ce9420b63448dab34b1b77716efef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1abaccd095574f52bd6eba414b7aee82",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u39.png"}},
{
              "id":"c8265266b01b45559f8c6849fd7bb97f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22c5624b87d74a5da2563148aa5432cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u51.png"}},
{
              "id":"d7772c9706c74bf4b13fa4964e4329ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f390f531a9841c59d019bb1db527635",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u43.png"}},
{
              "id":"a85183ef50894c25a3be1ada74d527a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a5b7db585b948c79628602ba81d1e86",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u43.png"}},
{
              "id":"5e6c0f06ec434111a420ccba35892807",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04ff4068684b42968a775f8f5b8900ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价详单/u55.png"}}]},
{
          "id":"f1e5d3087cbd4ba984593bb33d5b442a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":552,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e89094c2dd9a40229121e64e97bd7b89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":552,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecb4df8e263045e4aab8e69cdf8e253e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":648,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62624a7a8b7f400fa027b44c4ed91889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":648,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品",
                      "target":{
                        "targetType":"page",
                        "url":"产品.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cee761bcfb7543f1b6745d246017803c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":744,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f90823d4112243269779c53194110fa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":744,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 案例",
                      "target":{
                        "targetType":"page",
                        "url":"案例.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b63658c343274bebbf5a11a347ab4335",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":840,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a8a583ced54312b7670f84199427bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":840,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 报价",
                      "target":{
                        "targetType":"page",
                        "url":"报价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e48f51c193f4825b1cec3df623ab93c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":936,
              "y":99},
            "size":{
              "width":39,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52caafc151a54c15ad10a3a317069173",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":936,
                  "y":99},
                "size":{
                  "width":39,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 FAQ",
                      "target":{
                        "targetType":"page",
                        "url":"faq.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bc306a330dd415c925ebcdc0047b916",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":1034,
              "y":96},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5197f97613f46e382720a26945036e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":1034,
                  "y":96},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u15.png"}},
{
          "id":"3e1ea05cc6974b86a7fbb919f3ef0f4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":86},
            "size":{
              "width":296,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91437d94b82a49aba661a64605945426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":86},
                "size":{
                  "width":296,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u76.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3eaf9a89da6d4f2591752ca17c21c8ce":{
      "scriptId":"u0"},
    "fed398546e78496282c44810cf90edaf":{
      "scriptId":"u1"},
    "ecf2863d1bc1476db95ef3b1df720521":{
      "scriptId":"u2"},
    "ff8bcfde4fcc4f6babda8c68138b227d":{
      "scriptId":"u3"},
    "78c313b3d2b4401687fb4909f324d132":{
      "scriptId":"u4"},
    "fe878ca729a042cfae4b97eebc649365":{
      "scriptId":"u5"},
    "fb042b9845fc462295e2a1d25a1f9819":{
      "scriptId":"u6"},
    "865fe9947a88420badad71fb11f34a58":{
      "scriptId":"u7"},
    "8489b8ad00ad468e80ce21e0dff8f242":{
      "scriptId":"u8"},
    "d92e30eb11b2424bbab2ca6e416dea80":{
      "scriptId":"u9"},
    "183443e1713d4334b23cf0de774aea71":{
      "scriptId":"u10"},
    "db03a3d1fbab4b369f0873afedd433b1":{
      "scriptId":"u11"},
    "f48d4edb8787466ebd155b66d92dd400":{
      "scriptId":"u12"},
    "4f68bfb12b0e4dd8bd571e7059ca197a":{
      "scriptId":"u13"},
    "6e1d5f26090542818af7a58c43be7298":{
      "scriptId":"u14"},
    "10b8869683a148e3ad118e289039547e":{
      "scriptId":"u15"},
    "298099d21ea146dd9ba1a28af314da28":{
      "scriptId":"u16"},
    "ad2979ce05f44daf9db59cc6e04d645b":{
      "scriptId":"u17"},
    "7aafc8da5d75495dab2d0075a87b5600":{
      "scriptId":"u18"},
    "a1f914729bc24fc2ae1bf76e85a21d9e":{
      "scriptId":"u19"},
    "417c3501ee3a4b9b9d1f800f27e7334e":{
      "scriptId":"u20"},
    "0958cce67c6f4063bb461f9403fe81d8":{
      "scriptId":"u21"},
    "bf3eac22ad2143efadaa477feeabba31":{
      "scriptId":"u22"},
    "6f33eadade68431dbb318268842d2916":{
      "scriptId":"u23"},
    "66a04f0d1a774a29826e476bb4c73c73":{
      "scriptId":"u24"},
    "63dd742721fd4e8183ed8a112811ab98":{
      "scriptId":"u25"},
    "b9491e15d6354ad4930c759f4436f83f":{
      "scriptId":"u26"},
    "ed9776805e8447ea8c13e82b329e0a65":{
      "scriptId":"u27"},
    "0927db5dd7d0428e8d86d910c2ba4711":{
      "scriptId":"u28"},
    "5f8f3f2697be49ae81c71999214ae35a":{
      "scriptId":"u29"},
    "62b62f56919e4d33840d6c1d20d5974b":{
      "scriptId":"u30"},
    "43e9cd0de52047ec97fd3caec98ce1e3":{
      "scriptId":"u31"},
    "7786d05aaa974d84ac78e7bac18a68af":{
      "scriptId":"u32"},
    "90019863c1fc46b98f7e7ccd3189c63d":{
      "scriptId":"u33"},
    "3be658f575f84ae382d4cfb4b9f34054":{
      "scriptId":"u34"},
    "2770ac56fb4b447f99fb53a9cb996545":{
      "scriptId":"u35"},
    "bc0d1eb0b6424ba3b30ba0d653e788c4":{
      "scriptId":"u36"},
    "492f853a1f364cb886092b22b8fac5cf":{
      "scriptId":"u37"},
    "492348dc56d5481d853f6dbec2fb7ebe":{
      "scriptId":"u38"},
    "c192c6efefa640d0ba9008a1a33430dc":{
      "scriptId":"u39"},
    "05b2d9a723d64e7e84019be3f8a96d06":{
      "scriptId":"u40"},
    "bc8e6157887747698d39fbdaa2407474":{
      "scriptId":"u41"},
    "16bb86369cc440cdb4fe3c79e9707c2b":{
      "scriptId":"u42"},
    "d7772c9706c74bf4b13fa4964e4329ea":{
      "scriptId":"u43"},
    "5f390f531a9841c59d019bb1db527635":{
      "scriptId":"u44"},
    "93c3e05081394ba3ac77bd23f1e2cf66":{
      "scriptId":"u45"},
    "e7cccca6cfe242e48043e61b7d9dd56c":{
      "scriptId":"u46"},
    "a44ce9420b63448dab34b1b77716efef":{
      "scriptId":"u47"},
    "1abaccd095574f52bd6eba414b7aee82":{
      "scriptId":"u48"},
    "a85183ef50894c25a3be1ada74d527a2":{
      "scriptId":"u49"},
    "4a5b7db585b948c79628602ba81d1e86":{
      "scriptId":"u50"},
    "73727e6313ec4f369074249de427adeb":{
      "scriptId":"u51"},
    "7fc359b5ab8947a0b57b57a742c60f62":{
      "scriptId":"u52"},
    "c8265266b01b45559f8c6849fd7bb97f":{
      "scriptId":"u53"},
    "22c5624b87d74a5da2563148aa5432cf":{
      "scriptId":"u54"},
    "5e6c0f06ec434111a420ccba35892807":{
      "scriptId":"u55"},
    "04ff4068684b42968a775f8f5b8900ff":{
      "scriptId":"u56"},
    "f1e5d3087cbd4ba984593bb33d5b442a":{
      "scriptId":"u57"},
    "e89094c2dd9a40229121e64e97bd7b89":{
      "scriptId":"u58"},
    "ecb4df8e263045e4aab8e69cdf8e253e":{
      "scriptId":"u59"},
    "62624a7a8b7f400fa027b44c4ed91889":{
      "scriptId":"u60"},
    "cee761bcfb7543f1b6745d246017803c":{
      "scriptId":"u61"},
    "f90823d4112243269779c53194110fa8":{
      "scriptId":"u62"},
    "b63658c343274bebbf5a11a347ab4335":{
      "scriptId":"u63"},
    "f4a8a583ced54312b7670f84199427bf":{
      "scriptId":"u64"},
    "4e48f51c193f4825b1cec3df623ab93c":{
      "scriptId":"u65"},
    "52caafc151a54c15ad10a3a317069173":{
      "scriptId":"u66"},
    "9bc306a330dd415c925ebcdc0047b916":{
      "scriptId":"u67"},
    "a5197f97613f46e382720a26945036e8":{
      "scriptId":"u68"},
    "3e1ea05cc6974b86a7fbb919f3ef0f4c":{
      "scriptId":"u69"},
    "91437d94b82a49aba661a64605945426":{
      "scriptId":"u70"}}});