$axure.loadCurrentPage({
  "url":"个人首页-无图片.html",
  "generationDate":new Date(1428494664140.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"22f8f5c760ce42eda0878d9fd54d793c",
    "type":"Axure:Page",
    "name":"个人首页-无图片",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1a600d03fbeb42ce9c7d4f3ac3a54870",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":62},
            "size":{
              "width":1200,
              "height":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eaa1748579e4990896309bdbd91fff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":62},
                "size":{
                  "width":1200,
                  "height":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"9403995c3ae94aaabf54e53a1084af92",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":286},
            "size":{
              "width":1115,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-无图片/u2_line.png"}},
{
          "id":"ff29b31d7bd04a42b27fbe29acfccade",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":612,
              "y":278},
            "size":{
              "width":160,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"666f3513dc584723a0b5013fec0c92b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":62},
            "size":{
              "width":1200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6222c400f1949c3b5e6711f1ee36ee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":62},
                "size":{
                  "width":1200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u4.png"}},
{
          "id":"d5a92f6de03a4c7c9b99f86e16e42f35",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Futura Condensed Bold', 'Futura'",
            "fontSize":"28px",
            "fontWeight":"700",
            "fontStyle":"normal",
            "horizontalAlignment":"center",
            "location":{
              "x":135,
              "y":68},
            "size":{
              "width":76,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74293f9a673243e385f2601345f4dc9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Futura Condensed Bold', 'Futura'",
                "fontSize":"28px",
                "fontWeight":"700",
                "fontStyle":"normal",
                "horizontalAlignment":"center",
                "location":{
                  "x":135,
                  "y":68},
                "size":{
                  "width":76,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ecf31dacb5441a19c87480049074a2d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":62},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-无图片/u8_line.png"}},
{
          "id":"690d6848078541429f0daf846e33cda3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":282,
              "y":76},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e53c563bb7174f969edb681dc3383ebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":282,
                  "y":76},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"febf5bddc5ee4a43bd084e6a30e98d65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":1217,
              "y":76},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edaf652bc52645c19ee601d77d4f9cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":1217,
                  "y":76},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bca4d3b352a4c5cb884fee24cfb7187",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":74.5},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b812fe90f1748b48eb4f91c6eb85211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":74.5},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u13.png"}},
{
          "id":"fde6aec5404244ba96461bbb0f8bd02b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":170},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9adfc6c367c94bb0a929b981f56c844c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":170},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 正在上传",
                      "target":{
                        "targetType":"page",
                        "url":"正在上传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人首页-无图片/u15.png"}},
{
          "id":"0afae3bf4ff242c593825bc0e027603b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "location":{
              "x":249,
              "y":170},
            "size":{
              "width":381,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4928c57b20541a7a58a2cea18f6fdca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "location":{
                  "x":249,
                  "y":170},
                "size":{
                  "width":381,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u17.png"}},
{
          "id":"ea96bef4e4a547efa41416ecd99de074",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":140,
              "y":330},
            "size":{
              "width":145,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e2f2124ab4846f8acbc7c1085800b91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":330},
                "size":{
                  "width":145,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce6a1475bf0246829f192c8d6fd978a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":764},
            "size":{
              "width":1200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1966c87b888044639cc5c22b86c5f582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":764},
                "size":{
                  "width":1200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u4.png"}},
{
          "id":"cb193b55aecc4ff59cdaf84be6f86de6",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":135,
              "y":780},
            "size":{
              "width":145,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0daf3affffbf443594ecfde94ec23b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":135,
                  "y":780},
                "size":{
                  "width":145,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"5b62da1a8cc640bcbbc43744db2037ff",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":176},
            "size":{
              "width":200,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf791c3abd754613a559e26eb33ac271",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ba813c02d57405fab90765baa6bdb90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"ac4331cf661d4280a8af4e809c9b036a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f288e97c3294f49b75f85d069b0468f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"8922865d27f340eaa29aa3afbead691c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91910500b0f34ee1bd84b3d2290e21c7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"109aad16b9484128881f1f48d658795f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c216198580f0411f8aa4711642694c02",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"8e5d064f352c472e9490ca72ce7dc72d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2441a33248246979c4b740397f2cc11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"aba0277357a0492b8b7404396548ed8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b64c80d85544c16b195efbe33e37ff9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}}]},
{
          "id":"2023b2d669984cbc867ad4ccc4052be8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF7DB500},
            "location":{
              "x":950,
              "y":136},
            "size":{
              "width":70,
              "height":30},
            "borderWidth":"-1",
            "linePattern":"none",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fe22a53ca8d4c60a61f75f23be467fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7DB500},
                "location":{
                  "x":950,
                  "y":136},
                "size":{
                  "width":70,
                  "height":30},
                "borderWidth":"-1",
                "linePattern":"none",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u38.png"}},
{
          "id":"a483c3e14eff4222a5ede0348b19596b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":1090,
              "y":242},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ef51f8654747579a826e41ea836da7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":1090,
                  "y":242},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 尺寸配置",
                      "target":{
                        "targetType":"page",
                        "url":"尺寸配置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fd5a3867a084119be63761e61e7f749",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":306,
              "y":780},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724dfd71adcf47dc89bdbba9f6ca086c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":780},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4492dc8dec88437bae7e896ca8e137f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":383,
              "y":780},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a0d73074a3f478ca0c9a562cb7d9886",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":383,
                  "y":780},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9f12125c5ae48d582663c1ed584ea1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":433,
              "y":780},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e21f194677094c7bbb55480f02e34be2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":433,
                  "y":780},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1a600d03fbeb42ce9c7d4f3ac3a54870":{
      "scriptId":"u0"},
    "2eaa1748579e4990896309bdbd91fff2":{
      "scriptId":"u1"},
    "9403995c3ae94aaabf54e53a1084af92":{
      "scriptId":"u2"},
    "ff29b31d7bd04a42b27fbe29acfccade":{
      "scriptId":"u3"},
    "666f3513dc584723a0b5013fec0c92b4":{
      "scriptId":"u4"},
    "c6222c400f1949c3b5e6711f1ee36ee3":{
      "scriptId":"u5"},
    "d5a92f6de03a4c7c9b99f86e16e42f35":{
      "scriptId":"u6"},
    "74293f9a673243e385f2601345f4dc9c":{
      "scriptId":"u7"},
    "7ecf31dacb5441a19c87480049074a2d":{
      "scriptId":"u8"},
    "690d6848078541429f0daf846e33cda3":{
      "scriptId":"u9"},
    "e53c563bb7174f969edb681dc3383ebb":{
      "scriptId":"u10"},
    "febf5bddc5ee4a43bd084e6a30e98d65":{
      "scriptId":"u11"},
    "edaf652bc52645c19ee601d77d4f9cc2":{
      "scriptId":"u12"},
    "2bca4d3b352a4c5cb884fee24cfb7187":{
      "scriptId":"u13"},
    "7b812fe90f1748b48eb4f91c6eb85211":{
      "scriptId":"u14"},
    "fde6aec5404244ba96461bbb0f8bd02b":{
      "scriptId":"u15"},
    "9adfc6c367c94bb0a929b981f56c844c":{
      "scriptId":"u16"},
    "0afae3bf4ff242c593825bc0e027603b":{
      "scriptId":"u17"},
    "b4928c57b20541a7a58a2cea18f6fdca":{
      "scriptId":"u18"},
    "ea96bef4e4a547efa41416ecd99de074":{
      "scriptId":"u19"},
    "5e2f2124ab4846f8acbc7c1085800b91":{
      "scriptId":"u20"},
    "ce6a1475bf0246829f192c8d6fd978a1":{
      "scriptId":"u21"},
    "1966c87b888044639cc5c22b86c5f582":{
      "scriptId":"u22"},
    "cb193b55aecc4ff59cdaf84be6f86de6":{
      "scriptId":"u23"},
    "0daf3affffbf443594ecfde94ec23b62":{
      "scriptId":"u24"},
    "5b62da1a8cc640bcbbc43744db2037ff":{
      "scriptId":"u25"},
    "bf791c3abd754613a559e26eb33ac271":{
      "scriptId":"u26"},
    "2ba813c02d57405fab90765baa6bdb90":{
      "scriptId":"u27"},
    "109aad16b9484128881f1f48d658795f":{
      "scriptId":"u28"},
    "c216198580f0411f8aa4711642694c02":{
      "scriptId":"u29"},
    "ac4331cf661d4280a8af4e809c9b036a":{
      "scriptId":"u30"},
    "2f288e97c3294f49b75f85d069b0468f":{
      "scriptId":"u31"},
    "8e5d064f352c472e9490ca72ce7dc72d":{
      "scriptId":"u32"},
    "e2441a33248246979c4b740397f2cc11":{
      "scriptId":"u33"},
    "8922865d27f340eaa29aa3afbead691c":{
      "scriptId":"u34"},
    "91910500b0f34ee1bd84b3d2290e21c7":{
      "scriptId":"u35"},
    "aba0277357a0492b8b7404396548ed8b":{
      "scriptId":"u36"},
    "8b64c80d85544c16b195efbe33e37ff9":{
      "scriptId":"u37"},
    "2023b2d669984cbc867ad4ccc4052be8":{
      "scriptId":"u38"},
    "7fe22a53ca8d4c60a61f75f23be467fa":{
      "scriptId":"u39"},
    "a483c3e14eff4222a5ede0348b19596b":{
      "scriptId":"u40"},
    "d3ef51f8654747579a826e41ea836da7":{
      "scriptId":"u41"},
    "7fd5a3867a084119be63761e61e7f749":{
      "scriptId":"u42"},
    "724dfd71adcf47dc89bdbba9f6ca086c":{
      "scriptId":"u43"},
    "4492dc8dec88437bae7e896ca8e137f5":{
      "scriptId":"u44"},
    "4a0d73074a3f478ca0c9a562cb7d9886":{
      "scriptId":"u45"},
    "f9f12125c5ae48d582663c1ed584ea1c":{
      "scriptId":"u46"},
    "e21f194677094c7bbb55480f02e34be2":{
      "scriptId":"u47"}}});