$axure.loadCurrentPage({
  "url":"已登录.html",
  "generationDate":new Date(1412900044914.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba0ab1628e6b4d5484fef69ecf18804f",
    "type":"Axure:Page",
    "name":"已登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"08181e20950f4c7ca741cb73edffcd8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":1100,
              "height":894},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d23da17bc844c6d97eec95a3909cfc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":1100,
                  "height":894},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"7c7f9ca360614dbc9ee645d6e235f6af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":60,
              "y":834},
            "size":{
              "width":1100,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36ffa3f9a1414e55bfffb12da89a308e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":60,
                  "y":834},
                "size":{
                  "width":1100,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"6b1c50845c9f44f28d754abc1af7b18a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":854},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cb6acf953c448c9803c79d3f62b8c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":854},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40a9ca6c8dd74577abc377addadb296c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":475,
              "y":854},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e597943a3d484848b43d1fe15d06ddb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":854},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49d5b3bd91834980b811a1a5bd7afc88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":888},
            "size":{
              "width":230,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94faf29adac44965812a65c99c654453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":888},
                "size":{
                  "width":230,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ad1db29da6c44bc884e111603ecd107",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":475,
              "y":888},
            "size":{
              "width":230,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd9e53634de441bfb7bc5aa5f8113a6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":888},
                "size":{
                  "width":230,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"348f5e8ccf5a4d37a1f5ce13b21f73d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":931,
              "y":854},
            "size":{
              "width":84,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edae9fc841954f459c4ef13ff6534158",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":854},
                "size":{
                  "width":84,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fdeb2367cca473198f5230be6186ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":931,
              "y":888},
            "size":{
              "width":203,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ca3ec1fe3984e518fd013638cac3fb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":888},
                "size":{
                  "width":203,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a18370b81d640a3ae18b277398bacd5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":840,
              "y":854},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9e6501ac0a34003b2fbaac56ffd27f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":840,
                  "y":854},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u31.png"}},
{
          "id":"19568b9f61044271be3adfaffadc30e1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":843},
            "size":{
              "width":10,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u33_line.png"}},
{
          "id":"c0f40a695e4a4b4a90be0a45a04f14ff",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":843},
            "size":{
              "width":10,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u33_line.png"}},
{
          "id":"9214a10130124c4d925f0bce044e94b7",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":414},
            "size":{
              "width":120,
              "height":286}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"right",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ffe497b365bc4480bf742adca302ce74",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e1c358dbc3ff44729249269f5d84beb3",
                  "label":"",
                  "parentDynamicPanel":"9214a10130124c4d925f0bce044e94b7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":100,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8b586870ac34a2ba9a5be198b8bfc2d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9214a10130124c4d925f0bce044e94b7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":100,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u43.png"}},
{
                  "id":"52cd7d0cb4c94d518e1c89c895eb6927",
                  "label":"",
                  "parentDynamicPanel":"9214a10130124c4d925f0bce044e94b7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":10,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb187c887a8c4313930dc60fd2ece9c3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9214a10130124c4d925f0bce044e94b7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":10,
                          "y":140},
                        "size":{
                          "width":100,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u43.png"}},
{
                  "id":"a7f202003fe443829c9283eada4ce7b9",
                  "label":"",
                  "parentDynamicPanel":"9214a10130124c4d925f0bce044e94b7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":205},
                    "size":{
                      "width":37,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e37c060ca9314196a02fac2aa4f8dee0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9214a10130124c4d925f0bce044e94b7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":205},
                        "size":{
                          "width":37,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u47.png"}},
{
                  "id":"13463bf011964ed18473cabcab7e8ac5",
                  "label":"",
                  "parentDynamicPanel":"9214a10130124c4d925f0bce044e94b7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":38,
                      "y":69},
                    "size":{
                      "width":45,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51f88fff4d0b48e0b0dc0937f8aa5dff",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9214a10130124c4d925f0bce044e94b7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":38,
                          "y":69},
                        "size":{
                          "width":45,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u49.png"}}]}]},
{
          "id":"c9046e5f893541d0b5a9d1aa5503e012",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":588,
              "y":964},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82af7bcc88f54d9cb348e03e47fd2ea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":588,
                  "y":964},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fec02f20e87b4b38bad44ffec68fde17",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":133},
            "size":{
              "width":1100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u4_line.png"}},
{
          "id":"1f8a7452fd954a59bb5a33be37b38dc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":137},
            "size":{
              "width":1100,
              "height":153}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5e08676928448bda8bfb604430b9824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":137},
                "size":{
                  "width":1100,
                  "height":153}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品/u42.png"}},
{
          "id":"e5739cbbaf8241dfbb0e659cfe2bc592",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":100,
              "y":298},
            "size":{
              "width":95,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e2d2655fa36431ba97b1653537b1889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":298},
                "size":{
                  "width":95,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc7ccf3bda47487580437215de0e296c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":370},
            "size":{
              "width":190,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cf0a4faf0c344b29460f670283424b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":370},
                "size":{
                  "width":190,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 虚拟机文件下载",
                      "target":{
                        "targetType":"page",
                        "url":"虚拟机文件下载.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/已登录/u36.png"}},
{
          "id":"112a4e20a05d4f2b9d3b4be8d8eef4db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":370},
            "size":{
              "width":190,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67eb685fec604c15a302c29ab1e15b2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":370},
                "size":{
                  "width":190,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Changelog查看",
                      "target":{
                        "targetType":"page",
                        "url":"changelog__.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/已登录/u36.png"}},
{
          "id":"5b92ee48f1c94717b4e9183f9e3f2615",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":370},
            "size":{
              "width":190,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b95847f443244feb58203691f376680",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":370},
                "size":{
                  "width":190,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 相关文档下载",
                      "target":{
                        "targetType":"page",
                        "url":"相关文档下载.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/已登录/u36.png"}},
{
          "id":"b446451b75794e4dac9cd1e691a63606",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":178,
              "y":590},
            "size":{
              "width":155,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6425e7713314a05bb81ba8ddb21ab1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":178,
                  "y":590},
                "size":{
                  "width":155,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 虚拟机文件下载",
                      "target":{
                        "targetType":"page",
                        "url":"虚拟机文件下载.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85b320a6ad9745078f1c4c874f7d21b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":516,
              "y":590},
            "size":{
              "width":158,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4140354068d54e93bf4cf07899dc4c0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":516,
                  "y":590},
                "size":{
                  "width":158,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Changelog查看",
                      "target":{
                        "targetType":"page",
                        "url":"changelog__.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94c57eaba8094d05b427be14307524cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":892,
              "y":590},
            "size":{
              "width":85,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efc15ac2ee8c4c99b24dd6d9e98fb3ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":892,
                  "y":590},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 相关文档下载",
                      "target":{
                        "targetType":"page",
                        "url":"相关文档下载.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"782a30cb28b8492b93a9c4f8dcb286e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":552,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b4aa4871844fde908efe0dfb942ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":552,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3c7364b3a7b4979bd2d0034e9ab8efa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":648,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51d2a9b1a5fa4413b1f4c4714be3f713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":648,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品",
                      "target":{
                        "targetType":"page",
                        "url":"产品.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9376c8d0fee54f068662db17ab660998",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":744,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d955e71e9b664384b30a93bf370c7593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":744,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 案例",
                      "target":{
                        "targetType":"page",
                        "url":"案例.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"342f73c18a5d4606b417feaa6d7c9548",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":840,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aab7f72fcad443b089bc21cfe147b124",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":840,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 报价",
                      "target":{
                        "targetType":"page",
                        "url":"报价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81486d98db8d464bbb1c5bd99e4f952c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":936,
              "y":99},
            "size":{
              "width":39,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88c039b15bee444289743389696a9675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":936,
                  "y":99},
                "size":{
                  "width":39,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 FAQ",
                      "target":{
                        "targetType":"page",
                        "url":"faq.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1ead64c797949c2ae0298b74e77e8a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":1034,
              "y":96},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a92f154db1c94411aacc0011124cb7bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":1034,
                  "y":96},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u15.png"}},
{
          "id":"9b3c7db3049848d4b9d2d016c5c82f2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":86},
            "size":{
              "width":296,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25b1e1d4294b4538a0ed5f5493bb3fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":86},
                "size":{
                  "width":296,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u76.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "08181e20950f4c7ca741cb73edffcd8f":{
      "scriptId":"u0"},
    "2d23da17bc844c6d97eec95a3909cfc6":{
      "scriptId":"u1"},
    "7c7f9ca360614dbc9ee645d6e235f6af":{
      "scriptId":"u2"},
    "36ffa3f9a1414e55bfffb12da89a308e":{
      "scriptId":"u3"},
    "6b1c50845c9f44f28d754abc1af7b18a":{
      "scriptId":"u4"},
    "4cb6acf953c448c9803c79d3f62b8c07":{
      "scriptId":"u5"},
    "40a9ca6c8dd74577abc377addadb296c":{
      "scriptId":"u6"},
    "e597943a3d484848b43d1fe15d06ddb5":{
      "scriptId":"u7"},
    "49d5b3bd91834980b811a1a5bd7afc88":{
      "scriptId":"u8"},
    "94faf29adac44965812a65c99c654453":{
      "scriptId":"u9"},
    "9ad1db29da6c44bc884e111603ecd107":{
      "scriptId":"u10"},
    "fd9e53634de441bfb7bc5aa5f8113a6b":{
      "scriptId":"u11"},
    "348f5e8ccf5a4d37a1f5ce13b21f73d8":{
      "scriptId":"u12"},
    "edae9fc841954f459c4ef13ff6534158":{
      "scriptId":"u13"},
    "5fdeb2367cca473198f5230be6186ae9":{
      "scriptId":"u14"},
    "8ca3ec1fe3984e518fd013638cac3fb3":{
      "scriptId":"u15"},
    "8a18370b81d640a3ae18b277398bacd5":{
      "scriptId":"u16"},
    "b9e6501ac0a34003b2fbaac56ffd27f1":{
      "scriptId":"u17"},
    "19568b9f61044271be3adfaffadc30e1":{
      "scriptId":"u18"},
    "c0f40a695e4a4b4a90be0a45a04f14ff":{
      "scriptId":"u19"},
    "9214a10130124c4d925f0bce044e94b7":{
      "scriptId":"u20"},
    "e1c358dbc3ff44729249269f5d84beb3":{
      "scriptId":"u21"},
    "f8b586870ac34a2ba9a5be198b8bfc2d":{
      "scriptId":"u22"},
    "52cd7d0cb4c94d518e1c89c895eb6927":{
      "scriptId":"u23"},
    "eb187c887a8c4313930dc60fd2ece9c3":{
      "scriptId":"u24"},
    "a7f202003fe443829c9283eada4ce7b9":{
      "scriptId":"u25"},
    "e37c060ca9314196a02fac2aa4f8dee0":{
      "scriptId":"u26"},
    "13463bf011964ed18473cabcab7e8ac5":{
      "scriptId":"u27"},
    "51f88fff4d0b48e0b0dc0937f8aa5dff":{
      "scriptId":"u28"},
    "c9046e5f893541d0b5a9d1aa5503e012":{
      "scriptId":"u29"},
    "82af7bcc88f54d9cb348e03e47fd2ea1":{
      "scriptId":"u30"},
    "fec02f20e87b4b38bad44ffec68fde17":{
      "scriptId":"u31"},
    "1f8a7452fd954a59bb5a33be37b38dc5":{
      "scriptId":"u32"},
    "c5e08676928448bda8bfb604430b9824":{
      "scriptId":"u33"},
    "e5739cbbaf8241dfbb0e659cfe2bc592":{
      "scriptId":"u34"},
    "2e2d2655fa36431ba97b1653537b1889":{
      "scriptId":"u35"},
    "bc7ccf3bda47487580437215de0e296c":{
      "scriptId":"u36"},
    "1cf0a4faf0c344b29460f670283424b8":{
      "scriptId":"u37"},
    "112a4e20a05d4f2b9d3b4be8d8eef4db":{
      "scriptId":"u38"},
    "67eb685fec604c15a302c29ab1e15b2c":{
      "scriptId":"u39"},
    "5b92ee48f1c94717b4e9183f9e3f2615":{
      "scriptId":"u40"},
    "2b95847f443244feb58203691f376680":{
      "scriptId":"u41"},
    "b446451b75794e4dac9cd1e691a63606":{
      "scriptId":"u42"},
    "a6425e7713314a05bb81ba8ddb21ab1d":{
      "scriptId":"u43"},
    "85b320a6ad9745078f1c4c874f7d21b0":{
      "scriptId":"u44"},
    "4140354068d54e93bf4cf07899dc4c0b":{
      "scriptId":"u45"},
    "94c57eaba8094d05b427be14307524cb":{
      "scriptId":"u46"},
    "efc15ac2ee8c4c99b24dd6d9e98fb3ed":{
      "scriptId":"u47"},
    "782a30cb28b8492b93a9c4f8dcb286e7":{
      "scriptId":"u48"},
    "51b4aa4871844fde908efe0dfb942ef5":{
      "scriptId":"u49"},
    "f3c7364b3a7b4979bd2d0034e9ab8efa":{
      "scriptId":"u50"},
    "51d2a9b1a5fa4413b1f4c4714be3f713":{
      "scriptId":"u51"},
    "9376c8d0fee54f068662db17ab660998":{
      "scriptId":"u52"},
    "d955e71e9b664384b30a93bf370c7593":{
      "scriptId":"u53"},
    "342f73c18a5d4606b417feaa6d7c9548":{
      "scriptId":"u54"},
    "aab7f72fcad443b089bc21cfe147b124":{
      "scriptId":"u55"},
    "81486d98db8d464bbb1c5bd99e4f952c":{
      "scriptId":"u56"},
    "88c039b15bee444289743389696a9675":{
      "scriptId":"u57"},
    "b1ead64c797949c2ae0298b74e77e8a1":{
      "scriptId":"u58"},
    "a92f154db1c94411aacc0011124cb7bd":{
      "scriptId":"u59"},
    "9b3c7db3049848d4b9d2d016c5c82f2f":{
      "scriptId":"u60"},
    "25b1e1d4294b4538a0ed5f5493bb3fc8":{
      "scriptId":"u61"}}});