$axure.loadCurrentPage({
  "url":"案例介绍.html",
  "generationDate":new Date(1412900043877.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4c6fe0889e43425c8ab9c77e332ddbc7",
    "type":"Axure:Page",
    "name":"案例介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5e3234fa72d14fae9b89362b902fb56a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":1100,
              "height":894},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfd62146ed1345fe805f195979923d7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":1100,
                  "height":894},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"f141c72cb4e24a73a8e9d70379cca739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":60,
              "y":834},
            "size":{
              "width":1100,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e465b9c6bf049c7adfddaa1616c092d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":60,
                  "y":834},
                "size":{
                  "width":1100,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"bce87b7938b1448286b28cfe32e5ec82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":854},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe7b3ba844994e4aa928477cede7ed3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":854},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d78c3694b29425bbd0bc59172af8761",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":475,
              "y":854},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d424d4614409432dbe9f936f555899ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":854},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fcfa3487540468493e667b6015bf4c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":888},
            "size":{
              "width":230,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd17db1435654ce99b0c02a47b73ff59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":888},
                "size":{
                  "width":230,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e8867af09424e3082a1105d4233a91b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":475,
              "y":888},
            "size":{
              "width":230,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95b34cff34ee44e2991dc2f147c57b22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":888},
                "size":{
                  "width":230,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3558d68c4cd4e40a347e07fb14d33db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":931,
              "y":854},
            "size":{
              "width":84,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0562cb7ce02a4497ab179ac5a5e45ea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":854},
                "size":{
                  "width":84,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53b9dcc3fabf45f3bcbdb163d70f3405",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":931,
              "y":888},
            "size":{
              "width":203,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8e7e2a1963476ca1848309a0dcd731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":888},
                "size":{
                  "width":203,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d329e861c7bd467888cd482beea4dae7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":840,
              "y":854},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82cb70d273b44db7b55cc02583555780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":840,
                  "y":854},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u31.png"}},
{
          "id":"922c0eb3d8a4416b95132e9ad3c3bdaa",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":843},
            "size":{
              "width":10,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u33_line.png"}},
{
          "id":"634c1233fa2f4b55a4ed3a5ba948ec06",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":843},
            "size":{
              "width":10,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u33_line.png"}},
{
          "id":"93fbcd7b297243b28983b177318826a9",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":414},
            "size":{
              "width":120,
              "height":286}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"right",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1b3efa379fe64140a4674295b1ad9bf4",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f23f232e17d1423eac38e2d737a6d2bb",
                  "label":"",
                  "parentDynamicPanel":"93fbcd7b297243b28983b177318826a9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":100,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"96eacfb13a314d4998d37f5e512dea06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"93fbcd7b297243b28983b177318826a9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":100,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u43.png"}},
{
                  "id":"99b10dfc4d374a8db863b5d515f83a64",
                  "label":"",
                  "parentDynamicPanel":"93fbcd7b297243b28983b177318826a9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":10,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40105aecd2154010a181a7298b9ec228",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"93fbcd7b297243b28983b177318826a9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":10,
                          "y":140},
                        "size":{
                          "width":100,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u43.png"}},
{
                  "id":"61d369ff2b3e494894afe8f95b74d0ff",
                  "label":"",
                  "parentDynamicPanel":"93fbcd7b297243b28983b177318826a9",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":42,
                      "y":205},
                    "size":{
                      "width":37,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d42cfe927da48719b7e1738691447bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"93fbcd7b297243b28983b177318826a9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":42,
                          "y":205},
                        "size":{
                          "width":37,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u47.png"}},
{
                  "id":"cb67c0b5045f4610819fae153f5cd097",
                  "label":"",
                  "parentDynamicPanel":"93fbcd7b297243b28983b177318826a9",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":38,
                      "y":69},
                    "size":{
                      "width":45,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39d20646918749d9b8c3ff55e7971e75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"93fbcd7b297243b28983b177318826a9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":38,
                          "y":69},
                        "size":{
                          "width":45,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u49.png"}}]}]},
{
          "id":"e358215f397945749de8b9e3d6c1cf4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":588,
              "y":964},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa7152b7d7ad4c85a21526077fcc14f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":588,
                  "y":964},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6253e95e7c034229b3ccdc75aa6636b4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":133},
            "size":{
              "width":1100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u4_line.png"}},
{
          "id":"40ecbf8bf354449299c6c793b481f243",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":137},
            "size":{
              "width":1100,
              "height":153}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9babd4e270c8441a91b765350f939654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":137},
                "size":{
                  "width":1100,
                  "height":153}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品/u42.png"}},
{
          "id":"1ce0d7e2e83c4d28a35c9397f46030b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "horizontalAlignment":"center",
            "location":{
              "x":243,
              "y":330},
            "size":{
              "width":734,
              "height":423}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36e8edb7310d4763a818fbd3461fbaad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "horizontalAlignment":"center",
                "location":{
                  "x":243,
                  "y":330},
                "size":{
                  "width":734,
                  "height":423}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f0900d1de404c289d0e60e9111ef5cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":100,
              "y":298},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6f4425b6ce444bbba57d2f12e7da94a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":298},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c08908c548b418bb78a7c0e2fcecc1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":552,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"992aa07f84f84825b4d31c101ef408f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":552,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fe7478dc3544600838c0198e697807e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":648,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b5b15e8bc64f91a4af41c7493020e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":648,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品",
                      "target":{
                        "targetType":"page",
                        "url":"产品.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4661e49994574047bf32678deef45ff2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":744,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21bba19030d04628bb8ec9ef875d2642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":744,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 案例",
                      "target":{
                        "targetType":"page",
                        "url":"案例.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e2c0d844cae47e684f6f4f142047b3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":840,
              "y":99},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f491a90e714d48b3b2dc0aea730fc112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":840,
                  "y":99},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 报价",
                      "target":{
                        "targetType":"page",
                        "url":"报价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f65bfeffed9044d797edf402f260fcfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":936,
              "y":99},
            "size":{
              "width":39,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c5ed58ef95243bf99ae8734c1ae3c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":936,
                  "y":99},
                "size":{
                  "width":39,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 FAQ",
                      "target":{
                        "targetType":"page",
                        "url":"faq.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e065ac010f34e94b36f965f63ea1caa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":1034,
              "y":96},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc28171e4284c39a144f6d47d6998d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":1034,
                  "y":96},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u15.png"}},
{
          "id":"5bdc642590784aa18b7859f0510ead6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":86},
            "size":{
              "width":296,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be941a7e926e452bbf6f9f9c0e615398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":86},
                "size":{
                  "width":296,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u76.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5e3234fa72d14fae9b89362b902fb56a":{
      "scriptId":"u0"},
    "bfd62146ed1345fe805f195979923d7b":{
      "scriptId":"u1"},
    "f141c72cb4e24a73a8e9d70379cca739":{
      "scriptId":"u2"},
    "2e465b9c6bf049c7adfddaa1616c092d":{
      "scriptId":"u3"},
    "bce87b7938b1448286b28cfe32e5ec82":{
      "scriptId":"u4"},
    "fe7b3ba844994e4aa928477cede7ed3d":{
      "scriptId":"u5"},
    "5d78c3694b29425bbd0bc59172af8761":{
      "scriptId":"u6"},
    "d424d4614409432dbe9f936f555899ff":{
      "scriptId":"u7"},
    "0fcfa3487540468493e667b6015bf4c3":{
      "scriptId":"u8"},
    "bd17db1435654ce99b0c02a47b73ff59":{
      "scriptId":"u9"},
    "6e8867af09424e3082a1105d4233a91b":{
      "scriptId":"u10"},
    "95b34cff34ee44e2991dc2f147c57b22":{
      "scriptId":"u11"},
    "f3558d68c4cd4e40a347e07fb14d33db":{
      "scriptId":"u12"},
    "0562cb7ce02a4497ab179ac5a5e45ea8":{
      "scriptId":"u13"},
    "53b9dcc3fabf45f3bcbdb163d70f3405":{
      "scriptId":"u14"},
    "0d8e7e2a1963476ca1848309a0dcd731":{
      "scriptId":"u15"},
    "d329e861c7bd467888cd482beea4dae7":{
      "scriptId":"u16"},
    "82cb70d273b44db7b55cc02583555780":{
      "scriptId":"u17"},
    "922c0eb3d8a4416b95132e9ad3c3bdaa":{
      "scriptId":"u18"},
    "634c1233fa2f4b55a4ed3a5ba948ec06":{
      "scriptId":"u19"},
    "93fbcd7b297243b28983b177318826a9":{
      "scriptId":"u20"},
    "f23f232e17d1423eac38e2d737a6d2bb":{
      "scriptId":"u21"},
    "96eacfb13a314d4998d37f5e512dea06":{
      "scriptId":"u22"},
    "99b10dfc4d374a8db863b5d515f83a64":{
      "scriptId":"u23"},
    "40105aecd2154010a181a7298b9ec228":{
      "scriptId":"u24"},
    "61d369ff2b3e494894afe8f95b74d0ff":{
      "scriptId":"u25"},
    "0d42cfe927da48719b7e1738691447bd":{
      "scriptId":"u26"},
    "cb67c0b5045f4610819fae153f5cd097":{
      "scriptId":"u27"},
    "39d20646918749d9b8c3ff55e7971e75":{
      "scriptId":"u28"},
    "e358215f397945749de8b9e3d6c1cf4b":{
      "scriptId":"u29"},
    "fa7152b7d7ad4c85a21526077fcc14f6":{
      "scriptId":"u30"},
    "6253e95e7c034229b3ccdc75aa6636b4":{
      "scriptId":"u31"},
    "40ecbf8bf354449299c6c793b481f243":{
      "scriptId":"u32"},
    "9babd4e270c8441a91b765350f939654":{
      "scriptId":"u33"},
    "1ce0d7e2e83c4d28a35c9397f46030b3":{
      "scriptId":"u34"},
    "36e8edb7310d4763a818fbd3461fbaad":{
      "scriptId":"u35"},
    "6f0900d1de404c289d0e60e9111ef5cd":{
      "scriptId":"u36"},
    "a6f4425b6ce444bbba57d2f12e7da94a":{
      "scriptId":"u37"},
    "2c08908c548b418bb78a7c0e2fcecc1d":{
      "scriptId":"u38"},
    "992aa07f84f84825b4d31c101ef408f8":{
      "scriptId":"u39"},
    "2fe7478dc3544600838c0198e697807e":{
      "scriptId":"u40"},
    "76b5b15e8bc64f91a4af41c7493020e0":{
      "scriptId":"u41"},
    "4661e49994574047bf32678deef45ff2":{
      "scriptId":"u42"},
    "21bba19030d04628bb8ec9ef875d2642":{
      "scriptId":"u43"},
    "7e2c0d844cae47e684f6f4f142047b3e":{
      "scriptId":"u44"},
    "f491a90e714d48b3b2dc0aea730fc112":{
      "scriptId":"u45"},
    "f65bfeffed9044d797edf402f260fcfd":{
      "scriptId":"u46"},
    "4c5ed58ef95243bf99ae8734c1ae3c1c":{
      "scriptId":"u47"},
    "7e065ac010f34e94b36f965f63ea1caa":{
      "scriptId":"u48"},
    "adc28171e4284c39a144f6d47d6998d5":{
      "scriptId":"u49"},
    "5bdc642590784aa18b7859f0510ead6e":{
      "scriptId":"u50"},
    "be941a7e926e452bbf6f9f9c0e615398":{
      "scriptId":"u51"}}});