$axure.loadCurrentPage({
  "url":"structure.html",
  "generationDate":new Date(1428494663707.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a46e280fc8fa4cfa8875978d98f2313b",
    "type":"Axure:Page",
    "name":"Structure",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"56547e74694f4acbade5bfafc0461be8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":130,
              "y":410},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40b4658a47ed4b9c8ac15c5d8cd31f9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":130,
                  "y":410},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/structure/u0.png"}},
{
          "id":"629d92fcd046402bbe027c01d8c6225e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":380,
              "y":410},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15013f6dfce04f89960b67c7f9240bd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":380,
                  "y":410},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人首页-无图片",
                      "target":{
                        "targetType":"page",
                        "url":"个人首页-无图片.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"1f8fe5bb2a724bdcbbe207dde8154cbf",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":690,
              "y":40},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46ad460bf4d44a6c9aaed48faf43052a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":690,
                  "y":40},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"2ade9fc8ac304b488658c7461ffbe5ee",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":690,
              "y":410},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4dab41f891c4b948a3c89c1692b7d15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":690,
                  "y":410},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 正在上传",
                      "target":{
                        "targetType":"page",
                        "url":"正在上传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"14fe03f27dcc4740bad2987ea97551aa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":690,
              "y":681},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b3aafdf26ac4159a3ebef66e3f141df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":690,
                  "y":681},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 图片列表",
                      "target":{
                        "targetType":"page",
                        "url":"图片列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"34cbef209c3c40999671e9e5ea4bfaba",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":870,
              "y":340},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd31b064e67545b2b939a25c08d11991",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":870,
                  "y":340},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"d97c741d9129462a94d0061d6faddac9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":870,
              "y":410},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d8006adda154aea8f3e57799d462ba9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":870,
                  "y":410},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"7ccb6bf9d2c44ac299ac9394ef18821e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":870,
              "y":480},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"473dc49e8493416f9a2f3881eb575a3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":870,
                  "y":480},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"a9c53122575e4ad7b57bbd01cd52bbfa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":870,
              "y":584},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4596a6739ecf4bc4abae3922a12010a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":870,
                  "y":584},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"6405f478474f4dbd832422e5ceac1cfe",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":870,
              "y":681},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c7f135e023f43188781591af9d5e39b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":870,
                  "y":681},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看图片",
                      "target":{
                        "targetType":"page",
                        "url":"查看图片.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"b818fcbb57f1431cb43757925629f28c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1040,
              "y":768},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b342cdbb1ca4beab84d5fe539b758e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1040,
                  "y":768},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"44588f98b80d4d9f93a8d56a314191bb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1040,
              "y":842},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d68f136900d540d99f6876ff1b4d0f45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1040,
                  "y":842},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 复制多张图片链接",
                      "target":{
                        "targetType":"page",
                        "url":"复制多张图片链接.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"366495d7f9b148b097586d436394b8f5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1040,
              "y":916},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c2b63e01461412d998ef4107227c227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1040,
                  "y":916},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"c3dcd684542b4679aa357c8a9ce5da5f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03dc5e02082642918c6936759a3f6403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"57f5c020449d48fcbbaae3067a30ff17",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e22e6f3f5d400a91e360621bd41f61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"91beb21ec116411a8766ec885b184798",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d054ad9d94af4b199b401822e06a3ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"bdd772eb7a334f42b05899c47f2e9d41",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a69b0f7364b74994bee19faafd405188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":40}},
              "adaptiveStyles":{
}}]},
{
          "id":"df51d591f5de40e5a9bc4d6b952bbe42",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c068ef8667aa4e8e839d747d0cdc4743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"4210abef977149f2824aaf030bf7a2b0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b2a0ec9bea847ad8b7b585854335dd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"592c0a66b5054dc8885609bc2480ce6a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c59805a4e82e4e8cadb61e70d77a4027",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"c8aedcec15204e5783af43929fff50e0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f16975141eb2448fb1cb5db2e8136e45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"9d1d5529764049bd95100ffd4201e73a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":711}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582026879d8542df88c18332f5dbb452",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":711}},
              "adaptiveStyles":{
}}]},
{
          "id":"e331e4be20b8471b8b1feae65f29face",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":711}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6377e782ece4a199d755cf47deb0e7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":711}},
              "adaptiveStyles":{
}}]},
{
          "id":"0e03e5bb4c514cd2a77ef47f2099b16f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":400},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff17900586504d72a712043ed0ac7f12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":123,
                  "y":400},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u46.png"}},
{
          "id":"3498223f15a64d56b0484e8efcff060b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":400},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63e517ea3c8b48f593c22af694147bb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":400},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u46.png"}},
{
          "id":"bc37e199ae664af5b98f205e86a38d91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":400},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8222a1d85c40440188a1d7717df4e502",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":400},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u46.png"}},
{
          "id":"6292f65427254d469f07efa7452e835f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":671},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38b109a1f3454809853cf44e2ae10a92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":671},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u46.png"}},
{
          "id":"f4ec2b6eff0f43f195f96689b70e9080",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":861,
              "y":671},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83601b72e3aa47ec8364caf6a07eb5c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":861,
                  "y":671},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u46.png"}},
{
          "id":"da90eb32d40749a299a7217904d2b574",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":870,
              "y":842},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02b9771b8c4c4f92835d8ca81066c12a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":870,
                  "y":842},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 多张选中",
                      "target":{
                        "targetType":"page",
                        "url":"多张选中.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"582244892ec544399296c232ef388716",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":711}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c503d361ae84b0db1d9a8995b351b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":711}},
              "adaptiveStyles":{
}}]},
{
          "id":"e869614a8e514ff6a0032f26375acfb0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":872}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a3faac3c420496e9ff53060b011b7b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":872}},
              "adaptiveStyles":{
}}]},
{
          "id":"d884fe55cfb544c0ab18782b7cf10b22",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":872}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc390c6dfcad469982dfbe720685635a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":872}},
              "adaptiveStyles":{
}}]},
{
          "id":"5faed883fc4b4b7d94c5514692f5f29d",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":872}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6815418d624743159f84bb7c34810f10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":872}},
              "adaptiveStyles":{
}}]},
{
          "id":"3718f94943af41f7a31a0d477b400ace",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":861,
              "y":832},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"369f87f2be0c4ca1a56baf4d1a558639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":861,
                  "y":832},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u46.png"}},
{
          "id":"21ad004e29d54101a69628a7a40d0892",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1040,
              "y":681},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77395b8ce353465bab868ade1c8c0ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1040,
                  "y":681},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"88ae2f0fc5964a159ee8304530d29b86",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":711}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df54732be9454207971c30499cc473dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":711}},
              "adaptiveStyles":{
}}]},
{
          "id":"069d42ca8669447bb7defbabccd32caf",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":690,
              "y":150},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13d9a4dadc334b63a097c35d5c88cadb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":690,
                  "y":150},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"594de22b6a8f4b6a8c4638220be6377f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":690,
              "y":250},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"785fabfbe1c34534b76b25e87d83eeab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":690,
                  "y":250},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 尺寸配置",
                      "target":{
                        "targetType":"page",
                        "url":"尺寸配置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/structure/u2.png"}},
{
          "id":"2f5e4c6366ea4fd69e0c5045eda25219",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0018a0074b414dc09e9500763d351ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"86e2719673a84aea92165ee2cb2f9e58",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56f9263dc01c4f7a83c26536ea64b71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"a02da5168beb43c9978f9230d05b4d06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":240},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6082a5122a40229bc670a39d843663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":240},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u46.png"}},
{
          "id":"532f7d5026ca4366a349114ef60c3855",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":832},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc9532235564418cb3183a2018e5b97d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":832},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u46.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "56547e74694f4acbade5bfafc0461be8":{
      "scriptId":"u0"},
    "40b4658a47ed4b9c8ac15c5d8cd31f9f":{
      "scriptId":"u1"},
    "629d92fcd046402bbe027c01d8c6225e":{
      "scriptId":"u2"},
    "15013f6dfce04f89960b67c7f9240bd9":{
      "scriptId":"u3"},
    "1f8fe5bb2a724bdcbbe207dde8154cbf":{
      "scriptId":"u4"},
    "46ad460bf4d44a6c9aaed48faf43052a":{
      "scriptId":"u5"},
    "2ade9fc8ac304b488658c7461ffbe5ee":{
      "scriptId":"u6"},
    "c4dab41f891c4b948a3c89c1692b7d15":{
      "scriptId":"u7"},
    "14fe03f27dcc4740bad2987ea97551aa":{
      "scriptId":"u8"},
    "5b3aafdf26ac4159a3ebef66e3f141df":{
      "scriptId":"u9"},
    "34cbef209c3c40999671e9e5ea4bfaba":{
      "scriptId":"u10"},
    "cd31b064e67545b2b939a25c08d11991":{
      "scriptId":"u11"},
    "d97c741d9129462a94d0061d6faddac9":{
      "scriptId":"u12"},
    "6d8006adda154aea8f3e57799d462ba9":{
      "scriptId":"u13"},
    "7ccb6bf9d2c44ac299ac9394ef18821e":{
      "scriptId":"u14"},
    "473dc49e8493416f9a2f3881eb575a3d":{
      "scriptId":"u15"},
    "a9c53122575e4ad7b57bbd01cd52bbfa":{
      "scriptId":"u16"},
    "4596a6739ecf4bc4abae3922a12010a1":{
      "scriptId":"u17"},
    "6405f478474f4dbd832422e5ceac1cfe":{
      "scriptId":"u18"},
    "2c7f135e023f43188781591af9d5e39b":{
      "scriptId":"u19"},
    "b818fcbb57f1431cb43757925629f28c":{
      "scriptId":"u20"},
    "5b342cdbb1ca4beab84d5fe539b758e4":{
      "scriptId":"u21"},
    "44588f98b80d4d9f93a8d56a314191bb":{
      "scriptId":"u22"},
    "d68f136900d540d99f6876ff1b4d0f45":{
      "scriptId":"u23"},
    "366495d7f9b148b097586d436394b8f5":{
      "scriptId":"u24"},
    "2c2b63e01461412d998ef4107227c227":{
      "scriptId":"u25"},
    "c3dcd684542b4679aa357c8a9ce5da5f":{
      "scriptId":"u26"},
    "03dc5e02082642918c6936759a3f6403":{
      "scriptId":"u27"},
    "57f5c020449d48fcbbaae3067a30ff17":{
      "scriptId":"u28"},
    "59e22e6f3f5d400a91e360621bd41f61":{
      "scriptId":"u29"},
    "91beb21ec116411a8766ec885b184798":{
      "scriptId":"u30"},
    "d054ad9d94af4b199b401822e06a3ecc":{
      "scriptId":"u31"},
    "bdd772eb7a334f42b05899c47f2e9d41":{
      "scriptId":"u32"},
    "a69b0f7364b74994bee19faafd405188":{
      "scriptId":"u33"},
    "df51d591f5de40e5a9bc4d6b952bbe42":{
      "scriptId":"u34"},
    "c068ef8667aa4e8e839d747d0cdc4743":{
      "scriptId":"u35"},
    "4210abef977149f2824aaf030bf7a2b0":{
      "scriptId":"u36"},
    "0b2a0ec9bea847ad8b7b585854335dd1":{
      "scriptId":"u37"},
    "592c0a66b5054dc8885609bc2480ce6a":{
      "scriptId":"u38"},
    "c59805a4e82e4e8cadb61e70d77a4027":{
      "scriptId":"u39"},
    "c8aedcec15204e5783af43929fff50e0":{
      "scriptId":"u40"},
    "f16975141eb2448fb1cb5db2e8136e45":{
      "scriptId":"u41"},
    "9d1d5529764049bd95100ffd4201e73a":{
      "scriptId":"u42"},
    "582026879d8542df88c18332f5dbb452":{
      "scriptId":"u43"},
    "e331e4be20b8471b8b1feae65f29face":{
      "scriptId":"u44"},
    "b6377e782ece4a199d755cf47deb0e7b":{
      "scriptId":"u45"},
    "0e03e5bb4c514cd2a77ef47f2099b16f":{
      "scriptId":"u46"},
    "ff17900586504d72a712043ed0ac7f12":{
      "scriptId":"u47"},
    "3498223f15a64d56b0484e8efcff060b":{
      "scriptId":"u48"},
    "63e517ea3c8b48f593c22af694147bb6":{
      "scriptId":"u49"},
    "bc37e199ae664af5b98f205e86a38d91":{
      "scriptId":"u50"},
    "8222a1d85c40440188a1d7717df4e502":{
      "scriptId":"u51"},
    "6292f65427254d469f07efa7452e835f":{
      "scriptId":"u52"},
    "38b109a1f3454809853cf44e2ae10a92":{
      "scriptId":"u53"},
    "f4ec2b6eff0f43f195f96689b70e9080":{
      "scriptId":"u54"},
    "83601b72e3aa47ec8364caf6a07eb5c1":{
      "scriptId":"u55"},
    "da90eb32d40749a299a7217904d2b574":{
      "scriptId":"u56"},
    "02b9771b8c4c4f92835d8ca81066c12a":{
      "scriptId":"u57"},
    "582244892ec544399296c232ef388716":{
      "scriptId":"u58"},
    "5c503d361ae84b0db1d9a8995b351b08":{
      "scriptId":"u59"},
    "e869614a8e514ff6a0032f26375acfb0":{
      "scriptId":"u60"},
    "6a3faac3c420496e9ff53060b011b7b0":{
      "scriptId":"u61"},
    "d884fe55cfb544c0ab18782b7cf10b22":{
      "scriptId":"u62"},
    "fc390c6dfcad469982dfbe720685635a":{
      "scriptId":"u63"},
    "5faed883fc4b4b7d94c5514692f5f29d":{
      "scriptId":"u64"},
    "6815418d624743159f84bb7c34810f10":{
      "scriptId":"u65"},
    "3718f94943af41f7a31a0d477b400ace":{
      "scriptId":"u66"},
    "369f87f2be0c4ca1a56baf4d1a558639":{
      "scriptId":"u67"},
    "21ad004e29d54101a69628a7a40d0892":{
      "scriptId":"u68"},
    "77395b8ce353465bab868ade1c8c0ada":{
      "scriptId":"u69"},
    "88ae2f0fc5964a159ee8304530d29b86":{
      "scriptId":"u70"},
    "df54732be9454207971c30499cc473dd":{
      "scriptId":"u71"},
    "069d42ca8669447bb7defbabccd32caf":{
      "scriptId":"u72"},
    "13d9a4dadc334b63a097c35d5c88cadb":{
      "scriptId":"u73"},
    "594de22b6a8f4b6a8c4638220be6377f":{
      "scriptId":"u74"},
    "785fabfbe1c34534b76b25e87d83eeab":{
      "scriptId":"u75"},
    "2f5e4c6366ea4fd69e0c5045eda25219":{
      "scriptId":"u76"},
    "0018a0074b414dc09e9500763d351ce8":{
      "scriptId":"u77"},
    "86e2719673a84aea92165ee2cb2f9e58":{
      "scriptId":"u78"},
    "56f9263dc01c4f7a83c26536ea64b71d":{
      "scriptId":"u79"},
    "a02da5168beb43c9978f9230d05b4d06":{
      "scriptId":"u80"},
    "de6082a5122a40229bc670a39d843663":{
      "scriptId":"u81"},
    "532f7d5026ca4366a349114ef60c3855":{
      "scriptId":"u82"},
    "dc9532235564418cb3183a2018e5b97d":{
      "scriptId":"u83"}}});