$axure.loadCurrentPage({
  "url":"连线题.html",
  "generationDate":new Date(1439662880242.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"75b542264d6f4443851ac02708155a92",
    "type":"Axure:Page",
    "name":"连线题",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"31daebb349644a8bb5aeda94d071330b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":200,
              "y":60},
            "size":{
              "width":934,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83bab9c2d14342a1974f1e6e2bddbfd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "size":{
                  "width":118,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"740756fdfa234317b25b30f924d05f4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "size":{
                      "width":118,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u13.png"}},
{
              "id":"9c7b12b8fa374e8bbac3281abec3de78",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":118,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"baab59fc61f1444c9bbe943f708b0826",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":118,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u17.png"}},
{
              "id":"106a65222ac84e08940ebd41518bf38d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":118,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c542b3faf166451ead0ea0b051887468",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":130},
                    "size":{
                      "width":118,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u13.png"}},
{
              "id":"40c5dfed9ac84a2da98c50f9ae953ead",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":0},
                "size":{
                  "width":816,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc0d1681d9ee4c6b8e1fe87b88880b07",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":0},
                    "size":{
                      "width":816,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u15.png"}},
{
              "id":"230e0977fb774c52823c5427966d9a83",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":50},
                "size":{
                  "width":816,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f419b917bb6454eb4831a9135012a43",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":50},
                    "size":{
                      "width":816,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u19.png"}},
{
              "id":"24f5e3c3957749a98442deb756d10452",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":130},
                "size":{
                  "width":816,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac1ad54e1fb740759235ba45bbac5ba5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":130},
                    "size":{
                      "width":816,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u15.png"}},
{
              "id":"8a325878f0d3453db4b7ba70b8f4d09e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":118,
                  "height":135}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"daa461fd889f41789295fd53fdfdaffb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":118,
                      "height":135}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u25.png"}},
{
              "id":"f76c1803890744c9b4701d8f8d7e3d5e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":180},
                "size":{
                  "width":816,
                  "height":135}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b92671ec721a49eaa12e9477d4fe5246",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":180},
                    "size":{
                      "width":816,
                      "height":135}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u27.png"}},
{
              "id":"8451ac5e59cd4aa4aa6f06b04b6ecf97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":395},
                "size":{
                  "width":118,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aec46b9403ce41ae9aae2bd460b05c02",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":395},
                    "size":{
                      "width":118,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u13.png"}},
{
              "id":"43e77c32f7cf41c7b984ffc898907159",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":395},
                "size":{
                  "width":816,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0d63287dbb04f86b389d5d22ea4f2e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":395},
                    "size":{
                      "width":816,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u15.png"}},
{
              "id":"8d6cc973c67845f5b7f945e9be1071cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":445},
                "size":{
                  "width":118,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4c65f5864e4482fb5e8142ecdbb258e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":445},
                    "size":{
                      "width":118,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u37.png"}},
{
              "id":"be2b45cdb5ad4f268715a1bba57c8eea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":445},
                "size":{
                  "width":816,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1953ded7393f4b66822584fc2bef288f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":445},
                    "size":{
                      "width":816,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u39.png"}},
{
              "id":"3a83935e953c49b7a31f7c705ca8f74a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":315},
                "size":{
                  "width":118,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"646a33e765ee4bc2bf2ccb72bdc46380",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":315},
                    "size":{
                      "width":118,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u17.png"}},
{
              "id":"b4eec5195fb04b7390c859df91ac4900",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":315},
                "size":{
                  "width":816,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d92fa88a7c74e9ba0761bdb3a0e7028",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":315},
                    "size":{
                      "width":816,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u19.png"}}]},
{
          "id":"9749e3bd02a7487492d5f0b81ac49bea",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":120},
            "size":{
              "width":530,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"79ec4c8d8f7c4381b184a02c8801645c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":204},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"75c89a47eb584a9287a6aff5eaefc30a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":466},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"79f3be381c9b48d4a0d9942ccb303d84",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":523},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e47888ecd274c578816216d35d089c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":330,
                  "y":523},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"a37c1ec6d4f84c04b95bc8e193460478",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":410,
              "y":523},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad28d42ed4724bb7a1266ac209adc40c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":410,
                  "y":523},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"def8c8c58df64b9999437c764c3f95b2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":320,
              "y":584},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 试题列表",
                      "target":{
                        "targetType":"page",
                        "url":"试题列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9229276d0fa248e5ad3ae0ad19fe2b46",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":450,
              "y":584},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 预览",
                      "target":{
                        "targetType":"page",
                        "url":"预览.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"b0a511a1730f479b945d368493eba6fc",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":69},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1<br> (If 选中项于 This 等于 &quot;多选题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"多选题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 多选题",
                      "target":{
                        "targetType":"page",
                        "url":"多选题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2<br> (Else If 选中项于 This 等于 &quot;判断题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"判断题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 判断题",
                      "target":{
                        "targetType":"page",
                        "url":"判断题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 3<br> (Else If 选中项于 This 等于 &quot;论述题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"论述题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 论述题",
                      "target":{
                        "targetType":"page",
                        "url":"论述题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 4<br> (Else If 选中项于 This 等于 &quot;连线题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"连线题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 连线题",
                      "target":{
                        "targetType":"page",
                        "url":"连线题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 5<br> (Else If 选中项于 This 等于 &quot;填空题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"填空题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 填空题",
                      "target":{
                        "targetType":"page",
                        "url":"填空题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 6<br> (Else If 选中项于 This 等于 &quot;单选题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"单选题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加考题 - 单选题",
                      "target":{
                        "targetType":"page",
                        "url":"添加考题_-_单选题.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"ad12ceb48c3a4678be1e3d11c8d2918e",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":386},
            "size":{
              "width":530,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"7c0005bad133404fb94e5ca0f243eb92",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":254},
            "size":{
              "width":260,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0d5a76de8d7c4d91b67f7459f2cfa791",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":600,
              "y":259},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"073b8cdc74d641088d2d8016092267f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":600,
                  "y":259},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0bb51fe071f54f74a4ef3640687facba",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":293},
            "size":{
              "width":260,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"45ec38843e7a46e6ab18c8065be17a24",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":600,
              "y":298},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eb21efd91004105a8defca29726eecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":600,
                  "y":298},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ffe9398d6ab843a48c6cf8e61a0d04ee",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":334},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f8930bf115bf45d3b854226bedf56fe8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":730,
              "y":254},
            "size":{
              "width":260,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"098d809dabf841bca6829961dbbbb777",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":707,
              "y":258},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48487a671dae4763a1cc007d6fb75871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":707,
                  "y":258},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e36fce2faa284a0092d53eb0d015c278",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":730,
              "y":293},
            "size":{
              "width":260,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"97a3fa93c28f497db862d67f7d9f0423",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":707,
              "y":297},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"127e20e1a2664920a6c6bcb579dfd39a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":707,
                  "y":297},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bc7a0059746b4f658113ae3c7552449c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":570,
              "y":340},
            "size":{
              "width":131,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"708789d85dd5440d9ca59a3b1255c5c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":340},
                "size":{
                  "width":131,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75bb4d4ca8d843768386c8db9dd0aa94",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":450,
              "y":334},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8c270ab2ddbd4f9d86d4c501474f5d1a",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":25,
              "y":61},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9068d12c970a40778e1c1ea18f5b15ed",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"746934c4f1f54256961d3b4480722b02",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"700",
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f4718d457bc04fa0b5c02753e8df5cbb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontWeight":"700",
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a1aab2ee3aa04a9daa7213aaed148eb6",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a122f6505d8640869cc66cb079453cdd",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"54c33f998fa34e6398054ba19ae2772f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 试题列表",
                              "target":{
                                "targetType":"page",
                                "url":"试题列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"a122f6505d8640869cc66cb079453cdd"},
{
                  "id":"8239796a076747c397d6b329f288148f",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "stateStyles":{
                      "selected":{
                        "fontName":"'Applied Font Regular', 'Applied Font'"}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c86c3704fea4980a25a58f45eaee3c3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "stateStyles":{
                          "selected":{
                            "fontName":"'Applied Font Regular', 'Applied Font'"}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/试题列表/u151.png",
                    "selected~":"images/试题列表/u151_selected.png"}},
{
                  "id":"9c0fd115ae354573ab3a3ecefb27de7e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"700",
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da4cb8374f6e4b8ab3e8054e1326cfca",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontWeight":"700",
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"927cf9e8e32d4e20ad69804a69c62a49",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Bold', 'Applied Font'",
                            "fontWeight":"700",
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 添加考题 - 单选题",
                              "target":{
                                "targetType":"page",
                                "url":"添加考题_-_单选题.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"da4cb8374f6e4b8ab3e8054e1326cfca"}],
              "buttonShapeId":"746934c4f1f54256961d3b4480722b02"}]}]}},
  "masters":{
},
  "objectPaths":{
    "31daebb349644a8bb5aeda94d071330b":{
      "scriptId":"u0"},
    "83bab9c2d14342a1974f1e6e2bddbfd4":{
      "scriptId":"u1"},
    "740756fdfa234317b25b30f924d05f4a":{
      "scriptId":"u2"},
    "40c5dfed9ac84a2da98c50f9ae953ead":{
      "scriptId":"u3"},
    "cc0d1681d9ee4c6b8e1fe87b88880b07":{
      "scriptId":"u4"},
    "9c7b12b8fa374e8bbac3281abec3de78":{
      "scriptId":"u5"},
    "baab59fc61f1444c9bbe943f708b0826":{
      "scriptId":"u6"},
    "230e0977fb774c52823c5427966d9a83":{
      "scriptId":"u7"},
    "4f419b917bb6454eb4831a9135012a43":{
      "scriptId":"u8"},
    "106a65222ac84e08940ebd41518bf38d":{
      "scriptId":"u9"},
    "c542b3faf166451ead0ea0b051887468":{
      "scriptId":"u10"},
    "24f5e3c3957749a98442deb756d10452":{
      "scriptId":"u11"},
    "ac1ad54e1fb740759235ba45bbac5ba5":{
      "scriptId":"u12"},
    "8a325878f0d3453db4b7ba70b8f4d09e":{
      "scriptId":"u13"},
    "daa461fd889f41789295fd53fdfdaffb":{
      "scriptId":"u14"},
    "f76c1803890744c9b4701d8f8d7e3d5e":{
      "scriptId":"u15"},
    "b92671ec721a49eaa12e9477d4fe5246":{
      "scriptId":"u16"},
    "3a83935e953c49b7a31f7c705ca8f74a":{
      "scriptId":"u17"},
    "646a33e765ee4bc2bf2ccb72bdc46380":{
      "scriptId":"u18"},
    "b4eec5195fb04b7390c859df91ac4900":{
      "scriptId":"u19"},
    "6d92fa88a7c74e9ba0761bdb3a0e7028":{
      "scriptId":"u20"},
    "8451ac5e59cd4aa4aa6f06b04b6ecf97":{
      "scriptId":"u21"},
    "aec46b9403ce41ae9aae2bd460b05c02":{
      "scriptId":"u22"},
    "43e77c32f7cf41c7b984ffc898907159":{
      "scriptId":"u23"},
    "f0d63287dbb04f86b389d5d22ea4f2e7":{
      "scriptId":"u24"},
    "8d6cc973c67845f5b7f945e9be1071cb":{
      "scriptId":"u25"},
    "f4c65f5864e4482fb5e8142ecdbb258e":{
      "scriptId":"u26"},
    "be2b45cdb5ad4f268715a1bba57c8eea":{
      "scriptId":"u27"},
    "1953ded7393f4b66822584fc2bef288f":{
      "scriptId":"u28"},
    "9749e3bd02a7487492d5f0b81ac49bea":{
      "scriptId":"u29"},
    "79ec4c8d8f7c4381b184a02c8801645c":{
      "scriptId":"u30"},
    "75c89a47eb584a9287a6aff5eaefc30a":{
      "scriptId":"u31"},
    "79f3be381c9b48d4a0d9942ccb303d84":{
      "scriptId":"u32"},
    "2e47888ecd274c578816216d35d089c0":{
      "scriptId":"u33"},
    "a37c1ec6d4f84c04b95bc8e193460478":{
      "scriptId":"u34"},
    "ad28d42ed4724bb7a1266ac209adc40c":{
      "scriptId":"u35"},
    "def8c8c58df64b9999437c764c3f95b2":{
      "scriptId":"u36"},
    "9229276d0fa248e5ad3ae0ad19fe2b46":{
      "scriptId":"u37"},
    "b0a511a1730f479b945d368493eba6fc":{
      "scriptId":"u38"},
    "ad12ceb48c3a4678be1e3d11c8d2918e":{
      "scriptId":"u39"},
    "7c0005bad133404fb94e5ca0f243eb92":{
      "scriptId":"u40"},
    "0d5a76de8d7c4d91b67f7459f2cfa791":{
      "scriptId":"u41"},
    "073b8cdc74d641088d2d8016092267f5":{
      "scriptId":"u42"},
    "0bb51fe071f54f74a4ef3640687facba":{
      "scriptId":"u43"},
    "45ec38843e7a46e6ab18c8065be17a24":{
      "scriptId":"u44"},
    "5eb21efd91004105a8defca29726eecc":{
      "scriptId":"u45"},
    "ffe9398d6ab843a48c6cf8e61a0d04ee":{
      "scriptId":"u46"},
    "f8930bf115bf45d3b854226bedf56fe8":{
      "scriptId":"u47"},
    "098d809dabf841bca6829961dbbbb777":{
      "scriptId":"u48"},
    "48487a671dae4763a1cc007d6fb75871":{
      "scriptId":"u49"},
    "e36fce2faa284a0092d53eb0d015c278":{
      "scriptId":"u50"},
    "97a3fa93c28f497db862d67f7d9f0423":{
      "scriptId":"u51"},
    "127e20e1a2664920a6c6bcb579dfd39a":{
      "scriptId":"u52"},
    "bc7a0059746b4f658113ae3c7552449c":{
      "scriptId":"u53"},
    "708789d85dd5440d9ca59a3b1255c5c0":{
      "scriptId":"u54"},
    "75bb4d4ca8d843768386c8db9dd0aa94":{
      "scriptId":"u55"},
    "8c270ab2ddbd4f9d86d4c501474f5d1a":{
      "scriptId":"u56"},
    "9068d12c970a40778e1c1ea18f5b15ed":{
      "scriptId":"u57"},
    "8239796a076747c397d6b329f288148f":{
      "scriptId":"u58"},
    "2c86c3704fea4980a25a58f45eaee3c3":{
      "scriptId":"u59"},
    "746934c4f1f54256961d3b4480722b02":{
      "scriptId":"u60"},
    "f4718d457bc04fa0b5c02753e8df5cbb":{
      "scriptId":"u61"},
    "a1aab2ee3aa04a9daa7213aaed148eb6":{
      "scriptId":"u62"},
    "a122f6505d8640869cc66cb079453cdd":{
      "scriptId":"u63"},
    "54c33f998fa34e6398054ba19ae2772f":{
      "scriptId":"u64"},
    "9c0fd115ae354573ab3a3ecefb27de7e":{
      "scriptId":"u65"},
    "da4cb8374f6e4b8ab3e8054e1326cfca":{
      "scriptId":"u66"},
    "927cf9e8e32d4e20ad69804a69c62a49":{
      "scriptId":"u67"}}});