$axure.loadCurrentPage({
  "url":"添加考题_-_单选题.html",
  "generationDate":new Date(1439662879614.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"61368edd62ad40838f69f20cdf469694",
    "type":"Axure:Page",
    "name":"添加考题 - 单选题",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f02650f35c814d8fbf5faceb73a36c25",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":25,
              "y":61},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcf1e376cccf40e0bacb0dfb263b66f8",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f731ec053e794ed39379273cd556f3e9",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"700",
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"127c4610275d415599fa1de881cd3750",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontWeight":"700",
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f3ef3a76b2f4a4a8b0180a893826d8e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"013845bb74cf46968c408d12eb70ccf8",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"029e8fd7a10d42f2b37355eb49e02d6b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 试题列表",
                              "target":{
                                "targetType":"page",
                                "url":"试题列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"013845bb74cf46968c408d12eb70ccf8"},
{
                  "id":"83635a22a4504cc290425182ccd781d4",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "stateStyles":{
                      "selected":{
                        "fontName":"'Applied Font Regular', 'Applied Font'"}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6a4a66195ac4990bbcadcd8045f65db",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "stateStyles":{
                          "selected":{
                            "fontName":"'Applied Font Regular', 'Applied Font'"}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/试题列表/u151.png",
                    "selected~":"images/试题列表/u151_selected.png"}},
{
                  "id":"2b192a781c8940fc8cdc710aa5df40ac",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"700",
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"36897270a00149dbb2ef8826c888adf1",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontWeight":"700",
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5568964e1dda40a1b4056608a537ac5d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Bold', 'Applied Font'",
                            "fontWeight":"700",
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 添加考题 - 单选题",
                              "target":{
                                "targetType":"page",
                                "url":"添加考题_-_单选题.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"36897270a00149dbb2ef8826c888adf1"}],
              "buttonShapeId":"f731ec053e794ed39379273cd556f3e9"}]},
{
          "id":"d7dd61dd51b9471a97a1cb16c8307da4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":200,
              "y":60},
            "size":{
              "width":934,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78f66ee8113d4a97bfa9fd6e78cf21f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "size":{
                  "width":118,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1949c1ee722e41d5a45f7768e667a221",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "size":{
                      "width":118,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u13.png"}},
{
              "id":"325f27f109f74332bf47dfd142810287",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":118,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c2578d956da4edd833ebd0d45a34467",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":118,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u17.png"}},
{
              "id":"e64a8a42b70d4e03bee7f5a458785b9f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":118,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f93c9855aafd41f3a53ff4c0b19a7c67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":130},
                    "size":{
                      "width":118,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u13.png"}},
{
              "id":"fbcfe1c6f0cc478e8398fc847b284d5d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":0},
                "size":{
                  "width":816,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fbfc7d093da7471ca2e512ceebd4dddb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":0},
                    "size":{
                      "width":816,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u15.png"}},
{
              "id":"7b9a34be00d247a29cd2a166464d32cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":50},
                "size":{
                  "width":816,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1401763736345b6a60cb5f171a9c20c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":50},
                    "size":{
                      "width":816,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u19.png"}},
{
              "id":"8f7a60d5e3f14a1fbdc263bbda2266d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":130},
                "size":{
                  "width":816,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbe4d1da11e34d76ac87d8ff65355834",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":130},
                    "size":{
                      "width":816,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u15.png"}},
{
              "id":"7f3e4cdc278643159078e4d9100c8f50",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":118,
                  "height":135}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"14437e5a07f54012b13f3cbabb381628",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":118,
                      "height":135}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u25.png"}},
{
              "id":"59a706f311d74f37b8653c590cabe89e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":180},
                "size":{
                  "width":816,
                  "height":135}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0479083cb6f64e11861371361552e76a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":180},
                    "size":{
                      "width":816,
                      "height":135}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u27.png"}},
{
              "id":"9e7f2caa97244b62a67c56cc2a5ae708",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":395},
                "size":{
                  "width":118,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c11c0888e1348acbb769844f0af12c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":395},
                    "size":{
                      "width":118,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u13.png"}},
{
              "id":"7a471b95187e41f7b394877e9a395ffe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":395},
                "size":{
                  "width":816,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55f3ca7db4644acbaa012a9f908bb640",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":395},
                    "size":{
                      "width":816,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u15.png"}},
{
              "id":"c58f374359124111893d22210b3a4dc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":445},
                "size":{
                  "width":118,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3e1135551ef4868847aeb3bdf9a9893",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":445},
                    "size":{
                      "width":118,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u37.png"}},
{
              "id":"c4d2942e881f4545a544aefe285a9fc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":445},
                "size":{
                  "width":816,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3923f4e3c26c4d079b32635855204bda",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":445},
                    "size":{
                      "width":816,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u39.png"}},
{
              "id":"b510fd4f6b5441f982991e4c05954dee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":0,
                  "y":315},
                "size":{
                  "width":118,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c04d8099af840cca6d094141f9adb9a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":0,
                      "y":315},
                    "size":{
                      "width":118,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u17.png"}},
{
              "id":"e5c9b85a32244c5d9de275b99d2d4da1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":118,
                  "y":315},
                "size":{
                  "width":816,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3afe2d4aa585454caa5cc0243a2657b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "paddingTop":"10",
                    "paddingBottom":"10",
                    "location":{
                      "x":118,
                      "y":315},
                    "size":{
                      "width":816,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加考题_-_单选题/u19.png"}}]},
{
          "id":"3cd7057869504763b53418d3f5939733",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":69},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1<br> (If 选中项于 This 等于 &quot;多选题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"多选题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 多选题",
                      "target":{
                        "targetType":"page",
                        "url":"多选题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2<br> (Else If 选中项于 This 等于 &quot;判断题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"判断题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 判断题",
                      "target":{
                        "targetType":"page",
                        "url":"判断题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 3<br> (Else If 选中项于 This 等于 &quot;论述题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"论述题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 论述题",
                      "target":{
                        "targetType":"page",
                        "url":"论述题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 4<br> (Else If 选中项于 This 等于 &quot;连线题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"连线题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 连线题",
                      "target":{
                        "targetType":"page",
                        "url":"连线题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 5<br> (Else If 选中项于 This 等于 &quot;填空题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"填空题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 填空题",
                      "target":{
                        "targetType":"page",
                        "url":"填空题.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 6<br> (Else If 选中项于 This 等于 &quot;单选题&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"单选题",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加考题 - 单选题",
                      "target":{
                        "targetType":"page",
                        "url":"添加考题_-_单选题.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"37c9aad430124ebfbae1360c3658900b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":120},
            "size":{
              "width":530,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"ab422ffe105e4547b158fa69d567617d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":204},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1404ae25e5814808b0792d5fcbf6dd82",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":259},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd98b9898e664e1dbcc97a99f1d5ad2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":330,
                  "y":259},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"aaba0ef0be294eef935d9a93663b6644",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":360,
              "y":255},
            "size":{
              "width":500,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a87be9f11b474206bf60bd5dd10c7330",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":294},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57afa6f7a3794e2a93a004b2e2946269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":330,
                  "y":294},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"28811769a20947fd893fdcf3dcc43b21",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":360,
              "y":290},
            "size":{
              "width":500,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f39362116dc943798f864cbfca5f779c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":334},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2f151762f6b049a7837b4e454333c4e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":440,
              "y":337},
            "size":{
              "width":131,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2c06de7a3504f468fbe2ccdc39d2ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":337},
                "size":{
                  "width":131,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e9df277b09e47aea8c9d4aa6de16b2e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":466},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"507139fb7bd44d269ee5c14cf69ab4e7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":523},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa91aac826d94c87ba8f2e96c4b87781",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":330,
                  "y":523},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"9c3d22832ff944a5a5bb9e70da1f2736",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":410,
              "y":523},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1be5ed9a0f594f08a0eca2cf15928979",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":410,
                  "y":523},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"6f65ff5e555d4e1bb9731c0e00d532ff",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":320,
              "y":594},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 试题列表",
                      "target":{
                        "targetType":"page",
                        "url":"试题列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bbbb18613a494a78903da07b5e84d329",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":450,
              "y":594},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 预览",
                      "target":{
                        "targetType":"page",
                        "url":"预览.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"210af85697fc45489c47d27c828f55fe",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":386},
            "size":{
              "width":530,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"45cbed39c93d4f35871e108e0a97fdf1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":527.5},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/添加考题_-_单选题/u61_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加考题_-_单选题/u61_line.png"}},
{
          "id":"0822940eda3a4aabbffa2117add9542d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":1170,
              "y":510},
            "size":{
              "width":200,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79e1464d830b4abba653f6dbcfc0581f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":1170,
                  "y":510},
                "size":{
                  "width":200,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加考题_-_单选题/u62.png"}},
{
          "id":"a5c94b78e7634577aac5c46c661b5ae0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":212},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/添加考题_-_单选题/u61_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加考题_-_单选题/u61_line.png"}},
{
          "id":"2b032f7967c14e49bf074e7677e25a7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":1170,
              "y":194},
            "size":{
              "width":200,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3650e84de3eb4b72a235e7a6c49a6790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":1170,
                  "y":194},
                "size":{
                  "width":200,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加考题_-_单选题/u62.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f02650f35c814d8fbf5faceb73a36c25":{
      "scriptId":"u0"},
    "fcf1e376cccf40e0bacb0dfb263b66f8":{
      "scriptId":"u1"},
    "83635a22a4504cc290425182ccd781d4":{
      "scriptId":"u2"},
    "f6a4a66195ac4990bbcadcd8045f65db":{
      "scriptId":"u3"},
    "f731ec053e794ed39379273cd556f3e9":{
      "scriptId":"u4"},
    "127c4610275d415599fa1de881cd3750":{
      "scriptId":"u5"},
    "3f3ef3a76b2f4a4a8b0180a893826d8e":{
      "scriptId":"u6"},
    "013845bb74cf46968c408d12eb70ccf8":{
      "scriptId":"u7"},
    "029e8fd7a10d42f2b37355eb49e02d6b":{
      "scriptId":"u8"},
    "2b192a781c8940fc8cdc710aa5df40ac":{
      "scriptId":"u9"},
    "36897270a00149dbb2ef8826c888adf1":{
      "scriptId":"u10"},
    "5568964e1dda40a1b4056608a537ac5d":{
      "scriptId":"u11"},
    "d7dd61dd51b9471a97a1cb16c8307da4":{
      "scriptId":"u12"},
    "78f66ee8113d4a97bfa9fd6e78cf21f4":{
      "scriptId":"u13"},
    "1949c1ee722e41d5a45f7768e667a221":{
      "scriptId":"u14"},
    "fbcfe1c6f0cc478e8398fc847b284d5d":{
      "scriptId":"u15"},
    "fbfc7d093da7471ca2e512ceebd4dddb":{
      "scriptId":"u16"},
    "325f27f109f74332bf47dfd142810287":{
      "scriptId":"u17"},
    "5c2578d956da4edd833ebd0d45a34467":{
      "scriptId":"u18"},
    "7b9a34be00d247a29cd2a166464d32cc":{
      "scriptId":"u19"},
    "b1401763736345b6a60cb5f171a9c20c":{
      "scriptId":"u20"},
    "e64a8a42b70d4e03bee7f5a458785b9f":{
      "scriptId":"u21"},
    "f93c9855aafd41f3a53ff4c0b19a7c67":{
      "scriptId":"u22"},
    "8f7a60d5e3f14a1fbdc263bbda2266d9":{
      "scriptId":"u23"},
    "cbe4d1da11e34d76ac87d8ff65355834":{
      "scriptId":"u24"},
    "7f3e4cdc278643159078e4d9100c8f50":{
      "scriptId":"u25"},
    "14437e5a07f54012b13f3cbabb381628":{
      "scriptId":"u26"},
    "59a706f311d74f37b8653c590cabe89e":{
      "scriptId":"u27"},
    "0479083cb6f64e11861371361552e76a":{
      "scriptId":"u28"},
    "b510fd4f6b5441f982991e4c05954dee":{
      "scriptId":"u29"},
    "2c04d8099af840cca6d094141f9adb9a":{
      "scriptId":"u30"},
    "e5c9b85a32244c5d9de275b99d2d4da1":{
      "scriptId":"u31"},
    "3afe2d4aa585454caa5cc0243a2657b8":{
      "scriptId":"u32"},
    "9e7f2caa97244b62a67c56cc2a5ae708":{
      "scriptId":"u33"},
    "1c11c0888e1348acbb769844f0af12c5":{
      "scriptId":"u34"},
    "7a471b95187e41f7b394877e9a395ffe":{
      "scriptId":"u35"},
    "55f3ca7db4644acbaa012a9f908bb640":{
      "scriptId":"u36"},
    "c58f374359124111893d22210b3a4dc7":{
      "scriptId":"u37"},
    "c3e1135551ef4868847aeb3bdf9a9893":{
      "scriptId":"u38"},
    "c4d2942e881f4545a544aefe285a9fc7":{
      "scriptId":"u39"},
    "3923f4e3c26c4d079b32635855204bda":{
      "scriptId":"u40"},
    "3cd7057869504763b53418d3f5939733":{
      "scriptId":"u41"},
    "37c9aad430124ebfbae1360c3658900b":{
      "scriptId":"u42"},
    "ab422ffe105e4547b158fa69d567617d":{
      "scriptId":"u43"},
    "1404ae25e5814808b0792d5fcbf6dd82":{
      "scriptId":"u44"},
    "fd98b9898e664e1dbcc97a99f1d5ad2c":{
      "scriptId":"u45"},
    "aaba0ef0be294eef935d9a93663b6644":{
      "scriptId":"u46"},
    "a87be9f11b474206bf60bd5dd10c7330":{
      "scriptId":"u47"},
    "57afa6f7a3794e2a93a004b2e2946269":{
      "scriptId":"u48"},
    "28811769a20947fd893fdcf3dcc43b21":{
      "scriptId":"u49"},
    "f39362116dc943798f864cbfca5f779c":{
      "scriptId":"u50"},
    "2f151762f6b049a7837b4e454333c4e8":{
      "scriptId":"u51"},
    "f2c06de7a3504f468fbe2ccdc39d2ad1":{
      "scriptId":"u52"},
    "5e9df277b09e47aea8c9d4aa6de16b2e":{
      "scriptId":"u53"},
    "507139fb7bd44d269ee5c14cf69ab4e7":{
      "scriptId":"u54"},
    "fa91aac826d94c87ba8f2e96c4b87781":{
      "scriptId":"u55"},
    "9c3d22832ff944a5a5bb9e70da1f2736":{
      "scriptId":"u56"},
    "1be5ed9a0f594f08a0eca2cf15928979":{
      "scriptId":"u57"},
    "6f65ff5e555d4e1bb9731c0e00d532ff":{
      "scriptId":"u58"},
    "bbbb18613a494a78903da07b5e84d329":{
      "scriptId":"u59"},
    "210af85697fc45489c47d27c828f55fe":{
      "scriptId":"u60"},
    "45cbed39c93d4f35871e108e0a97fdf1":{
      "scriptId":"u61"},
    "0822940eda3a4aabbffa2117add9542d":{
      "scriptId":"u62"},
    "79e1464d830b4abba653f6dbcfc0581f":{
      "scriptId":"u63"},
    "a5c94b78e7634577aac5c46c661b5ae0":{
      "scriptId":"u64"},
    "2b032f7967c14e49bf074e7677e25a7c":{
      "scriptId":"u65"},
    "3650e84de3eb4b72a235e7a6c49a6790":{
      "scriptId":"u66"}}});