$axure.loadCurrentPage({
  "url":"查看试卷（后台）.html",
  "generationDate":new Date(1444085356657.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c25848a4460043919d8e2f576554f2c1",
    "type":"Axure:Page",
    "name":"查看试卷（后台）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c54dc01c4724affbf862b92512b363b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":310},
            "size":{
              "width":260,
              "height":175},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98137117ee6d48f98add7623f1f13d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":310},
                "size":{
                  "width":260,
                  "height":175},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看试卷（后台）/u0.png"}},
{
          "id":"5f0355b66d5c4b2bb6b0e7a698d3ca44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":20},
            "size":{
              "width":260,
              "height":120},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18046f6c5f7e4d52a3bd2b95926c25cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":20},
                "size":{
                  "width":260,
                  "height":120},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在线考试/u2.png"}},
{
          "id":"24d1dde79f5743ed97072321573ae9af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"22px",
            "location":{
              "x":175,
              "y":36},
            "size":{
              "width":85,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01b191d8b0ea4ed8a1b172ea54eaa285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"22px",
                "location":{
                  "x":175,
                  "y":36},
                "size":{
                  "width":85,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48ca1507882c49f7b5d16247789d54a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":34},
            "size":{
              "width":70,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04dd0351345641f2b710a3e863be4315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":34},
                "size":{
                  "width":70,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在线考试/u6.png"}},
{
          "id":"5e000302076e40a3a8d4e8b67ffc0026",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":321},
            "size":{
              "width":240,
              "height":30},
            "linePattern":"none",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7d35eb1ed814d33bfc1cf85df84b941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":321},
                "size":{
                  "width":240,
                  "height":30},
                "linePattern":"none",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在线考试/u9.png"}},
{
          "id":"08591a368f5f4643aacf1c92a8455ace",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":20},
            "size":{
              "width":950,
              "height":1450},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b70d858a89784ff4905efd1635163e5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":20},
                "size":{
                  "width":950,
                  "height":1450},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看试卷（后台）/u10.png"}},
{
          "id":"7988176768284f00ad7db3c23821ee84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":60,
              "y":150},
            "size":{
              "width":260,
              "height":90},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ffe42f28b346fea9af003977894b10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":60,
                  "y":150},
                "size":{
                  "width":260,
                  "height":90},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/阅卷页（操作栏在左侧）/u80.png"}},
{
          "id":"dc1443531222499288be58b19cc12ee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":36},
            "size":{
              "width":145,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae40d18bb90f4b8eb465ad6e41a1733e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":831,
                  "y":36},
                "size":{
                  "width":145,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9a146e1172f4d71b00b867c4c1f817e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":734,
              "y":92},
            "size":{
              "width":128,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7fab89e91c949ed8f862578d35bb540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":734,
                  "y":92},
                "size":{
                  "width":128,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f68fa52a3e9448eeb5e773ed8694a7b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":930,
              "y":92},
            "size":{
              "width":144,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ba07be92fff462d8ce2e13fda858553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":930,
                  "y":92},
                "size":{
                  "width":144,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54ff7210a825414887adeb7da0ef0fc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":166},
            "size":{
              "width":246,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ade4b6f905a945419e75549eeca47086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":166},
                "size":{
                  "width":246,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf6b987567604227853bfede4f7e82fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":205},
            "size":{
              "width":767,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf5594fefe24ecfaed675a87bddb60c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":205},
                "size":{
                  "width":767,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30e4668e3f9b4eb9a3677c1b4f35220b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":450,
              "y":259},
            "size":{
              "width":220,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cdb7e35b272455daedad338c1a2641b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":450,
                  "y":259},
                "size":{
                  "width":220,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"d54fff499faa4c7c921979ab0a64e8d3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "disabled":true,
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":450,
              "y":291},
            "size":{
              "width":220,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eae46a21b5e4872b36279777a437da8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":450,
                  "y":291},
                "size":{
                  "width":220,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"a64ad29342ef44e2a5d104eea53c71b4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "disabled":true,
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":450,
              "y":323},
            "size":{
              "width":220,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d71a8c09da4b405aab1db6da8eaff8c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":450,
                  "y":323},
                "size":{
                  "width":220,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"ba0c85c427444d10bc2ddcc47d3b269d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "disabled":true,
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":450,
              "y":355},
            "size":{
              "width":220,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da8ca65f6e374ab1a02052e359ae9da4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":450,
                  "y":355},
                "size":{
                  "width":220,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"3a803643c1d64c97a164fb80bc41c270",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":414},
            "size":{
              "width":237,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0af8a7f1706e49959d707546009d7bea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":414},
                "size":{
                  "width":237,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56405802bceb4ff7996dd4d94c80248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":453},
            "size":{
              "width":351,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6452260cea0e4903b617bd5f4e5ddf0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":453},
                "size":{
                  "width":351,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c0fd44e1e114e33a0bb06f8c2512545",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":510},
            "size":{
              "width":341,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b6302d88c7f4daaa522314f553f105f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":510},
                "size":{
                  "width":341,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"3cea042df12446ea935eb278db5aa13a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":539},
            "size":{
              "width":341,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c04ab476dc8743b0bd7fb074c19c00aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":539},
                "size":{
                  "width":341,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"e41336e462fb4c97afc55fe07cdecffb",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":568},
            "size":{
              "width":341,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d45de312f878431a8c853900d5d83f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":568},
                "size":{
                  "width":341,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"a360228c7d1747e4a315fb8cdc3e0413",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":597},
            "size":{
              "width":341,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ffb6467c5614ef28eec6c8deb4a0553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":597},
                "size":{
                  "width":341,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"7592c2235dc54fcd9d65df8e4e08aa3a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":205},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"893440d788974036bd19eb8c00cc1da8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":644},
            "size":{
              "width":237,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54b07fb36ed24133977784e1ab65eb21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":644},
                "size":{
                  "width":237,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"156170eb855c4abdbef41ef18cdf86a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":686},
            "size":{
              "width":152,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b158df66f1346bc98312bfe3e621b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":686},
                "size":{
                  "width":152,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcd7f7e98ab0457480cf287b37169581",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":820},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c628f653ff0c49e6bd0c7c322bc049ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":820},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48104bcf77924207ad3690fcd30b622e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":857},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31f20d55ea914a22af4aa413ff4156e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":857},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2aec2a075cf4436fb086349adc44a042",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":894},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee0016219d7646de90f838aa74bfcc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":894},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7760702fb40e4cdc8ed35ab58d31c002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":930},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f20a6bfa35a4f518f5ae3f795a971e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":930},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ecaaab6bf624520b8ddd3391cdcf245",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":967},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5460093626884db0b3a1c8d92382b62d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":967},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b4e9b153de4435abd3854f575b3bb99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":820},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beb0d474a281434abbc445ede93fcd04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":820},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f78f12f1fb240d1a2ac19a8cb1d6acd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":858},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f586fe35fcc4ed5a56c907c78acb6ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":858},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"744e236e7d9d4583a53404719d1c694c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":894},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"966be0c83c0345109f531c0263700f37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":894},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bb86d6bfc3646b8bfbe73f4b0c682e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":930},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ae585b8dc48433b83e4a3ff4e303b03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":930},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75df4744fd2143889535ca84c1c967e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":968},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d63019bc4f964cf09dfa70b755991223",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":968},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1af1c7ec095e489092b1702795e50f5b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":452},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"33e857923ce74954935ad8471fc5f83b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":1012},
            "size":{
              "width":237,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d4f3f592f104b3dbcf75e7939455bb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":1012},
                "size":{
                  "width":237,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"145cbdaac6e1484caa26af3e844c3bcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":1216},
            "size":{
              "width":246,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d613ad6279466087cb61e365a8bb1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":1216},
                "size":{
                  "width":246,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b089001467f54a7bb55a44b45915374f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":918},
            "size":{
              "width":135,
              "height":10},
            "rotation":"50"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/阅卷页（操作栏在左侧）/u145_line.png"}},
{
          "id":"7da5db892d714e93802a0fc3febbe3e0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":876},
            "size":{
              "width":135,
              "height":10},
            "rotation":"50"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/阅卷页（操作栏在左侧）/u145_line.png"}},
{
          "id":"7a3b84fee70844a5ab9d2a92b3055bc8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":881},
            "size":{
              "width":96,
              "height":10},
            "rotation":"340"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/阅卷页（操作栏在左侧）/u147_line.png"}},
{
          "id":"e25c835b17cb4612a72b5e9bda549ddb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":881},
            "size":{
              "width":137,
              "height":10},
            "rotation":"310"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/阅卷页（操作栏在左侧）/u148_line.png"}},
{
          "id":"f324280cecd94827b0ce4a24ee2239f8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":478,
              "y":936},
            "size":{
              "width":108,
              "height":10},
            "rotation":"325"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/阅卷页（操作栏在左侧）/u149_line.png"}},
{
          "id":"eb35e6a82584498ab39ddbb38ef6a184",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":684},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c0c314a22b1d4b50b539bcad0a88e848",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":445,
              "y":889},
            "size":{
              "width":15,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068ad3b1ff744340b8bd8294f5be0ae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":889},
                "size":{
                  "width":15,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb0473d7e4cc420dbe4db766a58c1d34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":445,
              "y":926},
            "size":{
              "width":15,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ae49630f33640e5ba3b7df7aed25d29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":926},
                "size":{
                  "width":15,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a38bdf2f0e14949b64b8db0b8d3462b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":640,
              "y":506},
            "size":{
              "width":15,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35c026e102494d6dbe19e2ef3a1fcc48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":506},
                "size":{
                  "width":15,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4257bd51c5c742d2b4a45b67d84d0348",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":630,
              "y":535},
            "size":{
              "width":15,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"511fd75345e948b4a88726f4630b6abe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":535},
                "size":{
                  "width":15,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59f101dc94da42ea9f0a32474abe0f2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":440,
              "y":481},
            "size":{
              "width":93,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9c0ab7a8f5149f1af365ee4494dcce1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":481},
                "size":{
                  "width":93,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a01165ca9ab140a49a0a51920a4c6bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":440,
              "y":231},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991e5ef8e92746c583e9465e03745335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":231},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9635f9e585e54edcaf145c7bb891d9e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":440,
              "y":715},
            "size":{
              "width":136,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cc14ce9da1d4a81be75063dab054451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":715},
                "size":{
                  "width":136,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f457770ef6e743079afc4a72596a3d17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1049},
            "size":{
              "width":160,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e381f8e280f4988a25f88d0b28cb7bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1049},
                "size":{
                  "width":160,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9656165aaa4d4135adf95910ff17ef74",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":460,
              "y":1134},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"118fcf91b78e457aba08313255daad8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":460,
                  "y":1134},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"91a9388cca3b4e28a6e06fd03ba52922",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "disabled":true,
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":460,
              "y":1163},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d22fb57a6924f258b3c8e0bad1bd5af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":460,
                  "y":1163},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"7c881915469d4ebb96b1a97a9ef7be97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":440,
              "y":1075},
            "size":{
              "width":92,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca09f21d08324f8ca8d73abfdb150032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":1075},
                "size":{
                  "width":92,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5c8dcc7bcf54852b53aa5369568ba06",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":1049},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"01c0a028360a49ae8acd28da4d440c7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":517,
              "y":1130},
            "size":{
              "width":15,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"083e0d35524640c0b4977e86e012023d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":517,
                  "y":1130},
                "size":{
                  "width":15,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2da1e1d99234a76925fc4d2f60e907b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":440,
              "y":1101},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a80ce5b78574c19aae86ca4b9559ede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":1101},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65fef97961304ea8b3615b5aff920207",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1261},
            "size":{
              "width":165,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17116bd872d3452f8dce3591bd10cb7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":1261},
                "size":{
                  "width":165,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0c85e6a84934aeaa6c3e10b333cebcf",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":1321},
            "size":{
              "width":750,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"4e18ed8be28c44a49c7d2e668a5eeddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":440,
              "y":1290},
            "size":{
              "width":501,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8019d22e49594faea4c6019e37674181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":1290},
                "size":{
                  "width":501,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9186081a8fe24e9e9470deede09bd1a6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":1259.5},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8fe3a90c97ea494ca5f628609c878c9d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":960,
              "y":1549},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"4d9c306ce9934501a5c6cec6198819f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":369},
            "size":{
              "width":127,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59401de891d149c6926f5063ee3a40db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":369},
                "size":{
                  "width":127,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba5daf705ac54189bb17b235633af4a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":425},
            "size":{
              "width":128,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84f140412ea460f862162c016870672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":425},
                "size":{
                  "width":128,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e05acfec6b5549269e62bcf3e26663ed",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":410},
            "size":{
              "width":240,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/查看试卷（后台）/u118_line.png"}},
{
          "id":"e7dca72e262f4235a5efa68687f9d327",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":494},
            "size":{
              "width":10,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/在线考试/u86_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/在线考试/u86_line.png"}},
{
          "id":"4bf67f6aee3b4f58a4aba24992173860",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "paddingTop":"8",
            "paddingBottom":"8",
            "location":{
              "x":70,
              "y":534},
            "size":{
              "width":200,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0485a3d51db14a00ad206511fab2e08d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "paddingTop":"8",
                "paddingBottom":"8",
                "location":{
                  "x":70,
                  "y":534},
                "size":{
                  "width":200,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看试卷（后台）/u120.png"}},
{
          "id":"4eaa1711c24b4a6abbcdb25e13840642",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":250},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"8ec03a99bd8446579816ad32f1054b6c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":200,
              "y":250},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"f97aa53d7ddc4302b2093b6b63011171",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":946,
              "y":1435},
            "size":{
              "width":261,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84950f101dc54ca9b9a2eadf92033592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":946,
                  "y":1435},
                "size":{
                  "width":261,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06e168b2a9f14b299e78eba25d14ed7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":915,
              "y":1416},
            "size":{
              "width":38,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67d14d6d78e4e0ab7a4f6ab4277b91d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":915,
                  "y":1416},
                "size":{
                  "width":38,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/阅卷页（操作栏在左侧）/u206.png"}},
{
          "id":"0d1e25da5944462db28f781de58d742d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":1000,
              "y":1503},
            "size":{
              "width":70,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40790233249f43ffa89056e50e97783d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":1000,
                  "y":1503},
                "size":{
                  "width":70,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看试卷（后台）/u128.png"}},
{
          "id":"5ae980e908e74fe1bf7df0709b04e063",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":1462},
            "size":{
              "width":10,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/在线考试/u86_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/在线考试/u86_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1c54dc01c4724affbf862b92512b363b":{
      "scriptId":"u0"},
    "98137117ee6d48f98add7623f1f13d03":{
      "scriptId":"u1"},
    "5f0355b66d5c4b2bb6b0e7a698d3ca44":{
      "scriptId":"u2"},
    "18046f6c5f7e4d52a3bd2b95926c25cf":{
      "scriptId":"u3"},
    "24d1dde79f5743ed97072321573ae9af":{
      "scriptId":"u4"},
    "01b191d8b0ea4ed8a1b172ea54eaa285":{
      "scriptId":"u5"},
    "48ca1507882c49f7b5d16247789d54a1":{
      "scriptId":"u6"},
    "04dd0351345641f2b710a3e863be4315":{
      "scriptId":"u7"},
    "5e000302076e40a3a8d4e8b67ffc0026":{
      "scriptId":"u8"},
    "b7d35eb1ed814d33bfc1cf85df84b941":{
      "scriptId":"u9"},
    "08591a368f5f4643aacf1c92a8455ace":{
      "scriptId":"u10"},
    "b70d858a89784ff4905efd1635163e5b":{
      "scriptId":"u11"},
    "7988176768284f00ad7db3c23821ee84":{
      "scriptId":"u12"},
    "27ffe42f28b346fea9af003977894b10":{
      "scriptId":"u13"},
    "dc1443531222499288be58b19cc12ee6":{
      "scriptId":"u14"},
    "ae40d18bb90f4b8eb465ad6e41a1733e":{
      "scriptId":"u15"},
    "a9a146e1172f4d71b00b867c4c1f817e":{
      "scriptId":"u16"},
    "e7fab89e91c949ed8f862578d35bb540":{
      "scriptId":"u17"},
    "f68fa52a3e9448eeb5e773ed8694a7b7":{
      "scriptId":"u18"},
    "8ba07be92fff462d8ce2e13fda858553":{
      "scriptId":"u19"},
    "54ff7210a825414887adeb7da0ef0fc9":{
      "scriptId":"u20"},
    "ade4b6f905a945419e75549eeca47086":{
      "scriptId":"u21"},
    "cf6b987567604227853bfede4f7e82fa":{
      "scriptId":"u22"},
    "caf5594fefe24ecfaed675a87bddb60c":{
      "scriptId":"u23"},
    "30e4668e3f9b4eb9a3677c1b4f35220b":{
      "scriptId":"u24"},
    "4cdb7e35b272455daedad338c1a2641b":{
      "scriptId":"u25"},
    "d54fff499faa4c7c921979ab0a64e8d3":{
      "scriptId":"u26"},
    "3eae46a21b5e4872b36279777a437da8":{
      "scriptId":"u27"},
    "a64ad29342ef44e2a5d104eea53c71b4":{
      "scriptId":"u28"},
    "d71a8c09da4b405aab1db6da8eaff8c3":{
      "scriptId":"u29"},
    "ba0c85c427444d10bc2ddcc47d3b269d":{
      "scriptId":"u30"},
    "da8ca65f6e374ab1a02052e359ae9da4":{
      "scriptId":"u31"},
    "3a803643c1d64c97a164fb80bc41c270":{
      "scriptId":"u32"},
    "0af8a7f1706e49959d707546009d7bea":{
      "scriptId":"u33"},
    "56405802bceb4ff7996dd4d94c80248c":{
      "scriptId":"u34"},
    "6452260cea0e4903b617bd5f4e5ddf0f":{
      "scriptId":"u35"},
    "4c0fd44e1e114e33a0bb06f8c2512545":{
      "scriptId":"u36"},
    "5b6302d88c7f4daaa522314f553f105f":{
      "scriptId":"u37"},
    "3cea042df12446ea935eb278db5aa13a":{
      "scriptId":"u38"},
    "c04ab476dc8743b0bd7fb074c19c00aa":{
      "scriptId":"u39"},
    "e41336e462fb4c97afc55fe07cdecffb":{
      "scriptId":"u40"},
    "d45de312f878431a8c853900d5d83f67":{
      "scriptId":"u41"},
    "a360228c7d1747e4a315fb8cdc3e0413":{
      "scriptId":"u42"},
    "5ffb6467c5614ef28eec6c8deb4a0553":{
      "scriptId":"u43"},
    "7592c2235dc54fcd9d65df8e4e08aa3a":{
      "scriptId":"u44"},
    "893440d788974036bd19eb8c00cc1da8":{
      "scriptId":"u45"},
    "54b07fb36ed24133977784e1ab65eb21":{
      "scriptId":"u46"},
    "156170eb855c4abdbef41ef18cdf86a5":{
      "scriptId":"u47"},
    "0b158df66f1346bc98312bfe3e621b3a":{
      "scriptId":"u48"},
    "dcd7f7e98ab0457480cf287b37169581":{
      "scriptId":"u49"},
    "c628f653ff0c49e6bd0c7c322bc049ff":{
      "scriptId":"u50"},
    "48104bcf77924207ad3690fcd30b622e":{
      "scriptId":"u51"},
    "31f20d55ea914a22af4aa413ff4156e3":{
      "scriptId":"u52"},
    "2aec2a075cf4436fb086349adc44a042":{
      "scriptId":"u53"},
    "ee0016219d7646de90f838aa74bfcc5e":{
      "scriptId":"u54"},
    "7760702fb40e4cdc8ed35ab58d31c002":{
      "scriptId":"u55"},
    "8f20a6bfa35a4f518f5ae3f795a971e3":{
      "scriptId":"u56"},
    "9ecaaab6bf624520b8ddd3391cdcf245":{
      "scriptId":"u57"},
    "5460093626884db0b3a1c8d92382b62d":{
      "scriptId":"u58"},
    "3b4e9b153de4435abd3854f575b3bb99":{
      "scriptId":"u59"},
    "beb0d474a281434abbc445ede93fcd04":{
      "scriptId":"u60"},
    "8f78f12f1fb240d1a2ac19a8cb1d6acd":{
      "scriptId":"u61"},
    "3f586fe35fcc4ed5a56c907c78acb6ae":{
      "scriptId":"u62"},
    "744e236e7d9d4583a53404719d1c694c":{
      "scriptId":"u63"},
    "966be0c83c0345109f531c0263700f37":{
      "scriptId":"u64"},
    "3bb86d6bfc3646b8bfbe73f4b0c682e4":{
      "scriptId":"u65"},
    "5ae585b8dc48433b83e4a3ff4e303b03":{
      "scriptId":"u66"},
    "75df4744fd2143889535ca84c1c967e2":{
      "scriptId":"u67"},
    "d63019bc4f964cf09dfa70b755991223":{
      "scriptId":"u68"},
    "1af1c7ec095e489092b1702795e50f5b":{
      "scriptId":"u69"},
    "33e857923ce74954935ad8471fc5f83b":{
      "scriptId":"u70"},
    "6d4f3f592f104b3dbcf75e7939455bb7":{
      "scriptId":"u71"},
    "145cbdaac6e1484caa26af3e844c3bcc":{
      "scriptId":"u72"},
    "95d613ad6279466087cb61e365a8bb1f":{
      "scriptId":"u73"},
    "b089001467f54a7bb55a44b45915374f":{
      "scriptId":"u74"},
    "7da5db892d714e93802a0fc3febbe3e0":{
      "scriptId":"u75"},
    "7a3b84fee70844a5ab9d2a92b3055bc8":{
      "scriptId":"u76"},
    "e25c835b17cb4612a72b5e9bda549ddb":{
      "scriptId":"u77"},
    "f324280cecd94827b0ce4a24ee2239f8":{
      "scriptId":"u78"},
    "eb35e6a82584498ab39ddbb38ef6a184":{
      "scriptId":"u79"},
    "c0c314a22b1d4b50b539bcad0a88e848":{
      "scriptId":"u80"},
    "068ad3b1ff744340b8bd8294f5be0ae7":{
      "scriptId":"u81"},
    "bb0473d7e4cc420dbe4db766a58c1d34":{
      "scriptId":"u82"},
    "5ae49630f33640e5ba3b7df7aed25d29":{
      "scriptId":"u83"},
    "2a38bdf2f0e14949b64b8db0b8d3462b":{
      "scriptId":"u84"},
    "35c026e102494d6dbe19e2ef3a1fcc48":{
      "scriptId":"u85"},
    "4257bd51c5c742d2b4a45b67d84d0348":{
      "scriptId":"u86"},
    "511fd75345e948b4a88726f4630b6abe":{
      "scriptId":"u87"},
    "59f101dc94da42ea9f0a32474abe0f2b":{
      "scriptId":"u88"},
    "c9c0ab7a8f5149f1af365ee4494dcce1":{
      "scriptId":"u89"},
    "a01165ca9ab140a49a0a51920a4c6bf4":{
      "scriptId":"u90"},
    "991e5ef8e92746c583e9465e03745335":{
      "scriptId":"u91"},
    "9635f9e585e54edcaf145c7bb891d9e0":{
      "scriptId":"u92"},
    "5cc14ce9da1d4a81be75063dab054451":{
      "scriptId":"u93"},
    "f457770ef6e743079afc4a72596a3d17":{
      "scriptId":"u94"},
    "0e381f8e280f4988a25f88d0b28cb7bb":{
      "scriptId":"u95"},
    "9656165aaa4d4135adf95910ff17ef74":{
      "scriptId":"u96"},
    "118fcf91b78e457aba08313255daad8e":{
      "scriptId":"u97"},
    "91a9388cca3b4e28a6e06fd03ba52922":{
      "scriptId":"u98"},
    "3d22fb57a6924f258b3c8e0bad1bd5af":{
      "scriptId":"u99"},
    "7c881915469d4ebb96b1a97a9ef7be97":{
      "scriptId":"u100"},
    "ca09f21d08324f8ca8d73abfdb150032":{
      "scriptId":"u101"},
    "a5c8dcc7bcf54852b53aa5369568ba06":{
      "scriptId":"u102"},
    "01c0a028360a49ae8acd28da4d440c7a":{
      "scriptId":"u103"},
    "083e0d35524640c0b4977e86e012023d":{
      "scriptId":"u104"},
    "c2da1e1d99234a76925fc4d2f60e907b":{
      "scriptId":"u105"},
    "8a80ce5b78574c19aae86ca4b9559ede":{
      "scriptId":"u106"},
    "65fef97961304ea8b3615b5aff920207":{
      "scriptId":"u107"},
    "17116bd872d3452f8dce3591bd10cb7d":{
      "scriptId":"u108"},
    "c0c85e6a84934aeaa6c3e10b333cebcf":{
      "scriptId":"u109"},
    "4e18ed8be28c44a49c7d2e668a5eeddd":{
      "scriptId":"u110"},
    "8019d22e49594faea4c6019e37674181":{
      "scriptId":"u111"},
    "9186081a8fe24e9e9470deede09bd1a6":{
      "scriptId":"u112"},
    "8fe3a90c97ea494ca5f628609c878c9d":{
      "scriptId":"u113"},
    "4d9c306ce9934501a5c6cec6198819f0":{
      "scriptId":"u114"},
    "59401de891d149c6926f5063ee3a40db":{
      "scriptId":"u115"},
    "ba5daf705ac54189bb17b235633af4a0":{
      "scriptId":"u116"},
    "c84f140412ea460f862162c016870672":{
      "scriptId":"u117"},
    "e05acfec6b5549269e62bcf3e26663ed":{
      "scriptId":"u118"},
    "e7dca72e262f4235a5efa68687f9d327":{
      "scriptId":"u119"},
    "4bf67f6aee3b4f58a4aba24992173860":{
      "scriptId":"u120"},
    "0485a3d51db14a00ad206511fab2e08d":{
      "scriptId":"u121"},
    "4eaa1711c24b4a6abbcdb25e13840642":{
      "scriptId":"u122"},
    "8ec03a99bd8446579816ad32f1054b6c":{
      "scriptId":"u123"},
    "f97aa53d7ddc4302b2093b6b63011171":{
      "scriptId":"u124"},
    "84950f101dc54ca9b9a2eadf92033592":{
      "scriptId":"u125"},
    "06e168b2a9f14b299e78eba25d14ed7f":{
      "scriptId":"u126"},
    "e67d14d6d78e4e0ab7a4f6ab4277b91d":{
      "scriptId":"u127"},
    "0d1e25da5944462db28f781de58d742d":{
      "scriptId":"u128"},
    "40790233249f43ffa89056e50e97783d":{
      "scriptId":"u129"},
    "5ae980e908e74fe1bf7df0709b04e063":{
      "scriptId":"u130"}}});