$axure.loadCurrentPage({
  "url":"无相关结果.html",
  "generationDate":new Date(1446546666551.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fdd8869516014afe8beacffa778474ba",
    "type":"Axure:Page",
    "name":"无相关结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"db578d9e702c4dc98d746752728a7c1b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":886,
              "y":31},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"dbef703263a14148992e9bef2b35374a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":1235,
              "y":31},
            "size":{
              "width":60,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索结果",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3343335c078044feadf3cc68fbf0c4a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":81},
            "size":{
              "width":1342,
              "height":40},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e54681160f4335867ea8c4433b693f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":81},
                "size":{
                  "width":1342,
                  "height":40},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_未登录/u2.png"}},
{
          "id":"2b8567c381db40539729dd99313f6bca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":34,
              "y":90},
            "size":{
              "width":33,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fbdd3c9ba9f46bea024b6182042df22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":34,
                  "y":90},
                "size":{
                  "width":33,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home - 已登录",
                      "target":{
                        "targetType":"page",
                        "url":"home_-_已登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de6aeb8a2f844efb8603ed2c6b533923",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":95,
              "y":90},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7981c0dc20e64300be5a8602a51e6d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":95,
                  "y":90},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程中心",
                      "target":{
                        "targetType":"page",
                        "url":"课程中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9d9e945830446afb75b517a7b3fe252",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":187,
              "y":90},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9a48f1cf5542ae9f3078681673ed70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":187,
                  "y":90},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的课程",
                      "target":{
                        "targetType":"page",
                        "url":"我的课程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34ea85e250fd42eca2c633268a1e8658",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":280,
              "y":90},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f375008c74444bd798243a56e23d9744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":280,
                  "y":90},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的题库",
                      "target":{
                        "targetType":"page",
                        "url":"我的题库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cb99bbb429b41be9398d6480e07ded5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":372,
              "y":90},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6240e37f9c914599bf45a7e5d57116dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":372,
                  "y":90},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的问答",
                      "target":{
                        "targetType":"page",
                        "url":"我的问答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afddcbb1e67f435fb49f19223de0fbb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":465,
              "y":90},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20c7ca12863548f49658fd8cf7f8fa6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":465,
                  "y":90},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的笔记",
                      "target":{
                        "targetType":"page",
                        "url":"我的笔记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a71029273b1c4af8af72e948715cb33f",
          "label":"已登录",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":80},
            "size":{
              "width":280,
              "height":234}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"54555c0993dc40eba9f45ffa9df8516e",
              "label":"已登录_鼠标未经过",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0dc17688859e4c4d81850fba01c4dafe",
                  "label":"",
                  "parentDynamicPanel":"a71029273b1c4af8af72e948715cb33f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":191,
                      "y":12},
                    "size":{
                      "width":49,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e191afd489bc4e28ab430d172e56fb70",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a71029273b1c4af8af72e948715cb33f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "horizontalAlignment":"right",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":191,
                          "y":12},
                        "size":{
                          "width":49,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ac8e4d74fce943e584af8c9fcf714418",
                  "label":"",
                  "parentDynamicPanel":"a71029273b1c4af8af72e948715cb33f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":161,
                      "y":8},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7356b42005bd4f49a7e8a9f84ad2c973",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a71029273b1c4af8af72e948715cb33f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":161,
                          "y":8},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home_-_已登录/u19.png"}},
{
                  "id":"eca45de4f8174bc38865d7fa7c8f376d",
                  "label":"",
                  "parentDynamicPanel":"a71029273b1c4af8af72e948715cb33f",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":135,
                      "y":0},
                    "size":{
                      "width":145,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 已登录 to 已登录_鼠标经过",
                              "panelsToStates":[{
                                  "panelPath":["a71029273b1c4af8af72e948715cb33f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"setPanelOrder",
                              "description":"移动 已登录 到顶层 ",
                              "panelPaths":[{
                                  "panelPath":["a71029273b1c4af8af72e948715cb33f"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 已登录 to 已登录_鼠标经过",
                              "panelsToStates":[{
                                  "panelPath":["a71029273b1c4af8af72e948715cb33f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"setPanelOrder",
                              "description":"移动 已登录 到顶层 ",
                              "panelPaths":[{
                                  "panelPath":["a71029273b1c4af8af72e948715cb33f"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"18c67938074543a9920e68a43ca05912",
              "label":"已登录_鼠标经过",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"79c386af4274432fa2ee3ab83931225e",
                  "label":"",
                  "parentDynamicPanel":"a71029273b1c4af8af72e948715cb33f",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":135,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 已登录 to 已登录_鼠标未经过",
                              "panelsToStates":[{
                                  "panelPath":["a71029273b1c4af8af72e948715cb33f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 已登录 to 已登录_鼠标经过",
                              "panelsToStates":[{
                                  "panelPath":["a71029273b1c4af8af72e948715cb33f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]},
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 已登录 to 已登录_鼠标未经过",
                              "panelsToStates":[{
                                  "panelPath":["a71029273b1c4af8af72e948715cb33f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"fce8cd30192a4ab8a3b9d7e5fe57fe21",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"c65ee3c0d65d4c3bb62d46a635b3791a",
                          "label":"",
                          "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "fontSize":"16px",
                            "verticalAlignment":"top",
                            "lineSpacing":"40px",
                            "paddingTop":"5",
                            "location":{
                              "x":0,
                              "y":39},
                            "size":{
                              "width":145,
                              "height":131}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"4cb80ff092124108a4082a370947eb51",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "fontSize":"16px",
                                "verticalAlignment":"top",
                                "lineSpacing":"40px",
                                "paddingTop":"5",
                                "location":{
                                  "x":0,
                                  "y":39},
                                "size":{
                                  "width":145,
                                  "height":131}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home_-_已登录/u23.png"}},
{
                          "id":"8ada157e3a9244728363ca4500b1f614",
                          "label":"",
                          "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "fontSize":"16px",
                            "size":{
                              "width":145,
                              "height":40},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f417f9b64c6b49998680e8fb323ca081",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "fontSize":"16px",
                                "size":{
                                  "width":145,
                                  "height":40},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home_-_已登录/u25.png"}},
{
                          "id":"e739dea8c230471b83d019be7d5fb779",
                          "label":"",
                          "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":26,
                              "y":8},
                            "size":{
                              "width":24,
                              "height":24},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF000000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7bddaa3b877241cdadefe3f5d88fb85c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":26,
                                  "y":8},
                                "size":{
                                  "width":24,
                                  "height":24},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home_-_已登录/u19.png"}},
{
                          "id":"80f4f7bfeaf840189487ec973eabbf34",
                          "label":"",
                          "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                          "type":"imageMapRegion",
                          "styleType":"imageMapRegion",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":128},
                            "size":{
                              "width":145,
                              "height":40}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 Home - 未登录",
                                      "target":{
                                        "targetType":"page",
                                        "url":"home_-_未登录.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true},
{
                          "id":"28dec12000154ac4a355a2a8934fde30",
                          "label":"",
                          "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":110,
                              "y":56},
                            "size":{
                              "width":20,
                              "height":14},
                            "rotation":"0",
                            "textRotation":"0",
                            "borderWidth":"0",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF000000},
                            "cornerRadiusTopLeft":"0"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7e6012e8fad24058bd370c9885bbf2dd",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":110,
                                  "y":56},
                                "size":{
                                  "width":20,
                                  "height":14},
                                "rotation":"0",
                                "textRotation":"0",
                                "borderWidth":"0",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000},
                                "cornerRadiusTopLeft":"0"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home_-_已登录/u30.png"}},
{
                          "id":"c908011badaf4da1aeec5e09a02ec091",
                          "label":"",
                          "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                          "type":"imageMapRegion",
                          "styleType":"imageMapRegion",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":43},
                            "size":{
                              "width":145,
                              "height":40}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 通知中心",
                                      "target":{
                                        "targetType":"page",
                                        "url":"通知中心.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true},
{
                          "id":"3b3b840306c44397afb8c0e70dd92cea",
                          "label":"",
                          "parentDynamicPanel":"79c386af4274432fa2ee3ab83931225e",
                          "type":"imageMapRegion",
                          "styleType":"imageMapRegion",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":84},
                            "size":{
                              "width":145,
                              "height":40}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 个人设置",
                                      "target":{
                                        "targetType":"page",
                                        "url":"个人设置.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}]}]}]},
{
          "id":"9689f5af690644b395d52d40d30d8154",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":110,
              "y":34},
            "size":{
              "width":153,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39e5a7c139a34da4aa1216894d490442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":34},
                "size":{
                  "width":153,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfa6e85c36e0407f94b4f7d665ea97f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":34,
              "y":20},
            "size":{
              "width":66,
              "height":42},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7cb524d1b3d4944a82593d504a8d459",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":34,
                  "y":20},
                "size":{
                  "width":66,
                  "height":42},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_未登录/u25.png"}},
{
          "id":"3b257450a46f42479f312e087cab8a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":170},
            "size":{
              "width":1261,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"913e5a1f5fbc42d5b4a2de0bf3adcca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":170},
                "size":{
                  "width":1261,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程中心/u38.png"}},
{
          "id":"c28ef40faef34644bde39a0d4597677a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":189},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e0197dad03c460b913d33b429fa0afe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":189},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88f4c11128124d6e84a9d6b5105181e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":242},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e56c1004ca64bb5845ddd120526fcd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":242},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88f8e36df0994dd2a683c6aea611f84c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":296},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daa04558e2b24d56837b9218a94958f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":296},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b55b092fdf244659e8822c370ab66d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":130,
              "y":189},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"874d88933f4d4deb80e63d6026d25056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":130,
                  "y":189},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程中心/u46.png"}},
{
          "id":"030980f10c2049a3a236cb027bf00d82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":130,
              "y":242},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76782418a7b24a57870091ae7e698b82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":130,
                  "y":242},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程中心/u46.png"}},
{
          "id":"f7bc5a34d6d34a279695f19d401e4151",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":130,
              "y":296},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8cbc83be4484c2382e3e3788453cc6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":130,
                  "y":296},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程中心/u46.png"}},
{
          "id":"8cad2c8c7eb64571994dbabf5ef5b0ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":296},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9284e741a20447ed9f88b565e0064509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":296},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71a26bb739d940ca8415751a0dcafa1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":296},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fac5f954131455f9e361754966339d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":296},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b629301fb45455dba843e9aa77cc2e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":296},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"552850a161114bd0b028457445005c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":296},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c73868b250e4495aa0b5af1ec58e1bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":189},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e110f62d1a452495fd05dff097b04b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":189},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17781ddb548b4541b6b0546ed7edac89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":189},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94878bfa146746b4b68922e625ab859e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":189},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8f381ab050b4516b6e0195aa83b5e62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":189},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d51fbbff8a244e92a21251a32f0323bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":189},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f3d6cab6bbb4b6ebe5955e644c1abfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":189},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57124463170246cc9003e9f0321c22d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":189},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd6b8ec8478f4c11a60379fae2595c89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":517,
              "y":189},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25d2cc24677f49109cbd51fa3690795e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":517,
                  "y":189},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb258cee6644480983ed25a2abe31789",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":189},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2844c65207a04b41871181e9dc9fd9ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":189},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c44d777ac76e4fe7ae3414d4b15e31a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":242},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77eb8d77d9c94610a40dd2abf7b5e1aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":242},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"231b58d276514a669f75a4469a77f829",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":242},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b9c0f78e381465aafdf8476d155b8e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":242},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82f92502616c4d50b11c398be11d67bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":242},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4cea0b64124ca7a08cff53931bf536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":242},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6377e5492e3b4f52ab95f834b8ebc93f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":242},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f0265a90f2e4c2fbcaa6592dc4d6165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":242},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f8562eea34848ef933a71cda8f2dffa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":517,
              "y":242},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b88e8a300ce1443499102f3776ff6c42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":517,
                  "y":242},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49d59211885c46b9885a37a3e2fa5860",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":34,
              "y":352},
            "size":{
              "width":1261,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d5f049b8cc6428893288a7376310294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":34,
                  "y":352},
                "size":{
                  "width":1261,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程中心/u80.png"}},
{
          "id":"b560fb86a5104f26bfc6ad378033d5c6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":375},
            "size":{
              "width":56,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/课程中心/u82_line.png"}},
{
          "id":"c717a8b8b0b443bc9c496b743d7b36b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":40,
              "y":356},
            "size":{
              "width":29,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a71c7e7f22ec46eca378773dbde51134",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":40,
                  "y":356},
                "size":{
                  "width":29,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e11e14f13ba0429cb2a81a8df1378d46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":73,
              "y":356},
            "size":{
              "width":57,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e30a4d4afb6d4038af8517bbd49798f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":356},
                "size":{
                  "width":57,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28d7821946ae41069f897e378bfee3b4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":217},
            "size":{
              "width":1261,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/课程中心/u89_line.png"}},
{
          "id":"755da92250d246fa9a7f0d66dd1de199",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":270},
            "size":{
              "width":1261,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/课程中心/u89_line.png"}},
{
          "id":"1acc4c9cb54949cc9ef7d43fa3a8bae4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":34,
              "y":137},
            "size":{
              "width":185,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faaec5e9cc5c43bfb65c934a88d35137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":34,
                  "y":137},
                "size":{
                  "width":185,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"223df19cb30542d99fdbd853a140c044",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":1164,
              "y":359},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20e2f0cb0fa4441e86635c6985390ab4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1164,
                  "y":359},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"58d2e2d21cc045a9a65a5ace2ab4868f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":950},
            "size":{
              "width":1342,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02a3236bb20746c68221e3907e0168cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":950},
                "size":{
                  "width":1342,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_未登录/u47.png"}},
{
          "id":"25775352f64f46a598f19240b9f40818",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":558,
              "y":976},
            "size":{
              "width":71,
              "height":42},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05cb75ac818349cc98bf776a4006e820",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":558,
                  "y":976},
                "size":{
                  "width":71,
                  "height":42},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_未登录/u49.png"}},
{
          "id":"4af6bc24964e4cbf917b9186e737624e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":632,
              "y":990},
            "size":{
              "width":153,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22824da68ff34f609ecc0ae743f2dbe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":632,
                  "y":990},
                "size":{
                  "width":153,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8abd90ad4e74a9986000185d401e6fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":406,
              "y":499},
            "size":{
              "width":546,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6120b443f71f4a98ac763d4fc347ee22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":406,
                  "y":499},
                "size":{
                  "width":546,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cfbb70385d445609a9e130f7f3afc31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":430},
            "size":{
              "width":150,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"233e8ad61f8a49a8be236527e20263ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":430},
                "size":{
                  "width":150,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/无相关结果/u101.png"}},
{
          "id":"54b201171d0246198315869e500ee9a1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":370,
              "y":630},
            "size":{
              "width":449,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"33c901bdc1a1469896178aedd212facb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":832,
              "y":630},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索结果",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "db578d9e702c4dc98d746752728a7c1b":{
      "scriptId":"u0"},
    "dbef703263a14148992e9bef2b35374a":{
      "scriptId":"u1"},
    "3343335c078044feadf3cc68fbf0c4a0":{
      "scriptId":"u2"},
    "58e54681160f4335867ea8c4433b693f":{
      "scriptId":"u3"},
    "2b8567c381db40539729dd99313f6bca":{
      "scriptId":"u4"},
    "9fbdd3c9ba9f46bea024b6182042df22":{
      "scriptId":"u5"},
    "de6aeb8a2f844efb8603ed2c6b533923":{
      "scriptId":"u6"},
    "7981c0dc20e64300be5a8602a51e6d55":{
      "scriptId":"u7"},
    "b9d9e945830446afb75b517a7b3fe252":{
      "scriptId":"u8"},
    "8e9a48f1cf5542ae9f3078681673ed70":{
      "scriptId":"u9"},
    "34ea85e250fd42eca2c633268a1e8658":{
      "scriptId":"u10"},
    "f375008c74444bd798243a56e23d9744":{
      "scriptId":"u11"},
    "6cb99bbb429b41be9398d6480e07ded5":{
      "scriptId":"u12"},
    "6240e37f9c914599bf45a7e5d57116dd":{
      "scriptId":"u13"},
    "afddcbb1e67f435fb49f19223de0fbb4":{
      "scriptId":"u14"},
    "20c7ca12863548f49658fd8cf7f8fa6b":{
      "scriptId":"u15"},
    "a71029273b1c4af8af72e948715cb33f":{
      "scriptId":"u16"},
    "0dc17688859e4c4d81850fba01c4dafe":{
      "scriptId":"u17"},
    "e191afd489bc4e28ab430d172e56fb70":{
      "scriptId":"u18"},
    "ac8e4d74fce943e584af8c9fcf714418":{
      "scriptId":"u19"},
    "7356b42005bd4f49a7e8a9f84ad2c973":{
      "scriptId":"u20"},
    "eca45de4f8174bc38865d7fa7c8f376d":{
      "scriptId":"u21"},
    "79c386af4274432fa2ee3ab83931225e":{
      "scriptId":"u22"},
    "c65ee3c0d65d4c3bb62d46a635b3791a":{
      "scriptId":"u23"},
    "4cb80ff092124108a4082a370947eb51":{
      "scriptId":"u24"},
    "8ada157e3a9244728363ca4500b1f614":{
      "scriptId":"u25"},
    "f417f9b64c6b49998680e8fb323ca081":{
      "scriptId":"u26"},
    "e739dea8c230471b83d019be7d5fb779":{
      "scriptId":"u27"},
    "7bddaa3b877241cdadefe3f5d88fb85c":{
      "scriptId":"u28"},
    "80f4f7bfeaf840189487ec973eabbf34":{
      "scriptId":"u29"},
    "28dec12000154ac4a355a2a8934fde30":{
      "scriptId":"u30"},
    "7e6012e8fad24058bd370c9885bbf2dd":{
      "scriptId":"u31"},
    "c908011badaf4da1aeec5e09a02ec091":{
      "scriptId":"u32"},
    "3b3b840306c44397afb8c0e70dd92cea":{
      "scriptId":"u33"},
    "9689f5af690644b395d52d40d30d8154":{
      "scriptId":"u34"},
    "39e5a7c139a34da4aa1216894d490442":{
      "scriptId":"u35"},
    "bfa6e85c36e0407f94b4f7d665ea97f5":{
      "scriptId":"u36"},
    "e7cb524d1b3d4944a82593d504a8d459":{
      "scriptId":"u37"},
    "3b257450a46f42479f312e087cab8a31":{
      "scriptId":"u38"},
    "913e5a1f5fbc42d5b4a2de0bf3adcca2":{
      "scriptId":"u39"},
    "c28ef40faef34644bde39a0d4597677a":{
      "scriptId":"u40"},
    "1e0197dad03c460b913d33b429fa0afe":{
      "scriptId":"u41"},
    "88f4c11128124d6e84a9d6b5105181e5":{
      "scriptId":"u42"},
    "8e56c1004ca64bb5845ddd120526fcd0":{
      "scriptId":"u43"},
    "88f8e36df0994dd2a683c6aea611f84c":{
      "scriptId":"u44"},
    "daa04558e2b24d56837b9218a94958f0":{
      "scriptId":"u45"},
    "8b55b092fdf244659e8822c370ab66d9":{
      "scriptId":"u46"},
    "874d88933f4d4deb80e63d6026d25056":{
      "scriptId":"u47"},
    "030980f10c2049a3a236cb027bf00d82":{
      "scriptId":"u48"},
    "76782418a7b24a57870091ae7e698b82":{
      "scriptId":"u49"},
    "f7bc5a34d6d34a279695f19d401e4151":{
      "scriptId":"u50"},
    "b8cbc83be4484c2382e3e3788453cc6d":{
      "scriptId":"u51"},
    "8cad2c8c7eb64571994dbabf5ef5b0ce":{
      "scriptId":"u52"},
    "9284e741a20447ed9f88b565e0064509":{
      "scriptId":"u53"},
    "71a26bb739d940ca8415751a0dcafa1d":{
      "scriptId":"u54"},
    "9fac5f954131455f9e361754966339d1":{
      "scriptId":"u55"},
    "9b629301fb45455dba843e9aa77cc2e5":{
      "scriptId":"u56"},
    "552850a161114bd0b028457445005c5b":{
      "scriptId":"u57"},
    "8c73868b250e4495aa0b5af1ec58e1bd":{
      "scriptId":"u58"},
    "67e110f62d1a452495fd05dff097b04b":{
      "scriptId":"u59"},
    "17781ddb548b4541b6b0546ed7edac89":{
      "scriptId":"u60"},
    "94878bfa146746b4b68922e625ab859e":{
      "scriptId":"u61"},
    "c8f381ab050b4516b6e0195aa83b5e62":{
      "scriptId":"u62"},
    "d51fbbff8a244e92a21251a32f0323bc":{
      "scriptId":"u63"},
    "8f3d6cab6bbb4b6ebe5955e644c1abfa":{
      "scriptId":"u64"},
    "57124463170246cc9003e9f0321c22d8":{
      "scriptId":"u65"},
    "dd6b8ec8478f4c11a60379fae2595c89":{
      "scriptId":"u66"},
    "25d2cc24677f49109cbd51fa3690795e":{
      "scriptId":"u67"},
    "eb258cee6644480983ed25a2abe31789":{
      "scriptId":"u68"},
    "2844c65207a04b41871181e9dc9fd9ac":{
      "scriptId":"u69"},
    "c44d777ac76e4fe7ae3414d4b15e31a2":{
      "scriptId":"u70"},
    "77eb8d77d9c94610a40dd2abf7b5e1aa":{
      "scriptId":"u71"},
    "231b58d276514a669f75a4469a77f829":{
      "scriptId":"u72"},
    "8b9c0f78e381465aafdf8476d155b8e1":{
      "scriptId":"u73"},
    "82f92502616c4d50b11c398be11d67bf":{
      "scriptId":"u74"},
    "ab4cea0b64124ca7a08cff53931bf536":{
      "scriptId":"u75"},
    "6377e5492e3b4f52ab95f834b8ebc93f":{
      "scriptId":"u76"},
    "3f0265a90f2e4c2fbcaa6592dc4d6165":{
      "scriptId":"u77"},
    "6f8562eea34848ef933a71cda8f2dffa":{
      "scriptId":"u78"},
    "b88e8a300ce1443499102f3776ff6c42":{
      "scriptId":"u79"},
    "49d59211885c46b9885a37a3e2fa5860":{
      "scriptId":"u80"},
    "5d5f049b8cc6428893288a7376310294":{
      "scriptId":"u81"},
    "b560fb86a5104f26bfc6ad378033d5c6":{
      "scriptId":"u82"},
    "c717a8b8b0b443bc9c496b743d7b36b1":{
      "scriptId":"u83"},
    "a71c7e7f22ec46eca378773dbde51134":{
      "scriptId":"u84"},
    "e11e14f13ba0429cb2a81a8df1378d46":{
      "scriptId":"u85"},
    "e30a4d4afb6d4038af8517bbd49798f8":{
      "scriptId":"u86"},
    "28d7821946ae41069f897e378bfee3b4":{
      "scriptId":"u87"},
    "755da92250d246fa9a7f0d66dd1de199":{
      "scriptId":"u88"},
    "1acc4c9cb54949cc9ef7d43fa3a8bae4":{
      "scriptId":"u89"},
    "faaec5e9cc5c43bfb65c934a88d35137":{
      "scriptId":"u90"},
    "223df19cb30542d99fdbd853a140c044":{
      "scriptId":"u91"},
    "20e2f0cb0fa4441e86635c6985390ab4":{
      "scriptId":"u92"},
    "58d2e2d21cc045a9a65a5ace2ab4868f":{
      "scriptId":"u93"},
    "02a3236bb20746c68221e3907e0168cf":{
      "scriptId":"u94"},
    "25775352f64f46a598f19240b9f40818":{
      "scriptId":"u95"},
    "05cb75ac818349cc98bf776a4006e820":{
      "scriptId":"u96"},
    "4af6bc24964e4cbf917b9186e737624e":{
      "scriptId":"u97"},
    "22824da68ff34f609ecc0ae743f2dbe8":{
      "scriptId":"u98"},
    "d8abd90ad4e74a9986000185d401e6fc":{
      "scriptId":"u99"},
    "6120b443f71f4a98ac763d4fc347ee22":{
      "scriptId":"u100"},
    "6cfbb70385d445609a9e130f7f3afc31":{
      "scriptId":"u101"},
    "233e8ad61f8a49a8be236527e20263ec":{
      "scriptId":"u102"},
    "54b201171d0246198315869e500ee9a1":{
      "scriptId":"u103"},
    "33c901bdc1a1469896178aedd212facb":{
      "scriptId":"u104"}}});