$axure.loadCurrentPage({
  "url":"正在上传.html",
  "generationDate":new Date(1428494665064.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"42807b781d8b4fedad7555932cdf92fe",
    "type":"Axure:Page",
    "name":"正在上传",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4ec02afa039541288d801c11b43aa3f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":62},
            "size":{
              "width":1200,
              "height":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e37f394efd5b4c5ca7c2b817a2e3ecdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":62},
                "size":{
                  "width":1200,
                  "height":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"4c192aabf9c14ec19f2361b0f9b79e86",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":286},
            "size":{
              "width":1115,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-无图片/u2_line.png"}},
{
          "id":"ab340035a1ec4d61bdb60f9b254ca073",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":612,
              "y":278},
            "size":{
              "width":160,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"24bdfc60a66b4c77aee37eb987126148",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":62},
            "size":{
              "width":1200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d7d503599954cccaa5e9f70bda41339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":62},
                "size":{
                  "width":1200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u4.png"}},
{
          "id":"8181b41e693e4a7a9be3d263e8824442",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Futura Condensed Bold', 'Futura'",
            "fontSize":"28px",
            "fontWeight":"700",
            "fontStyle":"normal",
            "horizontalAlignment":"center",
            "location":{
              "x":135,
              "y":68},
            "size":{
              "width":76,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb3238dd2a964d1e8fd9392c52ddeba5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Futura Condensed Bold', 'Futura'",
                "fontSize":"28px",
                "fontWeight":"700",
                "fontStyle":"normal",
                "horizontalAlignment":"center",
                "location":{
                  "x":135,
                  "y":68},
                "size":{
                  "width":76,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1b73bd3e9eb473bac8a3ce5ea4278d5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":62},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人首页-无图片/u8_line.png"}},
{
          "id":"94bf56affe7548e1b4737aebe7d79ce3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":282,
              "y":76},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e36f47f5aa2433b8d3614219cb41e10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":282,
                  "y":76},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d700674ef50454180603ef1a3e0a1ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":1217,
              "y":76},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2be55fe3cf024d3a8e37c2a6663b8465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":1217,
                  "y":76},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c04945ff276743eea7732541af5cc7b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":74},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2854aeba85cd4a469f9f653ac3bbbf02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":74},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u13.png"}},
{
          "id":"df01038637d94d6f8a715594368ca77e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":170},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d11fc9fb2eb749618db258771fb62521",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":170},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 图片列表",
                      "target":{
                        "targetType":"page",
                        "url":"图片列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人首页-无图片/u15.png"}},
{
          "id":"ff0195648cbf4ee9affa272c5d971f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "location":{
              "x":249,
              "y":170},
            "size":{
              "width":381,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94af7124ce04c5e847b2bf1bde809ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "location":{
                  "x":249,
                  "y":170},
                "size":{
                  "width":381,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u17.png"}},
{
          "id":"525755e3fe1f4e7e8d508d8392bc7f89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":140,
              "y":330},
            "size":{
              "width":145,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14999abc00c84ee0bc27e525de0f8373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":330},
                "size":{
                  "width":145,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aea9c862a9e4146a32316e61747e2c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":764},
            "size":{
              "width":1200,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ecf0f8808bf48c798c16c97d6c67849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":764},
                "size":{
                  "width":1200,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u4.png"}},
{
          "id":"b96d217b37014559a3519b52533fdd4f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":135,
              "y":780},
            "size":{
              "width":145,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ae722a6ac0c4e05999ca05cf52613d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":135,
                  "y":780},
                "size":{
                  "width":145,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"a1d83b88353e493697aa21c2f1086a84",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":176},
            "size":{
              "width":200,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e426a2ff65424b959970e4635f17acba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"acb390c0c759477fa502dcb3861e4802",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"6c30a1c17dfd494fba8b6401f106761c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d19569978f2f4aeaa05da1b9c015bbc6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"9f9c8c3efc714f82bd7a0ad6d92dce8c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"952ddb6f84fc4fd9bbde44867be00a6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"d74a2bdf4acc4c5182eac3d87e94b80c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d510c9eef9ad48148eedb77a35ffd52b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"ed0ceb559aa14e27af574a010c075059",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a46c6c2d6a8449b7864db05e70acef53",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}},
{
              "id":"ae4ec7721d9f4677949ea9f1807a637c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d10491118a3b4658b48e6310b7019e58",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人首页-无图片/u26.png"}}]},
{
          "id":"9a08cefbc0a64af6bcd05bb506bb40b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF7DB500},
            "location":{
              "x":950,
              "y":136},
            "size":{
              "width":70,
              "height":30},
            "borderWidth":"-1",
            "linePattern":"none",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76685cd092f74e7ba4a7afdf46265d76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7DB500},
                "location":{
                  "x":950,
                  "y":136},
                "size":{
                  "width":70,
                  "height":30},
                "borderWidth":"-1",
                "linePattern":"none",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人首页-无图片/u38.png"}},
{
          "id":"24c28051ff8041c8bdaaf4fc7746600b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":1090,
              "y":242},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"328568580a67482183396e44fda17eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":1090,
                  "y":242},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 尺寸配置",
                      "target":{
                        "targetType":"page",
                        "url":"尺寸配置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cf0992713204839a387f30db6340f01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":306,
              "y":780},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60f47c9fa40b4ae5a0edf2f72fb2b02f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":780},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"151dd644d22c4df7b4830b94b923af15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":383,
              "y":780},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50f89b9e5ab74c599e56c38b99c9b342",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":383,
                  "y":780},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fa949df3d404fbbaec70025db1db34b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":433,
              "y":780},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a9ac0354d204666a89faf705220813e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":433,
                  "y":780},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7df393e0b1a4a619716c36dd6d083e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "location":{
              "x":91,
              "y":62},
            "size":{
              "width":1198,
              "height":750},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"091c511b298a43fdb363a0e62b6654fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "location":{
                  "x":91,
                  "y":62},
                "size":{
                  "width":1198,
                  "height":750},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尺寸配置/u48.png"}},
{
          "id":"3bef064f49934519ad674a047a74e4b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":270},
            "size":{
              "width":657,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0df30f3f50c4450ac1ae80d0d75bb73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":270},
                "size":{
                  "width":657,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u50.png"}},
{
          "id":"70403aebb7414ed995ccc4ad6881db6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":380,
              "y":283},
            "size":{
              "width":80,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16620477fbe64b1587571ba59c6c24d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":380,
                  "y":283},
                "size":{
                  "width":80,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7ef49857a1b473099d90fffee2f5be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":365,
              "y":315},
            "size":{
              "width":319,
              "height":234},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98ba5b658b5f4edab97e4b8e70accc61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":365,
                  "y":315},
                "size":{
                  "width":319,
                  "height":234},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u54.png"}},
{
          "id":"c0c831189f604d4396ca9dc2f2c8ac5b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":322},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c76769232ab470182f2a8f570a27d6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":322},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u56.png"}},
{
          "id":"8d03fa8540414c42b310154549f51d6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":322},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"155172ba67624ed6afeda0f62d88b0ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":485,
                  "y":322},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u56.png"}},
{
          "id":"c101e9eb143a4da585608e6961a3a54b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":310},
            "size":{
              "width":655,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/正在上传/u60_line.png"}},
{
          "id":"29cb82a2a22e4bc29d77e0332ea55cee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":990,
              "y":280},
            "size":{
              "width":16,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65327909f2ea4faa97ab4019d0677f1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":990,
                  "y":280},
                "size":{
                  "width":16,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 图片列表",
                      "target":{
                        "targetType":"page",
                        "url":"图片列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5dec6027a654a9c9b578feed2ac277c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":405},
            "size":{
              "width":10,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF00FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/正在上传/u63_line.png"}},
{
          "id":"9dec139b2833428283af7b78ca22a585",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF00FF},
            "location":{
              "x":388,
              "y":405},
            "size":{
              "width":9,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF00FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bab1ae2cebd343b5b2e295fb60e741d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF00FF},
                "location":{
                  "x":388,
                  "y":405},
                "size":{
                  "width":9,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF00FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u64.png"}},
{
          "id":"b4cd46203dd34d05b0b443d0c46851c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":376,
              "y":451},
            "size":{
              "width":125,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed6f456ee2ce479084d177809bb6e9a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":376,
                  "y":451},
                "size":{
                  "width":125,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u66.png"}},
{
          "id":"f9f3bb47020c430f8adbe0ce6040b4a8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":709,
              "y":322},
            "size":{
              "width":281,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"c8b27e364312471fa6bfb7edd95b1dd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":322},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bb179e3ae234c2db75a107b829ba8e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":322},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u56.png"}},
{
          "id":"98d2204cfcbc4396b2d4040b5fa5c29b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue LT Pro 75 Bold', 'Helvetica Neue LT Pro'",
            "fontSize":"24px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x1CFFFFFF},
            "textShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.619607843137255}},
            "location":{
              "x":380,
              "y":322},
            "size":{
              "width":80,
              "height":80},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65b25e441bef43b0910177ec23f3a0fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue LT Pro 75 Bold', 'Helvetica Neue LT Pro'",
                "fontSize":"24px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x1CFFFFFF},
                "textShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.619607843137255}},
                "location":{
                  "x":380,
                  "y":322},
                "size":{
                  "width":80,
                  "height":80},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u71.png"}},
{
          "id":"ae6987d2ed0e4ce9b59d4d84554a7ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue LT Pro 75 Bold', 'Helvetica Neue LT Pro'",
            "fontSize":"24px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "textShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.619607843137255}},
            "location":{
              "x":485,
              "y":322},
            "size":{
              "width":80,
              "height":80},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9f230795a47423badf987e180ba3f1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue LT Pro 75 Bold', 'Helvetica Neue LT Pro'",
                "fontSize":"24px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "textShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.619607843137255}},
                "location":{
                  "x":485,
                  "y":322},
                "size":{
                  "width":80,
                  "height":80},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb20bc6d5ba1491e884649d87d978f61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue LT Pro 75 Bold', 'Helvetica Neue LT Pro'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x9BFFFFFF},
            "textShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.619607843137255}},
            "location":{
              "x":590,
              "y":322},
            "size":{
              "width":80,
              "height":80},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e90f7a8f34042c297e32e0266efba1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue LT Pro 75 Bold', 'Helvetica Neue LT Pro'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x9BFFFFFF},
                "textShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.619607843137255}},
                "location":{
                  "x":590,
                  "y":322},
                "size":{
                  "width":80,
                  "height":80},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u75.png"}},
{
          "id":"137fbf6b2f6f436487b10a5fe8e8858b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue LT Pro 75 Bold', 'Helvetica Neue LT Pro'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x9BFFFFFF},
            "textShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.619607843137255}},
            "location":{
              "x":525,
              "y":322},
            "size":{
              "width":40,
              "height":80},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d19a32a7e1644f697cb0af12c525260",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue LT Pro 75 Bold', 'Helvetica Neue LT Pro'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x9BFFFFFF},
                "textShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.619607843137255}},
                "location":{
                  "x":525,
                  "y":322},
                "size":{
                  "width":40,
                  "height":80},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u77.png"}},
{
          "id":"f450efdc84af4823b94a5e6d65d52f46",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":736,
              "y":454},
            "size":{
              "width":10,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF00FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/正在上传/u63_line.png"}},
{
          "id":"7bdc1065ed01435a99bd5d53087a8de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF00FF},
            "location":{
              "x":737,
              "y":454},
            "size":{
              "width":9,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF00FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a50b0b930f304aacb8f0cc213f51c9d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF00FF},
                "location":{
                  "x":737,
                  "y":454},
                "size":{
                  "width":9,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF00FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u64.png"}},
{
          "id":"8d8babf090744eecbec60b019d3f10e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":725,
              "y":500},
            "size":{
              "width":235,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e38db62f75f14b7a912f53d82b44aa10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":725,
                  "y":500},
                "size":{
                  "width":235,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正在上传/u82.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4ec02afa039541288d801c11b43aa3f8":{
      "scriptId":"u0"},
    "e37f394efd5b4c5ca7c2b817a2e3ecdd":{
      "scriptId":"u1"},
    "4c192aabf9c14ec19f2361b0f9b79e86":{
      "scriptId":"u2"},
    "ab340035a1ec4d61bdb60f9b254ca073":{
      "scriptId":"u3"},
    "24bdfc60a66b4c77aee37eb987126148":{
      "scriptId":"u4"},
    "3d7d503599954cccaa5e9f70bda41339":{
      "scriptId":"u5"},
    "8181b41e693e4a7a9be3d263e8824442":{
      "scriptId":"u6"},
    "eb3238dd2a964d1e8fd9392c52ddeba5":{
      "scriptId":"u7"},
    "b1b73bd3e9eb473bac8a3ce5ea4278d5":{
      "scriptId":"u8"},
    "94bf56affe7548e1b4737aebe7d79ce3":{
      "scriptId":"u9"},
    "5e36f47f5aa2433b8d3614219cb41e10":{
      "scriptId":"u10"},
    "7d700674ef50454180603ef1a3e0a1ee":{
      "scriptId":"u11"},
    "2be55fe3cf024d3a8e37c2a6663b8465":{
      "scriptId":"u12"},
    "c04945ff276743eea7732541af5cc7b5":{
      "scriptId":"u13"},
    "2854aeba85cd4a469f9f653ac3bbbf02":{
      "scriptId":"u14"},
    "df01038637d94d6f8a715594368ca77e":{
      "scriptId":"u15"},
    "d11fc9fb2eb749618db258771fb62521":{
      "scriptId":"u16"},
    "ff0195648cbf4ee9affa272c5d971f0f":{
      "scriptId":"u17"},
    "f94af7124ce04c5e847b2bf1bde809ce":{
      "scriptId":"u18"},
    "525755e3fe1f4e7e8d508d8392bc7f89":{
      "scriptId":"u19"},
    "14999abc00c84ee0bc27e525de0f8373":{
      "scriptId":"u20"},
    "9aea9c862a9e4146a32316e61747e2c3":{
      "scriptId":"u21"},
    "9ecf0f8808bf48c798c16c97d6c67849":{
      "scriptId":"u22"},
    "b96d217b37014559a3519b52533fdd4f":{
      "scriptId":"u23"},
    "7ae722a6ac0c4e05999ca05cf52613d6":{
      "scriptId":"u24"},
    "a1d83b88353e493697aa21c2f1086a84":{
      "scriptId":"u25"},
    "e426a2ff65424b959970e4635f17acba":{
      "scriptId":"u26"},
    "acb390c0c759477fa502dcb3861e4802":{
      "scriptId":"u27"},
    "d74a2bdf4acc4c5182eac3d87e94b80c":{
      "scriptId":"u28"},
    "d510c9eef9ad48148eedb77a35ffd52b":{
      "scriptId":"u29"},
    "6c30a1c17dfd494fba8b6401f106761c":{
      "scriptId":"u30"},
    "d19569978f2f4aeaa05da1b9c015bbc6":{
      "scriptId":"u31"},
    "ed0ceb559aa14e27af574a010c075059":{
      "scriptId":"u32"},
    "a46c6c2d6a8449b7864db05e70acef53":{
      "scriptId":"u33"},
    "9f9c8c3efc714f82bd7a0ad6d92dce8c":{
      "scriptId":"u34"},
    "952ddb6f84fc4fd9bbde44867be00a6f":{
      "scriptId":"u35"},
    "ae4ec7721d9f4677949ea9f1807a637c":{
      "scriptId":"u36"},
    "d10491118a3b4658b48e6310b7019e58":{
      "scriptId":"u37"},
    "9a08cefbc0a64af6bcd05bb506bb40b7":{
      "scriptId":"u38"},
    "76685cd092f74e7ba4a7afdf46265d76":{
      "scriptId":"u39"},
    "24c28051ff8041c8bdaaf4fc7746600b":{
      "scriptId":"u40"},
    "328568580a67482183396e44fda17eb2":{
      "scriptId":"u41"},
    "1cf0992713204839a387f30db6340f01":{
      "scriptId":"u42"},
    "60f47c9fa40b4ae5a0edf2f72fb2b02f":{
      "scriptId":"u43"},
    "151dd644d22c4df7b4830b94b923af15":{
      "scriptId":"u44"},
    "50f89b9e5ab74c599e56c38b99c9b342":{
      "scriptId":"u45"},
    "7fa949df3d404fbbaec70025db1db34b":{
      "scriptId":"u46"},
    "2a9ac0354d204666a89faf705220813e":{
      "scriptId":"u47"},
    "b7df393e0b1a4a619716c36dd6d083e9":{
      "scriptId":"u48"},
    "091c511b298a43fdb363a0e62b6654fa":{
      "scriptId":"u49"},
    "3bef064f49934519ad674a047a74e4b1":{
      "scriptId":"u50"},
    "d0df30f3f50c4450ac1ae80d0d75bb73":{
      "scriptId":"u51"},
    "70403aebb7414ed995ccc4ad6881db6f":{
      "scriptId":"u52"},
    "16620477fbe64b1587571ba59c6c24d6":{
      "scriptId":"u53"},
    "a7ef49857a1b473099d90fffee2f5be3":{
      "scriptId":"u54"},
    "98ba5b658b5f4edab97e4b8e70accc61":{
      "scriptId":"u55"},
    "c0c831189f604d4396ca9dc2f2c8ac5b":{
      "scriptId":"u56"},
    "8c76769232ab470182f2a8f570a27d6d":{
      "scriptId":"u57"},
    "8d03fa8540414c42b310154549f51d6f":{
      "scriptId":"u58"},
    "155172ba67624ed6afeda0f62d88b0ad":{
      "scriptId":"u59"},
    "c101e9eb143a4da585608e6961a3a54b":{
      "scriptId":"u60"},
    "29cb82a2a22e4bc29d77e0332ea55cee":{
      "scriptId":"u61"},
    "65327909f2ea4faa97ab4019d0677f1e":{
      "scriptId":"u62"},
    "a5dec6027a654a9c9b578feed2ac277c":{
      "scriptId":"u63"},
    "9dec139b2833428283af7b78ca22a585":{
      "scriptId":"u64"},
    "bab1ae2cebd343b5b2e295fb60e741d0":{
      "scriptId":"u65"},
    "b4cd46203dd34d05b0b443d0c46851c8":{
      "scriptId":"u66"},
    "ed6f456ee2ce479084d177809bb6e9a4":{
      "scriptId":"u67"},
    "f9f3bb47020c430f8adbe0ce6040b4a8":{
      "scriptId":"u68"},
    "c8b27e364312471fa6bfb7edd95b1dd9":{
      "scriptId":"u69"},
    "6bb179e3ae234c2db75a107b829ba8e8":{
      "scriptId":"u70"},
    "98d2204cfcbc4396b2d4040b5fa5c29b":{
      "scriptId":"u71"},
    "65b25e441bef43b0910177ec23f3a0fc":{
      "scriptId":"u72"},
    "ae6987d2ed0e4ce9b59d4d84554a7ab1":{
      "scriptId":"u73"},
    "f9f230795a47423badf987e180ba3f1c":{
      "scriptId":"u74"},
    "fb20bc6d5ba1491e884649d87d978f61":{
      "scriptId":"u75"},
    "4e90f7a8f34042c297e32e0266efba1c":{
      "scriptId":"u76"},
    "137fbf6b2f6f436487b10a5fe8e8858b":{
      "scriptId":"u77"},
    "2d19a32a7e1644f697cb0af12c525260":{
      "scriptId":"u78"},
    "f450efdc84af4823b94a5e6d65d52f46":{
      "scriptId":"u79"},
    "7bdc1065ed01435a99bd5d53087a8de0":{
      "scriptId":"u80"},
    "a50b0b930f304aacb8f0cc213f51c9d1":{
      "scriptId":"u81"},
    "8d8babf090744eecbec60b019d3f10e7":{
      "scriptId":"u82"},
    "e38db62f75f14b7a912f53d82b44aa10":{
      "scriptId":"u83"}}});