$axure.loadCurrentPage({
  "url":"publish.html",
  "generationDate":new Date(1433109084777.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6715988a4f854f94a92204c51f5470f5",
    "type":"Axure:Page",
    "name":"publish",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"182a76e715224b1fa2460fd8da6e16c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":150},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4eb4727ffcf4622899ed108f7ac5716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":150},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/show/u0.png"}},
{
          "id":"d399808164014bfe95e065ac8e3c5be7",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":268},
            "size":{
              "width":320,
              "height":570}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"786d11ff28d8407580a9132bcc91c5c0",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3bd43d0f4a4549e3a57942a77335a760",
                  "label":"",
                  "parentDynamicPanel":"d399808164014bfe95e065ac8e3c5be7",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":62,
                      "y":18},
                    "size":{
                      "width":193,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"974262ab605b43dc99a9940233e48206",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d399808164014bfe95e065ac8e3c5be7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"24px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":62,
                          "y":18},
                        "size":{
                          "width":193,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bba6faea925d493aad508f7619bf79cb",
                  "label":"",
                  "parentDynamicPanel":"d399808164014bfe95e065ac8e3c5be7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":19,
                      "y":72},
                    "size":{
                      "width":280,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac10d4a48f9942168d7b845d3fa528a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d399808164014bfe95e065ac8e3c5be7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":19,
                          "y":72},
                        "size":{
                          "width":280,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8bf998b7e5e54a2e801e47d9af7d8ba7",
                  "label":"",
                  "parentDynamicPanel":"d399808164014bfe95e065ac8e3c5be7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":346},
                    "size":{
                      "width":280,
                      "height":187},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe53e72b31fb45b98cbfbfa378c2ff97",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d399808164014bfe95e065ac8e3c5be7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":346},
                        "size":{
                          "width":280,
                          "height":187},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/add_new_-_template/u61.png"}},
{
                  "id":"b0f2a4a707174a199dec8fe1088506f5",
                  "label":"",
                  "parentDynamicPanel":"d399808164014bfe95e065ac8e3c5be7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":19,
                      "y":556},
                    "size":{
                      "width":280,
                      "height":231}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"558d1af1aae245b4b3bf2f645de75186",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d399808164014bfe95e065ac8e3c5be7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":19,
                          "y":556},
                        "size":{
                          "width":280,
                          "height":231}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"cf6807223ee94bc78c0d064c497a6015",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":101},
            "size":{
              "width":1400,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/my_story_-_newcomer/u14_line.png"}},
{
          "id":"355ff04ea1cc46f7996673b86e31cd35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":90,
              "y":69},
            "size":{
              "width":190,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"202ca58c8f3f4012b11be8d403e60f44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":90,
                  "y":69},
                "size":{
                  "width":190,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Add new - template",
                      "target":{
                        "targetType":"page",
                        "url":"add_new_-_template.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/add_new_-_template/u5.png"}},
{
          "id":"ab5cfd457df94bbd8c0c8935d6dca01b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":280,
              "y":69},
            "size":{
              "width":190,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51ca903cd9d2492ca972c00cc3250ea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":280,
                  "y":69},
                "size":{
                  "width":190,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 edit",
                      "target":{
                        "targetType":"page",
                        "url":"edit.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/add_new_-_template/u5.png"}},
{
          "id":"61709ae0c3534f5397a3dc4312d6d30f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":470,
              "y":69},
            "size":{
              "width":190,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3912c1012374ffd979883cec158cbce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":470,
                  "y":69},
                "size":{
                  "width":190,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 preview",
                      "target":{
                        "targetType":"page",
                        "url":"preview.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/add_new_-_template/u5.png"}},
{
          "id":"7d8456fdc04e4ec29b26d82a8c137ece",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":660,
              "y":66},
            "size":{
              "width":190,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08ad28bd37094676b15708298a3f7148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":660,
                  "y":66},
                "size":{
                  "width":190,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/add_new_-_template/u3.png"}},
{
          "id":"53e2fc04df90424d9e8ccabfb6f11d0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":867,
              "y":356},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52042d275a554162911d9615b39dea19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":867,
                  "y":356},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/my_story_-_newcomer/qr_u42.png"}},
{
          "id":"f66ceade9f954d8c9f2abde78c707549",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":611},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19c762ce6aee4fd8a1393aaa08dd8177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":611},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/show/u9.png"}},
{
          "id":"c84cc2c38fe34a8c96c24391f12bf4f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":914,
              "y":611},
            "size":{
              "width":42,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0853b937aa6845ba909d5bba228473c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":914,
                  "y":611},
                "size":{
                  "width":42,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/show/u11.png"}},
{
          "id":"5bac5b9b460647c190accef67ddd07b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":611},
            "size":{
              "width":41,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ece854157a342c6abf8ae7c6b7286c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":611},
                "size":{
                  "width":41,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/show/u13.png"}},
{
          "id":"77ad6270476944058e122dad65e1684b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1042,
              "y":611},
            "size":{
              "width":41,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0735e6b2b5c54662a5f56fc99cdb80d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1042,
                  "y":611},
                "size":{
                  "width":41,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/show/u15.png"}},
{
          "id":"bee7a2b62fd947d3afca9e9cf5fe8470",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":860,
              "y":655},
            "size":{
              "width":25,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c85f60b9e5248efa5cccd6f7c7695fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":860,
                  "y":655},
                "size":{
                  "width":25,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5aea0644c28471bbdbd6f17b649f4b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":912,
              "y":655},
            "size":{
              "width":49,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a241de8c79ec4205954c892634114f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":912,
                  "y":655},
                "size":{
                  "width":49,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d1a8bc060364a0b962fe28a3642d980",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":982,
              "y":655},
            "size":{
              "width":37,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32b52cf9d3974493b660e2f20bbdb30e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":982,
                  "y":655},
                "size":{
                  "width":37,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bf6f55885b7465193894432e537b21b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":1052,
              "y":655},
            "size":{
              "width":21,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"699ffab10109410fb66bb0d2e724e3ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":1052,
                  "y":655},
                "size":{
                  "width":21,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22ffa70aed0c4abab7e9e3682e11f6fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":852,
              "y":574},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"364d1a2f93684872af89b6deb2dce4d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":852,
                  "y":574},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6056f1e7fa36439d8d9e02f395c511e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"28px",
            "location":{
              "x":838,
              "y":301},
            "size":{
              "width":257,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56832d88fd084fe485cf24a30c12d6dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"28px",
                "location":{
                  "x":838,
                  "y":301},
                "size":{
                  "width":257,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08571ffe551c41d99864619ba72cb0ca",
          "label":"遮罩",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x4C000000},
            "location":{
              "x":90,
              "y":50},
            "size":{
              "width":1400,
              "height":920},
            "visible":false,
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55952cf24bbd423d996f3e82365bc251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x4C000000},
                "location":{
                  "x":90,
                  "y":50},
                "size":{
                  "width":1400,
                  "height":920},
                "visible":false,
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/my_story_-_newcomer/遮罩_u104.png"}},
{
          "id":"a1ac9a4802aa41c68076b7fb71d0c767",
          "label":"意见反馈",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":531.5,
              "y":254},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1<br> (If state of 意见反馈 等于 提交成功)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["a1ac9a4802aa41c68076b7fb71d0c767"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["a1ac9a4802aa41c68076b7fb71d0c767"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"wait",
                      "description":"等待1500毫秒",
                      "waitTime":1500},
{
                      "action":"fadeWidget",
                      "description":"隐藏 意见反馈",
                      "objectsToFades":[{
                          "objectPath":["a1ac9a4802aa41c68076b7fb71d0c767"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 遮罩",
                      "objectsToFades":[{
                          "objectPath":["08571ffe551c41d99864619ba72cb0ca"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"caa7445abebe47e181beb7a0126a4fb7",
              "label":"表单",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d8fb336ce7f64a028b4a1397c42cdf8d",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"top",
                    "location":{
                      "x":0,
                      "y":10},
                    "size":{
                      "width":510,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"462351f6055e4d9ba261ec58ccad4a59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"top",
                        "location":{
                          "x":0,
                          "y":10},
                        "size":{
                          "width":510,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/my_story_-_newcomer/u107.png"}},
{
                  "id":"db1cbdfa42094c53859f3003171a77a2",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "location":{
                      "x":34,
                      "y":73},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64a62abc1d9c4243bbd00ae45c210c8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "location":{
                          "x":34,
                          "y":73},
                        "size":{
                          "width":71,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ae9d24436ef14942a8268250e0689f34",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "location":{
                      "x":34,
                      "y":122},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11f4c290a65f4794a97568101d50204d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "location":{
                          "x":34,
                          "y":122},
                        "size":{
                          "width":71,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a8f797b3ea33437ebc17d19c42e40da6",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":122},
                    "size":{
                      "width":365,
                      "height":100}},
                  "adaptiveStyles":{
}},
{
                  "id":"349653f67ec74ff7ba5828362c84442a",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"bottom",
                    "location":{
                      "x":115,
                      "y":73},
                    "size":{
                      "width":95,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"519597a566674543a2d3835b40aadc91",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "verticalAlignment":"bottom",
                        "location":{
                          "x":115,
                          "y":73},
                        "size":{
                          "width":95,
                          "height":20}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"37407276ead447d9a1edcb496230d2f0",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"bottom",
                    "location":{
                      "x":225,
                      "y":73},
                    "size":{
                      "width":110,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"209fa904faee47fd8ff44fad0d908ca9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "verticalAlignment":"bottom",
                        "location":{
                          "x":225,
                          "y":73},
                        "size":{
                          "width":110,
                          "height":20}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"819265e8939242e281fc5f32677e1b20",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"bottom",
                    "location":{
                      "x":350,
                      "y":73},
                    "size":{
                      "width":110,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2deb16ebc30c4079b98b44723b1770da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "verticalAlignment":"bottom",
                        "location":{
                          "x":350,
                          "y":73},
                        "size":{
                          "width":110,
                          "height":20}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"eea53f0f2aa54acbbda93c5a05aa9234",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "location":{
                      "x":380,
                      "y":240},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 意见反馈 to 提交成功",
                              "panelsToStates":[{
                                  "panelPath":["a1ac9a4802aa41c68076b7fb71d0c767"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"setPanelOrder",
                              "description":"移动 意见反馈 到顶层 ",
                              "panelPaths":[{
                                  "panelPath":["a1ac9a4802aa41c68076b7fb71d0c767"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]}]}]}},
                  "tabbable":true},
{
                  "id":"e6e36778490742e39c8827ebb6c52b67",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":493,
                      "y":0},
                    "size":{
                      "width":24,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0c8be2273db414487bedb35f484243d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":493,
                          "y":0},
                        "size":{
                          "width":24,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 意见反馈",
                              "objectsToFades":[{
                                  "objectPath":["a1ac9a4802aa41c68076b7fb71d0c767"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 遮罩",
                              "objectsToFades":[{
                                  "objectPath":["08571ffe551c41d99864619ba72cb0ca"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/my_story_-_newcomer/u49.png"}}]},
{
              "id":"cce27744502748a4aa24f3c8f117a673",
              "label":"提交成功",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"38fd6d223b97401a9b8f707c50b7d5cb",
                  "label":"",
                  "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":113,
                      "y":102},
                    "size":{
                      "width":304,
                      "height":70},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71a9819c086a49339a8c2def97ea94c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1ac9a4802aa41c68076b7fb71d0c767",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"18px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":113,
                          "y":102},
                        "size":{
                          "width":304,
                          "height":70},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/my_story_-_newcomer/u123.png"}}]}]},
{
          "id":"2456d05b08634814a8bfe0a67094e0b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCFF},
            "location":{
              "x":1460,
              "y":560},
            "size":{
              "width":30,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29610c449f2049aab41454f442c71a30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":1460,
                  "y":560},
                "size":{
                  "width":30,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 意见反馈",
                      "objectsToFades":[{
                          "objectPath":["a1ac9a4802aa41c68076b7fb71d0c767"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 意见反馈 to 表单",
                      "panelsToStates":[{
                          "panelPath":["a1ac9a4802aa41c68076b7fb71d0c767"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 遮罩",
                      "objectsToFades":[{
                          "objectPath":["08571ffe551c41d99864619ba72cb0ca"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/my_story_-_newcomer/u125.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "182a76e715224b1fa2460fd8da6e16c3":{
      "scriptId":"u0"},
    "b4eb4727ffcf4622899ed108f7ac5716":{
      "scriptId":"u1"},
    "d399808164014bfe95e065ac8e3c5be7":{
      "scriptId":"u2"},
    "3bd43d0f4a4549e3a57942a77335a760":{
      "scriptId":"u3"},
    "974262ab605b43dc99a9940233e48206":{
      "scriptId":"u4"},
    "bba6faea925d493aad508f7619bf79cb":{
      "scriptId":"u5"},
    "ac10d4a48f9942168d7b845d3fa528a9":{
      "scriptId":"u6"},
    "8bf998b7e5e54a2e801e47d9af7d8ba7":{
      "scriptId":"u7"},
    "fe53e72b31fb45b98cbfbfa378c2ff97":{
      "scriptId":"u8"},
    "b0f2a4a707174a199dec8fe1088506f5":{
      "scriptId":"u9"},
    "558d1af1aae245b4b3bf2f645de75186":{
      "scriptId":"u10"},
    "cf6807223ee94bc78c0d064c497a6015":{
      "scriptId":"u11"},
    "355ff04ea1cc46f7996673b86e31cd35":{
      "scriptId":"u12"},
    "202ca58c8f3f4012b11be8d403e60f44":{
      "scriptId":"u13"},
    "ab5cfd457df94bbd8c0c8935d6dca01b":{
      "scriptId":"u14"},
    "51ca903cd9d2492ca972c00cc3250ea3":{
      "scriptId":"u15"},
    "61709ae0c3534f5397a3dc4312d6d30f":{
      "scriptId":"u16"},
    "d3912c1012374ffd979883cec158cbce":{
      "scriptId":"u17"},
    "7d8456fdc04e4ec29b26d82a8c137ece":{
      "scriptId":"u18"},
    "08ad28bd37094676b15708298a3f7148":{
      "scriptId":"u19"},
    "53e2fc04df90424d9e8ccabfb6f11d0f":{
      "scriptId":"u20"},
    "52042d275a554162911d9615b39dea19":{
      "scriptId":"u21"},
    "f66ceade9f954d8c9f2abde78c707549":{
      "scriptId":"u22"},
    "19c762ce6aee4fd8a1393aaa08dd8177":{
      "scriptId":"u23"},
    "c84cc2c38fe34a8c96c24391f12bf4f0":{
      "scriptId":"u24"},
    "0853b937aa6845ba909d5bba228473c2":{
      "scriptId":"u25"},
    "5bac5b9b460647c190accef67ddd07b7":{
      "scriptId":"u26"},
    "9ece854157a342c6abf8ae7c6b7286c0":{
      "scriptId":"u27"},
    "77ad6270476944058e122dad65e1684b":{
      "scriptId":"u28"},
    "0735e6b2b5c54662a5f56fc99cdb80d6":{
      "scriptId":"u29"},
    "bee7a2b62fd947d3afca9e9cf5fe8470":{
      "scriptId":"u30"},
    "7c85f60b9e5248efa5cccd6f7c7695fc":{
      "scriptId":"u31"},
    "c5aea0644c28471bbdbd6f17b649f4b5":{
      "scriptId":"u32"},
    "a241de8c79ec4205954c892634114f21":{
      "scriptId":"u33"},
    "0d1a8bc060364a0b962fe28a3642d980":{
      "scriptId":"u34"},
    "32b52cf9d3974493b660e2f20bbdb30e":{
      "scriptId":"u35"},
    "6bf6f55885b7465193894432e537b21b":{
      "scriptId":"u36"},
    "699ffab10109410fb66bb0d2e724e3ac":{
      "scriptId":"u37"},
    "22ffa70aed0c4abab7e9e3682e11f6fd":{
      "scriptId":"u38"},
    "364d1a2f93684872af89b6deb2dce4d4":{
      "scriptId":"u39"},
    "6056f1e7fa36439d8d9e02f395c511e4":{
      "scriptId":"u40"},
    "56832d88fd084fe485cf24a30c12d6dc":{
      "scriptId":"u41"},
    "08571ffe551c41d99864619ba72cb0ca":{
      "scriptId":"u42"},
    "55952cf24bbd423d996f3e82365bc251":{
      "scriptId":"u43"},
    "a1ac9a4802aa41c68076b7fb71d0c767":{
      "scriptId":"u44"},
    "d8fb336ce7f64a028b4a1397c42cdf8d":{
      "scriptId":"u45"},
    "462351f6055e4d9ba261ec58ccad4a59":{
      "scriptId":"u46"},
    "db1cbdfa42094c53859f3003171a77a2":{
      "scriptId":"u47"},
    "64a62abc1d9c4243bbd00ae45c210c8f":{
      "scriptId":"u48"},
    "ae9d24436ef14942a8268250e0689f34":{
      "scriptId":"u49"},
    "11f4c290a65f4794a97568101d50204d":{
      "scriptId":"u50"},
    "a8f797b3ea33437ebc17d19c42e40da6":{
      "scriptId":"u51"},
    "349653f67ec74ff7ba5828362c84442a":{
      "scriptId":"u52"},
    "519597a566674543a2d3835b40aadc91":{
      "scriptId":"u53"},
    "37407276ead447d9a1edcb496230d2f0":{
      "scriptId":"u54"},
    "209fa904faee47fd8ff44fad0d908ca9":{
      "scriptId":"u55"},
    "819265e8939242e281fc5f32677e1b20":{
      "scriptId":"u56"},
    "2deb16ebc30c4079b98b44723b1770da":{
      "scriptId":"u57"},
    "eea53f0f2aa54acbbda93c5a05aa9234":{
      "scriptId":"u58"},
    "e6e36778490742e39c8827ebb6c52b67":{
      "scriptId":"u59"},
    "d0c8be2273db414487bedb35f484243d":{
      "scriptId":"u60"},
    "38fd6d223b97401a9b8f707c50b7d5cb":{
      "scriptId":"u61"},
    "71a9819c086a49339a8c2def97ea94c0":{
      "scriptId":"u62"},
    "2456d05b08634814a8bfe0a67094e0b3":{
      "scriptId":"u63"},
    "29610c449f2049aab41454f442c71a30":{
      "scriptId":"u64"}}});