$axure.loadCurrentPage({
  "url":"【另一种导航条】.html",
  "generationDate":new Date(1446546663535.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"582d4367b19e4d23915002cbbd7ca656",
    "type":"Axure:Page",
    "name":"【另一种导航条】",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"418ee9d286554c4c957de8fd8ffcdbad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":81},
            "size":{
              "width":1342,
              "height":40},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1da4febeb9794190a16223cc6efec9c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":81},
                "size":{
                  "width":1342,
                  "height":40},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_未登录/u2.png"}},
{
          "id":"d548812edc2f414eaa64482b20c88914",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":233,
              "y":90},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b02802d97c46669c1d1feb895927ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":233,
                  "y":90},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aacc73dfcde948e587b5c8140590cf63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":82},
            "size":{
              "width":175,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e79735d7b2f84138b0fb93a8a9df9d80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":82},
                "size":{
                  "width":175,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d805dfd2f8f24a9aa3bc8ed81232019c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":337},
            "size":{
              "width":1342,
              "height":40},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2053992ea7a0452c8ca0a8de280107e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":337},
                "size":{
                  "width":1342,
                  "height":40},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_未登录/u2.png"}},
{
          "id":"49d57c58868749d4869843f18b5299fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":233,
              "y":346},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e983a720c13b4eeeac9bde47fadf14b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":233,
                  "y":346},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d7e1018933b4ec2bb91f821625640e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":325,
              "y":346},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec73eaddc3b4ff2abf48cc9a5f7e8e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":325,
                  "y":346},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4504defac06d4422b6395d015b2e62fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":418,
              "y":346},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"693b7ad742c147cd8b5399081d777db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":418,
                  "y":346},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61360cb60cb64fa4ae39bede1683f26b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":510,
              "y":346},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3859b8c0b0e24fc5b03d63688d2ed0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":510,
                  "y":346},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcf106167f6947228335bbcb13dd08e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":603,
              "y":346},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9d76b7698454f5fb9e9b2b10e6dd0cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":603,
                  "y":346},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"723f7aaad5cf43baadd0b18a686fddaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":338},
            "size":{
              "width":175,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8c13d771874a2dbfdc813becb7e3bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":338},
                "size":{
                  "width":175,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2215910bea344b9a8d59883da2ac7dc0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":718,
              "y":342},
            "size":{
              "width":322,
              "height":31}},
          "adaptiveStyles":{
}},
{
          "id":"e36a25bb7036470f905499cda6401730",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":981,
              "y":342},
            "size":{
              "width":58,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"578608524c1f4902a2b65fc7e59cc368",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "verticalAlignment":"top",
            "lineSpacing":"40px",
            "paddingTop":"5",
            "location":{
              "x":1185,
              "y":375},
            "size":{
              "width":145,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79cb8f853281488cac48d7985028884d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "verticalAlignment":"top",
                "lineSpacing":"40px",
                "paddingTop":"5",
                "location":{
                  "x":1185,
                  "y":375},
                "size":{
                  "width":145,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_已登录/u23.png"}},
{
          "id":"81ce2da60f2e40aab8236761d2a11ef0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":1185,
              "y":336},
            "size":{
              "width":145,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0efc7fcb582c4f848509834da1eb8f54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":1185,
                  "y":336},
                "size":{
                  "width":145,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_已登录/u25.png"}},
{
          "id":"1ba8dce0933a47939e94c23ee2278ff5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1211,
              "y":344},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"180fb432ab4b4f78aeaf4dae689c8828",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1211,
                  "y":344},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_已登录/u19.png"}},
{
          "id":"b1df32800a6e4af88aca82437c7a2b9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1294,
              "y":393},
            "size":{
              "width":20,
              "height":14},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c5dcd9ec40e4e9aa1da215ff734ecbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1294,
                  "y":393},
                "size":{
                  "width":20,
                  "height":14},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_已登录/u30.png"}},
{
          "id":"b39b6e3d607e4c71b57569fad9fd6814",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"5",
            "location":{
              "x":1050,
              "y":119},
            "size":{
              "width":280,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"337f39b57a2a4911a78d3b3956adc57d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"5",
                "location":{
                  "x":1050,
                  "y":119},
                "size":{
                  "width":280,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_未登录/u11.png"}},
{
          "id":"c84f5242f57440a180789681ad250330",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":1215,
              "y":80},
            "size":{
              "width":115,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a81fc0259e475e9655c90abf5fb42c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":1215,
                  "y":80},
                "size":{
                  "width":115,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_-_未登录/u13.png"}},
{
          "id":"e89fb5f4638d43c8bb4539ad6f5c6049",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":143},
            "size":{
              "width":192,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bae949d849f444a69dc140fec5a89138",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":194},
            "size":{
              "width":192,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"097758c54afb471ba7c284de8a16bc29",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1230,
              "y":243},
            "size":{
              "width":82,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f22136bf0c064475b9c57af70735986c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1138,
              "y":243},
            "size":{
              "width":82,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e2ee2c6018ef4998874e0048606ed71f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":719,
              "y":86},
            "size":{
              "width":321,
              "height":31}},
          "adaptiveStyles":{
}},
{
          "id":"c37408484a41437d96187859f2fc3f09",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":981,
              "y":86},
            "size":{
              "width":58,
              "height":30}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "418ee9d286554c4c957de8fd8ffcdbad":{
      "scriptId":"u0"},
    "1da4febeb9794190a16223cc6efec9c5":{
      "scriptId":"u1"},
    "d548812edc2f414eaa64482b20c88914":{
      "scriptId":"u2"},
    "a7b02802d97c46669c1d1feb895927ac":{
      "scriptId":"u3"},
    "aacc73dfcde948e587b5c8140590cf63":{
      "scriptId":"u4"},
    "e79735d7b2f84138b0fb93a8a9df9d80":{
      "scriptId":"u5"},
    "d805dfd2f8f24a9aa3bc8ed81232019c":{
      "scriptId":"u6"},
    "2053992ea7a0452c8ca0a8de280107e6":{
      "scriptId":"u7"},
    "49d57c58868749d4869843f18b5299fe":{
      "scriptId":"u8"},
    "e983a720c13b4eeeac9bde47fadf14b2":{
      "scriptId":"u9"},
    "8d7e1018933b4ec2bb91f821625640e9":{
      "scriptId":"u10"},
    "0ec73eaddc3b4ff2abf48cc9a5f7e8e1":{
      "scriptId":"u11"},
    "4504defac06d4422b6395d015b2e62fa":{
      "scriptId":"u12"},
    "693b7ad742c147cd8b5399081d777db8":{
      "scriptId":"u13"},
    "61360cb60cb64fa4ae39bede1683f26b":{
      "scriptId":"u14"},
    "3859b8c0b0e24fc5b03d63688d2ed0ec":{
      "scriptId":"u15"},
    "dcf106167f6947228335bbcb13dd08e1":{
      "scriptId":"u16"},
    "e9d76b7698454f5fb9e9b2b10e6dd0cd":{
      "scriptId":"u17"},
    "723f7aaad5cf43baadd0b18a686fddaa":{
      "scriptId":"u18"},
    "dd8c13d771874a2dbfdc813becb7e3bf":{
      "scriptId":"u19"},
    "2215910bea344b9a8d59883da2ac7dc0":{
      "scriptId":"u20"},
    "e36a25bb7036470f905499cda6401730":{
      "scriptId":"u21"},
    "578608524c1f4902a2b65fc7e59cc368":{
      "scriptId":"u22"},
    "79cb8f853281488cac48d7985028884d":{
      "scriptId":"u23"},
    "81ce2da60f2e40aab8236761d2a11ef0":{
      "scriptId":"u24"},
    "0efc7fcb582c4f848509834da1eb8f54":{
      "scriptId":"u25"},
    "1ba8dce0933a47939e94c23ee2278ff5":{
      "scriptId":"u26"},
    "180fb432ab4b4f78aeaf4dae689c8828":{
      "scriptId":"u27"},
    "b1df32800a6e4af88aca82437c7a2b9f":{
      "scriptId":"u28"},
    "0c5dcd9ec40e4e9aa1da215ff734ecbb":{
      "scriptId":"u29"},
    "b39b6e3d607e4c71b57569fad9fd6814":{
      "scriptId":"u30"},
    "337f39b57a2a4911a78d3b3956adc57d":{
      "scriptId":"u31"},
    "c84f5242f57440a180789681ad250330":{
      "scriptId":"u32"},
    "b5a81fc0259e475e9655c90abf5fb42c":{
      "scriptId":"u33"},
    "e89fb5f4638d43c8bb4539ad6f5c6049":{
      "scriptId":"u34"},
    "bae949d849f444a69dc140fec5a89138":{
      "scriptId":"u35"},
    "097758c54afb471ba7c284de8a16bc29":{
      "scriptId":"u36"},
    "f22136bf0c064475b9c57af70735986c":{
      "scriptId":"u37"},
    "e2ee2c6018ef4998874e0048606ed71f":{
      "scriptId":"u38"},
    "c37408484a41437d96187859f2fc3f09":{
      "scriptId":"u39"}}});